/**
 * Tests - CLI - Scaffold - App - Express.js - Run.
 *
 * @since 0.15.0
 */
export type Tests_Cli_Scaffold_App_Expressjs_CliScaffoldAppExpressjsRun_OriginalCwd = string;

export type Tests_Cli_Scaffold_App_Expressjs_CliScaffoldAppExpressjsRun_TemporaryDirectory = string;

export type Tests_Cli_Scaffold_App_Expressjs_CliScaffoldAppExpressjsRun_TemporaryBase = string;

export type Tests_Cli_Scaffold_App_Expressjs_CliScaffoldAppExpressjsRun_SandboxRoot = string;

export type Tests_Cli_Scaffold_App_Expressjs_CliScaffoldAppExpressjsRun_RootDirectory = string;

export type Tests_Cli_Scaffold_App_Expressjs_CliScaffoldAppExpressjsRun_ChildDirectory = string;

export type Tests_Cli_Scaffold_App_Expressjs_CliScaffoldAppExpressjsRun_RootPackageJson = string;

export type Tests_Cli_Scaffold_App_Expressjs_CliScaffoldAppExpressjsRun_RootPackageJsonPath = string;

export type Tests_Cli_Scaffold_App_Expressjs_CliScaffoldAppExpressjsRun_ChildPackageJson = string;

export type Tests_Cli_Scaffold_App_Expressjs_CliScaffoldAppExpressjsRun_ChildPackageJsonPath = string;

export type Tests_Cli_Scaffold_App_Expressjs_CliScaffoldAppExpressjsRun_ProjectDirectory = string;

export type Tests_Cli_Scaffold_App_Expressjs_CliScaffoldAppExpressjsRun_Exists = boolean;

export type Tests_Cli_Scaffold_App_Expressjs_CliScaffoldAppExpressjsRun_DryRunOutputPath = string;

export type Tests_Cli_Scaffold_App_Expressjs_CliScaffoldAppExpressjsRun_WorkspacePackageJsonPath = string;

export type Tests_Cli_Scaffold_App_Expressjs_CliScaffoldAppExpressjsRun_TsconfigPath = string;

export type Tests_Cli_Scaffold_App_Expressjs_CliScaffoldAppExpressjsRun_IndexTsPath = string;

export type Tests_Cli_Scaffold_App_Expressjs_CliScaffoldAppExpressjsRun_PackageJson = string;

export type Tests_Cli_Scaffold_App_Expressjs_CliScaffoldAppExpressjsRun_PackageJsonPath = string;
