run-name: "Publishing ${{ github.ref_name || 'manually' }} to Cloudflare Pages / Docusaurus[__WORKFLOW_ID__]${{ github.event_name == 'workflow_dispatch' && inputs.dry-run && ' (dry run)' || '' }}"
publish-condition: "${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && !inputs.dry-run) }}"
trigger:
  push:
    branches: [ "main" ]
