/**
 * Tests - CLI - Recipe - package.json - Cleanup - Run.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_OriginalCwd = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_TemporaryDirectory = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_SandboxPath = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_SandboxRoot = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_Output = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_Parsed = Record<string, unknown>;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_Keys = Array<string>;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_NameIndex = number;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_VersionIndex = number;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_DescriptionIndex = number;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_LicenseIndex = number;
