/**
 * Tests - CLI - Recipe - package.json - Cleanup.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_OriginalCwd = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_TemporaryDirectory = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_SandboxPath = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_SandboxRoot = string;

/**
 * Tests - CLI - Recipe - package.json - Cleanup.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_DoesNotModifyFilesDuringDryRun_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_DoesNotModifyFilesDuringDryRun_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_DoesNotModifyFilesDuringDryRun_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_DoesNotModifyFilesDuringDryRun_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_DoesNotModifyFilesDuringDryRun_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_DoesNotModifyFilesDuringDryRun_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_DoesNotModifyFilesDuringDryRun_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_DoesNotModifyFilesDuringDryRun_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_DoesNotModifyFilesDuringDryRun_Output = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_DoesNotModifyFilesDuringDryRun_Parsed = Record<string, unknown>;

/**
 * Tests - CLI - Recipe - package.json - Cleanup.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_KeepsUnknownKeysWhenRemoveUnknownKeysIsDisabledViaSettings_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_KeepsUnknownKeysWhenRemoveUnknownKeysIsDisabledViaSettings_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_KeepsUnknownKeysWhenRemoveUnknownKeysIsDisabledViaSettings_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_KeepsUnknownKeysWhenRemoveUnknownKeysIsDisabledViaSettings_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_KeepsUnknownKeysWhenRemoveUnknownKeysIsDisabledViaSettings_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_KeepsUnknownKeysWhenRemoveUnknownKeysIsDisabledViaSettings_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_KeepsUnknownKeysWhenRemoveUnknownKeysIsDisabledViaSettings_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_KeepsUnknownKeysWhenRemoveUnknownKeysIsDisabledViaSettings_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_KeepsUnknownKeysWhenRemoveUnknownKeysIsDisabledViaSettings_Output = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_KeepsUnknownKeysWhenRemoveUnknownKeysIsDisabledViaSettings_Parsed = Record<string, unknown>;

/**
 * Tests - CLI - Recipe - package.json - Cleanup.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_RemovesUnknownKeysFromPackageJson_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_RemovesUnknownKeysFromPackageJson_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_RemovesUnknownKeysFromPackageJson_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_RemovesUnknownKeysFromPackageJson_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_RemovesUnknownKeysFromPackageJson_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_RemovesUnknownKeysFromPackageJson_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_RemovesUnknownKeysFromPackageJson_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_RemovesUnknownKeysFromPackageJson_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_RemovesUnknownKeysFromPackageJson_Output = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_RemovesUnknownKeysFromPackageJson_Parsed = Record<string, unknown>;

/**
 * Tests - CLI - Recipe - package.json - Cleanup.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_ReordersPackageJsonKeysInDefinedSortOrder_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_ReordersPackageJsonKeysInDefinedSortOrder_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_ReordersPackageJsonKeysInDefinedSortOrder_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_ReordersPackageJsonKeysInDefinedSortOrder_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_ReordersPackageJsonKeysInDefinedSortOrder_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_ReordersPackageJsonKeysInDefinedSortOrder_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_ReordersPackageJsonKeysInDefinedSortOrder_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_ReordersPackageJsonKeysInDefinedSortOrder_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_ReordersPackageJsonKeysInDefinedSortOrder_Output = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_ReordersPackageJsonKeysInDefinedSortOrder_Parsed = Record<string, unknown>;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_ReordersPackageJsonKeysInDefinedSortOrder_Keys = Array<string>;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_ReordersPackageJsonKeysInDefinedSortOrder_NameIndex = number;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_ReordersPackageJsonKeysInDefinedSortOrder_VersionIndex = number;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_ReordersPackageJsonKeysInDefinedSortOrder_DescriptionIndex = number;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_ReordersPackageJsonKeysInDefinedSortOrder_LicenseIndex = number;

/**
 * Tests - CLI - Recipe - package.json - Cleanup.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_SetsExitCodeWhenNotAtProjectRoot_ProjectDirectory = string;

/**
 * Tests - CLI - Recipe - package.json - Cleanup.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_SkipsReorderingWhenReorderKeysIsDisabledViaSettings_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_SkipsReorderingWhenReorderKeysIsDisabledViaSettings_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_SkipsReorderingWhenReorderKeysIsDisabledViaSettings_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_SkipsReorderingWhenReorderKeysIsDisabledViaSettings_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_SkipsReorderingWhenReorderKeysIsDisabledViaSettings_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_SkipsReorderingWhenReorderKeysIsDisabledViaSettings_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_SkipsReorderingWhenReorderKeysIsDisabledViaSettings_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_SkipsReorderingWhenReorderKeysIsDisabledViaSettings_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_SkipsReorderingWhenReorderKeysIsDisabledViaSettings_Output = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_SkipsReorderingWhenReorderKeysIsDisabledViaSettings_Parsed = Record<string, unknown>;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_SkipsReorderingWhenReorderKeysIsDisabledViaSettings_Keys = Array<string>;

/**
 * Tests - CLI - Recipe - package.json - Cleanup.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_Output = string;

export type Tests_Cli_Recipe_PackageJson_Cleanup_CliRecipePackageJsonCleanupRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_Parsed = Record<string, unknown>;
