/**
 * Tests - CLI - Recipe - package.json - Normalize Dependencies.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_OriginalCwd = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_TemporaryDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_SandboxPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_SandboxRoot = string;

/**
 * Tests - CLI - Recipe - package.json - Normalize Dependencies.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_DoesNotModifyFilesDuringDryRun_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_DoesNotModifyFilesDuringDryRun_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_DoesNotModifyFilesDuringDryRun_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_DoesNotModifyFilesDuringDryRun_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_DoesNotModifyFilesDuringDryRun_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_DoesNotModifyFilesDuringDryRun_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_DoesNotModifyFilesDuringDryRun_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_DoesNotModifyFilesDuringDryRun_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_DoesNotModifyFilesDuringDryRun_Output = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_DoesNotModifyFilesDuringDryRun_Parsed = Record<string, unknown>;

/**
 * Tests - CLI - Recipe - package.json - Normalize Dependencies.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_MergesBundledDependenciesIntoBundleDependencies_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_MergesBundledDependenciesIntoBundleDependencies_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_MergesBundledDependenciesIntoBundleDependencies_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_MergesBundledDependenciesIntoBundleDependencies_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_MergesBundledDependenciesIntoBundleDependencies_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_MergesBundledDependenciesIntoBundleDependencies_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_MergesBundledDependenciesIntoBundleDependencies_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_MergesBundledDependenciesIntoBundleDependencies_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_MergesBundledDependenciesIntoBundleDependencies_Output = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_MergesBundledDependenciesIntoBundleDependencies_Parsed = Record<string, unknown>;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_MergesBundledDependenciesIntoBundleDependencies_IsBundleDepsArray = boolean;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_MergesBundledDependenciesIntoBundleDependencies_BundleDependencies = string[];

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_MergesBundledDependenciesIntoBundleDependencies_IncludesLodash = boolean;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_MergesBundledDependenciesIntoBundleDependencies_IncludesChalk = boolean;

/**
 * Tests - CLI - Recipe - package.json - Normalize Dependencies.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_RemovesEmptyDependencyFields_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_RemovesEmptyDependencyFields_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_RemovesEmptyDependencyFields_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_RemovesEmptyDependencyFields_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_RemovesEmptyDependencyFields_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_RemovesEmptyDependencyFields_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_RemovesEmptyDependencyFields_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_RemovesEmptyDependencyFields_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_RemovesEmptyDependencyFields_Output = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_RemovesEmptyDependencyFields_Parsed = Record<string, unknown>;

/**
 * Tests - CLI - Recipe - package.json - Normalize Dependencies.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_SetsExitCodeWhenNotAtProjectRoot_ProjectDirectory = string;

/**
 * Tests - CLI - Recipe - package.json - Normalize Dependencies.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_Output = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_Parsed = Record<string, unknown>;
