/**
 * Tests - CLI - Recipe - package.json - Normalize Bundler.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_OriginalCwd = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_TemporaryDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_SandboxPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_SandboxRoot = string;

/**
 * Tests - CLI - Recipe - package.json - Normalize Bundler.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_DoesNotModifyFilesDuringDryRun_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_DoesNotModifyFilesDuringDryRun_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_DoesNotModifyFilesDuringDryRun_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_DoesNotModifyFilesDuringDryRun_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_DoesNotModifyFilesDuringDryRun_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_DoesNotModifyFilesDuringDryRun_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_DoesNotModifyFilesDuringDryRun_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_DoesNotModifyFilesDuringDryRun_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_DoesNotModifyFilesDuringDryRun_Output = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_DoesNotModifyFilesDuringDryRun_Parsed = Record<string, unknown>;

/**
 * Tests - CLI - Recipe - package.json - Normalize Bundler.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_RemovesSideEffectsFromNonPackageRole_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_RemovesSideEffectsFromNonPackageRole_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_RemovesSideEffectsFromNonPackageRole_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_RemovesSideEffectsFromNonPackageRole_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_RemovesSideEffectsFromNonPackageRole_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_RemovesSideEffectsFromNonPackageRole_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_RemovesSideEffectsFromNonPackageRole_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_RemovesSideEffectsFromNonPackageRole_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_RemovesSideEffectsFromNonPackageRole_Output = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_RemovesSideEffectsFromNonPackageRole_Parsed = Record<string, unknown>;

/**
 * Tests - CLI - Recipe - package.json - Normalize Bundler.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_RenamesTypingsToTypes_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_RenamesTypingsToTypes_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_RenamesTypingsToTypes_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_RenamesTypingsToTypes_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_RenamesTypingsToTypes_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_RenamesTypingsToTypes_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_RenamesTypingsToTypes_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_RenamesTypingsToTypes_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_RenamesTypingsToTypes_Output = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_RenamesTypingsToTypes_Parsed = Record<string, unknown>;

/**
 * Tests - CLI - Recipe - package.json - Normalize Bundler.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_SetsExitCodeWhenNotAtProjectRoot_ProjectDirectory = string;

/**
 * Tests - CLI - Recipe - package.json - Normalize Bundler.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_Output = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_Parsed = Record<string, unknown>;
