/**
 * Tests - CLI - Recipe - package.json - Normalize Artifacts - Run.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_OriginalCwd = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_TemporaryDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_SandboxPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_SandboxRoot = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_Output = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_Parsed = Record<string, unknown>;
