/**
 * Tests - CLI - Recipe - package.json - Normalize Bundler - Run.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_OriginalCwd = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_TemporaryDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_SandboxPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_SandboxRoot = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_Output = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeBundler_CliRecipePackageJsonNormalizeBundlerRun_Parsed = Record<string, unknown>;
