/**
 * Tests - CLI - Recipe - package.json - Normalize Artifacts.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_OriginalCwd = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_TemporaryDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_SandboxPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_SandboxRoot = string;

/**
 * Tests - CLI - Recipe - package.json - Normalize Artifacts.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_DoesNotModifyFilesDuringDryRun_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_DoesNotModifyFilesDuringDryRun_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_DoesNotModifyFilesDuringDryRun_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_DoesNotModifyFilesDuringDryRun_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_DoesNotModifyFilesDuringDryRun_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_DoesNotModifyFilesDuringDryRun_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_DoesNotModifyFilesDuringDryRun_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_DoesNotModifyFilesDuringDryRun_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_DoesNotModifyFilesDuringDryRun_Output = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_DoesNotModifyFilesDuringDryRun_Parsed = Record<string, unknown>;

/**
 * Tests - CLI - Recipe - package.json - Normalize Artifacts.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_NormalizesStringBinToObjectForPackageRole_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_NormalizesStringBinToObjectForPackageRole_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_NormalizesStringBinToObjectForPackageRole_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_NormalizesStringBinToObjectForPackageRole_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_NormalizesStringBinToObjectForPackageRole_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_NormalizesStringBinToObjectForPackageRole_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_NormalizesStringBinToObjectForPackageRole_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_NormalizesStringBinToObjectForPackageRole_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_NormalizesStringBinToObjectForPackageRole_Output = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_NormalizesStringBinToObjectForPackageRole_Parsed = Record<string, unknown>;

/**
 * Tests - CLI - Recipe - package.json - Normalize Artifacts.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_SetsExitCodeWhenNotAtProjectRoot_ProjectDirectory = string;

/**
 * Tests - CLI - Recipe - package.json - Normalize Artifacts.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_SetsPrivateToTrueForNonDistributableWorkspace_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_SetsPrivateToTrueForNonDistributableWorkspace_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_SetsPrivateToTrueForNonDistributableWorkspace_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_SetsPrivateToTrueForNonDistributableWorkspace_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_SetsPrivateToTrueForNonDistributableWorkspace_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_SetsPrivateToTrueForNonDistributableWorkspace_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_SetsPrivateToTrueForNonDistributableWorkspace_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_SetsPrivateToTrueForNonDistributableWorkspace_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_SetsPrivateToTrueForNonDistributableWorkspace_Output = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_SetsPrivateToTrueForNonDistributableWorkspace_Parsed = Record<string, unknown>;

/**
 * Tests - CLI - Recipe - package.json - Normalize Artifacts.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_Output = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeArtifacts_CliRecipePackageJsonNormalizeArtifactsRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_Parsed = Record<string, unknown>;
