/**
 * Tests - CLI - Recipe - package.json - Normalize Dependencies - Run.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_OriginalCwd = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_TemporaryDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_SandboxPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_SandboxRoot = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_Output = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_Parsed = Record<string, unknown>;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_IsBundleDepsArray = boolean;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_BundleDependencies = string[];

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_IncludesLodash = boolean;

export type Tests_Cli_Recipe_PackageJson_NormalizeDependencies_CliRecipePackageJsonNormalizeDependenciesRun_IncludesChalk = boolean;
