/**
 * Tests - CLI - Recipe - package.json - Normalize Modules - Run.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_OriginalCwd = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_TemporaryDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_SandboxPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_SandboxRoot = string;

/**
 * Tests - CLI - Recipe - package.json - Normalize Modules - Run - Does Not Modify Files During Dry Run.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_DoesNotModifyFilesDuringDryRun_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_DoesNotModifyFilesDuringDryRun_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_DoesNotModifyFilesDuringDryRun_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_DoesNotModifyFilesDuringDryRun_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_DoesNotModifyFilesDuringDryRun_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_DoesNotModifyFilesDuringDryRun_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_DoesNotModifyFilesDuringDryRun_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_DoesNotModifyFilesDuringDryRun_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_DoesNotModifyFilesDuringDryRun_Output = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_DoesNotModifyFilesDuringDryRun_Parsed = Record<string, unknown>;

/**
 * Tests - CLI - Recipe - package.json - Normalize Modules - Run - Normalizes String Exports To Object For Package Role.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_NormalizesStringExportsToObjectForPackageRole_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_NormalizesStringExportsToObjectForPackageRole_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_NormalizesStringExportsToObjectForPackageRole_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_NormalizesStringExportsToObjectForPackageRole_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_NormalizesStringExportsToObjectForPackageRole_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_NormalizesStringExportsToObjectForPackageRole_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_NormalizesStringExportsToObjectForPackageRole_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_NormalizesStringExportsToObjectForPackageRole_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_NormalizesStringExportsToObjectForPackageRole_Output = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_NormalizesStringExportsToObjectForPackageRole_Parsed = Record<string, unknown>;

/**
 * Tests - CLI - Recipe - package.json - Normalize Modules - Run - Removes Exports From Non Package Role.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_RemovesExportsFromNonPackageRole_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_RemovesExportsFromNonPackageRole_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_RemovesExportsFromNonPackageRole_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_RemovesExportsFromNonPackageRole_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_RemovesExportsFromNonPackageRole_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_RemovesExportsFromNonPackageRole_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_RemovesExportsFromNonPackageRole_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_RemovesExportsFromNonPackageRole_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_RemovesExportsFromNonPackageRole_Output = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_RemovesExportsFromNonPackageRole_Parsed = Record<string, unknown>;

/**
 * Tests - CLI - Recipe - package.json - Normalize Modules - Run - Sets Exit Code When Not At Project Root.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_SetsExitCodeWhenNotAtProjectRoot_ProjectDirectory = string;

/**
 * Tests - CLI - Recipe - package.json - Normalize Modules - Run - Skips When No Workspaces Have The Recipe Enabled.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_Output = string;

export type Tests_Cli_Recipe_PackageJson_NormalizeModules_CliRecipePackageJsonNormalizeModulesRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_Parsed = Record<string, unknown>;
