/**
 * Tests - CLI - Recipe - package.json - Sync Environment - Run.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_OriginalCwd = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_TemporaryDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_SandboxPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_SandboxRoot = string;

/**
 * Tests - CLI - Recipe - package.json - Sync Environment - Run - Adds Engines Field When Missing.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_AddsEnginesFieldWhenMissing_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_AddsEnginesFieldWhenMissing_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_AddsEnginesFieldWhenMissing_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_AddsEnginesFieldWhenMissing_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_AddsEnginesFieldWhenMissing_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_AddsEnginesFieldWhenMissing_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_AddsEnginesFieldWhenMissing_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_AddsEnginesFieldWhenMissing_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_AddsEnginesFieldWhenMissing_Output = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_AddsEnginesFieldWhenMissing_Parsed = Record<string, unknown>;

/**
 * Tests - CLI - Recipe - package.json - Sync Environment - Run - Does Not Modify Files During Dry Run.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_DoesNotModifyFilesDuringDryRun_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_DoesNotModifyFilesDuringDryRun_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_DoesNotModifyFilesDuringDryRun_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_DoesNotModifyFilesDuringDryRun_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_DoesNotModifyFilesDuringDryRun_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_DoesNotModifyFilesDuringDryRun_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_DoesNotModifyFilesDuringDryRun_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_DoesNotModifyFilesDuringDryRun_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_DoesNotModifyFilesDuringDryRun_Output = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_DoesNotModifyFilesDuringDryRun_Parsed = Record<string, unknown>;

/**
 * Tests - CLI - Recipe - package.json - Sync Environment - Run - Removes Package Manager From Non Project Role.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_RemovesPackageManagerFromNonProjectRole_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_RemovesPackageManagerFromNonProjectRole_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_RemovesPackageManagerFromNonProjectRole_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_RemovesPackageManagerFromNonProjectRole_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_RemovesPackageManagerFromNonProjectRole_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_RemovesPackageManagerFromNonProjectRole_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_RemovesPackageManagerFromNonProjectRole_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_RemovesPackageManagerFromNonProjectRole_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_RemovesPackageManagerFromNonProjectRole_Output = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_RemovesPackageManagerFromNonProjectRole_Parsed = Record<string, unknown>;

/**
 * Tests - CLI - Recipe - package.json - Sync Environment - Run - Sets Exit Code When Not At Project Root.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_SetsExitCodeWhenNotAtProjectRoot_ProjectDirectory = string;

/**
 * Tests - CLI - Recipe - package.json - Sync Environment - Run - Skips When No Workspaces Have The Recipe Enabled.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_Output = string;

export type Tests_Cli_Recipe_PackageJson_SyncEnvironment_CliRecipePackageJsonSyncEnvironmentRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_Parsed = Record<string, unknown>;
