/**
 * Tests - CLI - Recipe - package.json - Sync Identity - Run.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_OriginalCwd = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_TemporaryDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SandboxPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SandboxRoot = string;

/**
 * Tests - CLI - Recipe - package.json - Sync Identity - Run - Does Not Modify Files During Dry Run.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_DoesNotModifyFilesDuringDryRun_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_DoesNotModifyFilesDuringDryRun_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_DoesNotModifyFilesDuringDryRun_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_DoesNotModifyFilesDuringDryRun_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_DoesNotModifyFilesDuringDryRun_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_DoesNotModifyFilesDuringDryRun_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_DoesNotModifyFilesDuringDryRun_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_DoesNotModifyFilesDuringDryRun_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_DoesNotModifyFilesDuringDryRun_Output = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_DoesNotModifyFilesDuringDryRun_Parsed = Record<string, unknown>;

/**
 * Tests - CLI - Recipe - package.json - Sync Identity - Run - Leaves An Unmanaged Manifest Without Display Name Untouched.
 *
 * @since 0.22.0
 */
export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_LeavesAnUnmanagedManifestWithoutDisplayNameUntouched_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_LeavesAnUnmanagedManifestWithoutDisplayNameUntouched_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_LeavesAnUnmanagedManifestWithoutDisplayNameUntouched_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_LeavesAnUnmanagedManifestWithoutDisplayNameUntouched_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_LeavesAnUnmanagedManifestWithoutDisplayNameUntouched_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_LeavesAnUnmanagedManifestWithoutDisplayNameUntouched_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_LeavesAnUnmanagedManifestWithoutDisplayNameUntouched_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_LeavesAnUnmanagedManifestWithoutDisplayNameUntouched_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_LeavesAnUnmanagedManifestWithoutDisplayNameUntouched_Output = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_LeavesAnUnmanagedManifestWithoutDisplayNameUntouched_Parsed = Record<string, unknown>;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_LeavesAnUnmanagedManifestWithoutDisplayNameUntouched_LogOutput = string;

/**
 * Tests - CLI - Recipe - package.json - Sync Identity - Run - Removes Display Name When No Project Title Is Defined.
 *
 * @since 0.22.0
 */
export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenNoProjectTitleIsDefined_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenNoProjectTitleIsDefined_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenNoProjectTitleIsDefined_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenNoProjectTitleIsDefined_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenNoProjectTitleIsDefined_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenNoProjectTitleIsDefined_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenNoProjectTitleIsDefined_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenNoProjectTitleIsDefined_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenNoProjectTitleIsDefined_Output = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenNoProjectTitleIsDefined_Parsed = Record<string, unknown>;

/**
 * Tests - CLI - Recipe - package.json - Sync Identity - Run - Removes Display Name When Not Managed For The Workspace.
 *
 * @since 0.22.0
 */
export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenNotManagedForTheWorkspace_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenNotManagedForTheWorkspace_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenNotManagedForTheWorkspace_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenNotManagedForTheWorkspace_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenNotManagedForTheWorkspace_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenNotManagedForTheWorkspace_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenNotManagedForTheWorkspace_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenNotManagedForTheWorkspace_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenNotManagedForTheWorkspace_Output = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenNotManagedForTheWorkspace_Parsed = Record<string, unknown>;

/**
 * Tests - CLI - Recipe - package.json - Sync Identity - Run - Removes Display Name When Workspace Policy Disallows It.
 *
 * @since 0.22.0
 */
export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenWorkspacePolicyDisallowsIt_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenWorkspacePolicyDisallowsIt_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenWorkspacePolicyDisallowsIt_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenWorkspacePolicyDisallowsIt_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenWorkspacePolicyDisallowsIt_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenWorkspacePolicyDisallowsIt_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenWorkspacePolicyDisallowsIt_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenWorkspacePolicyDisallowsIt_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenWorkspacePolicyDisallowsIt_Output = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_RemovesDisplayNameWhenWorkspacePolicyDisallowsIt_Parsed = Record<string, unknown>;

/**
 * Tests - CLI - Recipe - package.json - Sync Identity - Run - Sets Exit Code When Not At Project Root.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SetsExitCodeWhenNotAtProjectRoot_ProjectDirectory = string;

/**
 * Tests - CLI - Recipe - package.json - Sync Identity - Run - Sets Freezable Workspace Version To 0 0 0.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SetsFreezableWorkspaceVersionTo000_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SetsFreezableWorkspaceVersionTo000_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SetsFreezableWorkspaceVersionTo000_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SetsFreezableWorkspaceVersionTo000_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SetsFreezableWorkspaceVersionTo000_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SetsFreezableWorkspaceVersionTo000_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SetsFreezableWorkspaceVersionTo000_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SetsFreezableWorkspaceVersionTo000_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SetsFreezableWorkspaceVersionTo000_Output = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SetsFreezableWorkspaceVersionTo000_Parsed = Record<string, unknown>;

/**
 * Tests - CLI - Recipe - package.json - Sync Identity - Run - Skips When No Workspaces Have The Recipe Enabled.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_Output = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_Parsed = Record<string, unknown>;

/**
 * Tests - CLI - Recipe - package.json - Sync Identity - Run - Syncs Display Name From Project Title.
 *
 * @since 0.22.0
 */
export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsDisplayNameFromProjectTitle_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsDisplayNameFromProjectTitle_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsDisplayNameFromProjectTitle_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsDisplayNameFromProjectTitle_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsDisplayNameFromProjectTitle_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsDisplayNameFromProjectTitle_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsDisplayNameFromProjectTitle_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsDisplayNameFromProjectTitle_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsDisplayNameFromProjectTitle_Output = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsDisplayNameFromProjectTitle_Parsed = Record<string, unknown>;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsDisplayNameFromProjectTitle_MtimeBeforeSecondRun = number;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsDisplayNameFromProjectTitle_MtimeAfterSecondRun = number;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsDisplayNameFromProjectTitle_SecondRunLogOutput = string;

/**
 * Tests - CLI - Recipe - package.json - Sync Identity - Run - Syncs License To Proprietary Reference From Nova Config.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsLicenseToProprietaryReferenceFromNovaConfig_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsLicenseToProprietaryReferenceFromNovaConfig_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsLicenseToProprietaryReferenceFromNovaConfig_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsLicenseToProprietaryReferenceFromNovaConfig_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsLicenseToProprietaryReferenceFromNovaConfig_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsLicenseToProprietaryReferenceFromNovaConfig_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsLicenseToProprietaryReferenceFromNovaConfig_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsLicenseToProprietaryReferenceFromNovaConfig_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsLicenseToProprietaryReferenceFromNovaConfig_LicensePath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsLicenseToProprietaryReferenceFromNovaConfig_Output = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsLicenseToProprietaryReferenceFromNovaConfig_Parsed = Record<string, unknown>;

/**
 * Tests - CLI - Recipe - package.json - Sync Identity - Run - Syncs License To Spdx Identifier From Nova Config.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsLicenseToSpdxIdentifierFromNovaConfig_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsLicenseToSpdxIdentifierFromNovaConfig_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsLicenseToSpdxIdentifierFromNovaConfig_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsLicenseToSpdxIdentifierFromNovaConfig_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsLicenseToSpdxIdentifierFromNovaConfig_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsLicenseToSpdxIdentifierFromNovaConfig_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsLicenseToSpdxIdentifierFromNovaConfig_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsLicenseToSpdxIdentifierFromNovaConfig_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsLicenseToSpdxIdentifierFromNovaConfig_Output = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsLicenseToSpdxIdentifierFromNovaConfig_Parsed = Record<string, unknown>;

/**
 * Tests - CLI - Recipe - package.json - Sync Identity - Run - Syncs Name From Workspace Manifest.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsNameFromWorkspaceManifest_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsNameFromWorkspaceManifest_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsNameFromWorkspaceManifest_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsNameFromWorkspaceManifest_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsNameFromWorkspaceManifest_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsNameFromWorkspaceManifest_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsNameFromWorkspaceManifest_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsNameFromWorkspaceManifest_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsNameFromWorkspaceManifest_Output = string;

export type Tests_Cli_Recipe_PackageJson_SyncIdentity_CliRecipePackageJsonSyncIdentityRun_SyncsNameFromWorkspaceManifest_Parsed = Record<string, unknown>;
