/**
 * Tests - CLI - Recipe - package.json - Sync Ownership - Run.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_OriginalCwd = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_TemporaryDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_SandboxPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_SandboxRoot = string;

/**
 * Tests - CLI - Recipe - package.json - Sync Ownership - Run - Does Not Modify Files During Dry Run.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_DoesNotModifyFilesDuringDryRun_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_DoesNotModifyFilesDuringDryRun_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_DoesNotModifyFilesDuringDryRun_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_DoesNotModifyFilesDuringDryRun_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_DoesNotModifyFilesDuringDryRun_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_DoesNotModifyFilesDuringDryRun_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_DoesNotModifyFilesDuringDryRun_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_DoesNotModifyFilesDuringDryRun_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_DoesNotModifyFilesDuringDryRun_Output = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_DoesNotModifyFilesDuringDryRun_Parsed = Record<string, unknown>;

/**
 * Tests - CLI - Recipe - package.json - Sync Ownership - Run - Removes Homepage From Non Distributable Workspace.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_RemovesHomepageFromNonDistributableWorkspace_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_RemovesHomepageFromNonDistributableWorkspace_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_RemovesHomepageFromNonDistributableWorkspace_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_RemovesHomepageFromNonDistributableWorkspace_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_RemovesHomepageFromNonDistributableWorkspace_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_RemovesHomepageFromNonDistributableWorkspace_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_RemovesHomepageFromNonDistributableWorkspace_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_RemovesHomepageFromNonDistributableWorkspace_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_RemovesHomepageFromNonDistributableWorkspace_Output = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_RemovesHomepageFromNonDistributableWorkspace_Parsed = Record<string, unknown>;

/**
 * Tests - CLI - Recipe - package.json - Sync Ownership - Run - Sets Exit Code When Not At Project Root.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_SetsExitCodeWhenNotAtProjectRoot_ProjectDirectory = string;

/**
 * Tests - CLI - Recipe - package.json - Sync Ownership - Run - Skips When No Workspaces Have The Recipe Enabled.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_Output = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_SkipsWhenNoWorkspacesHaveTheRecipeEnabled_Parsed = Record<string, unknown>;

/**
 * Tests - CLI - Recipe - package.json - Sync Ownership - Run - Syncs Homepage From Nova Config.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_SyncsHomepageFromNovaConfig_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_SyncsHomepageFromNovaConfig_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_SyncsHomepageFromNovaConfig_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_SyncsHomepageFromNovaConfig_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_SyncsHomepageFromNovaConfig_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_SyncsHomepageFromNovaConfig_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_SyncsHomepageFromNovaConfig_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_SyncsHomepageFromNovaConfig_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_SyncsHomepageFromNovaConfig_Output = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_SyncsHomepageFromNovaConfig_Parsed = Record<string, unknown>;
