/**
 * Tests - CLI - Recipe - package.json - Sync Ownership - Run.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_OriginalCwd = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_TemporaryDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_SandboxPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_SandboxRoot = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_ProjectDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_WorkspaceDirectory = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_PackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_PackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_NovaConfigPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_NovaConfigContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_WorkspacePackageJsonPath = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_WorkspacePackageJsonContents = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_Output = string;

export type Tests_Cli_Recipe_PackageJson_SyncOwnership_CliRecipePackageJsonSyncOwnershipRun_Parsed = Record<string, unknown>;
