name: "Publish[__WORKFLOW_ID__]"

run-name: "[__RUN_NAME__]"

on:
[__TRIGGERS__]
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Run without making changes"
        required: false
        type: "boolean"
        default: true

permissions:
  contents: "read"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: false

env:
  PUBLISH: "[__PUBLISH_CONDITION__]"
  ROOT_DIR: "${{ vars.ROOT_WORKING_DIR }}"

jobs:
  build:
    runs-on: "ubuntu-latest"
    timeout-minutes: 15
    permissions:
      contents: "read"
[__JOBS_CONDITION__]
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v6"

      - name: "Setup Node.js"
        uses: "actions/setup-node@v6"
        with:
          node-version-file: "${{ env.ROOT_DIR }}/package.json"
          package-manager-cache: false

      - name: "Install packages"
        run: |
          npm install -g npm@latest
          npm install
        working-directory: "${{ env.ROOT_DIR }}"

      - name: "Check project"
        run: |
          [__CHECK_COMMAND__]
        working-directory: "${{ env.ROOT_DIR }}"

      - name: "Build project"
        run: |
          [__BUILD_COMMAND__]
        working-directory: "${{ env.ROOT_DIR }}"

[__UPLOAD_ARTIFACT_STEP__]
