import type { PropSidebarItem } from '@docusaurus/plugin-content-docs';

import type { CSSProperties } from 'react';

/**
 * Theme - Doc Category Generated Index Page - Doc Category Generated Index Page.
 *
 * @since 0.15.0
 */
export type Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_Navigation_Previous_Title = string;

export type Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_Navigation_Previous_Permalink = string;

export type Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_Navigation_Previous = {
  title: Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_Navigation_Previous_Title;
  permalink: Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_Navigation_Previous_Permalink;
  [key: string]: unknown;
};

export type Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_Navigation_Next_Title = string;

export type Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_Navigation_Next_Permalink = string;

export type Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_Navigation_Next = {
  title: Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_Navigation_Next_Title;
  permalink: Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_Navigation_Next_Permalink;
  [key: string]: unknown;
} | undefined;

export type Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_Navigation = {
  previous?: Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_Navigation_Previous;
  next?: Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_Navigation_Next;
};

export type Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_CategoryGeneratedIndex_Title = string;

export type Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_CategoryGeneratedIndex_Description = string | undefined;

export type Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_CategoryGeneratedIndex_Keywords = string[] | undefined;

export type Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_CategoryGeneratedIndex_Image = string | undefined;

export type Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_CategoryGeneratedIndex_Navigation = Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_Navigation;

export type Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_CategoryGeneratedIndex = {
  title: Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_CategoryGeneratedIndex_Title;
  description?: Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_CategoryGeneratedIndex_Description;
  keywords?: Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_CategoryGeneratedIndex_Keywords;
  image?: Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_CategoryGeneratedIndex_Image;
  navigation: Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_CategoryGeneratedIndex_Navigation;
  [key: string]: unknown;
};

export type Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_Props_CategoryGeneratedIndex = Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_CategoryGeneratedIndex;

export type Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_Props_ClassName = string | undefined;

export type Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_Props_Style = CSSProperties | undefined;

export type Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_Props = {
  categoryGeneratedIndex: Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_Props_CategoryGeneratedIndex;
  className?: Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_Props_ClassName;
  style?: Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_Props_Style;
  [key: string]: unknown;
};

export type Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_Category_Items = PropSidebarItem[];

export type Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_Category = {
  items: Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_Category_Items;
  [key: string]: unknown;
};

export type Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_ImageUrl = string | undefined;

export type Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_MetadataSpread = Record<string, unknown>;

export type Theme_DocCategoryGeneratedIndexPage_Index_DocCategoryGeneratedIndexPage_PaginatorSpread = Record<string, unknown>;
