import type { SidebarsConfig } from '@cbnventures/docusaurus-preset-nova/types/sidebars';

/**
 * Sidebars Configuration.
 *
 * @since 0.11.0
 */
const config: SidebarsConfig = {
  quickstart: [{
    type: 'autogenerated',
    dirName: 'quickstart',
  }],
  presets: [{
    type: 'autogenerated',
    dirName: 'presets',
  }],
  rules: [{
    type: 'autogenerated',
    dirName: 'rules',
  }],
  facades: [{
    type: 'autogenerated',
    dirName: 'facades',
  }],
  toolkit: [{
    type: 'autogenerated',
    dirName: 'toolkit',
  }],
  cli: [{
    type: 'autogenerated',
    dirName: 'cli',
  }],
};

export default config;
