import { ok, strictEqual } from 'node:assert/strict';
import {
  access,
  mkdir,
  mkdtemp,
  readFile,
  rm,
  writeFile,
} from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterAll, describe, it } from 'vitest';

import { CliGenerateGithubFunding } from '../../../../cli/generate/github/funding.js';

import type {
  TestsCliGenerateGithubFundingRunExists,
  TestsCliGenerateGithubFundingRunExpectedBanner,
  TestsCliGenerateGithubFundingRunFundingYmlPath,
  TestsCliGenerateGithubFundingRunNovaConfig,
  TestsCliGenerateGithubFundingRunNovaConfigPath,
  TestsCliGenerateGithubFundingRunOriginalCwd,
  TestsCliGenerateGithubFundingRunPackageJson,
  TestsCliGenerateGithubFundingRunPackageJsonPath,
  TestsCliGenerateGithubFundingRunProjectDirectory,
  TestsCliGenerateGithubFundingRunSandboxRoot,
  TestsCliGenerateGithubFundingRunTemporaryDirectory,
  TestsCliGenerateGithubFundingRunTemporaryPrefix,
  TestsCliGenerateGithubFundingRunWritten,
} from '../../../../types/tests/cli/generate/github/funding.test.d.ts';

/**
 * Tests - CLI - Generate - GitHub - Funding - Run.
 *
 * @since 0.15.0
 */
describe('CliGenerateGithubFunding.run', async () => {
  const originalCwd: TestsCliGenerateGithubFundingRunOriginalCwd = process.cwd();
  const temporaryDirectory: TestsCliGenerateGithubFundingRunTemporaryDirectory = tmpdir();
  const temporaryPrefix: TestsCliGenerateGithubFundingRunTemporaryPrefix = join(temporaryDirectory, `nova-${'test'}-`);
  const sandboxRoot: TestsCliGenerateGithubFundingRunSandboxRoot = await mkdtemp(temporaryPrefix);

  afterAll(async () => {
    process.chdir(originalCwd);

    await rm(sandboxRoot, {
      recursive: true,
      force: true,
    });

    return;
  });

  it('sets exit code when not at project root', async () => {
    const projectDirectory: TestsCliGenerateGithubFundingRunProjectDirectory = join(sandboxRoot, 'not-project-root');

    await mkdir(projectDirectory, { recursive: true });

    process.chdir(projectDirectory);

    await CliGenerateGithubFunding.run({});

    strictEqual(process.exitCode, 1);

    return;
  });

  it('respects dry-run', async () => {
    const projectDirectory: TestsCliGenerateGithubFundingRunProjectDirectory = join(sandboxRoot, 'dry-run');

    await mkdir(projectDirectory, { recursive: true });

    const packageJson: TestsCliGenerateGithubFundingRunPackageJson = JSON.stringify({ name: 'test' }, null, 2);

    const packageJsonPath: TestsCliGenerateGithubFundingRunPackageJsonPath = join(projectDirectory, 'package.json');

    await writeFile(packageJsonPath, `${packageJson}\n`, 'utf-8');

    const novaConfig: TestsCliGenerateGithubFundingRunNovaConfig = JSON.stringify({
      urls: {
        fundSources: ['https://github.com/sponsors/test'],
      },
    }, null, 2);

    const novaConfigPath: TestsCliGenerateGithubFundingRunNovaConfigPath = join(projectDirectory, 'nova.config.json');

    await writeFile(novaConfigPath, `${novaConfig}\n`, 'utf-8');

    process.chdir(projectDirectory);

    await CliGenerateGithubFunding.run({ dryRun: true });

    let exists: TestsCliGenerateGithubFundingRunExists = true;

    try {
      const fundingYmlPath: TestsCliGenerateGithubFundingRunFundingYmlPath = join(projectDirectory, '.github', 'FUNDING.yml');

      await access(fundingYmlPath);
    } catch {
      exists = false;
    }

    strictEqual(exists, false);

    return;
  });

  it('generates file from config', async () => {
    const projectDirectory: TestsCliGenerateGithubFundingRunProjectDirectory = join(sandboxRoot, 'generates-file');

    await mkdir(projectDirectory, { recursive: true });

    const packageJson: TestsCliGenerateGithubFundingRunPackageJson = JSON.stringify({ name: 'test' }, null, 2);

    const packageJsonPath: TestsCliGenerateGithubFundingRunPackageJsonPath = join(projectDirectory, 'package.json');

    await writeFile(packageJsonPath, `${packageJson}\n`, 'utf-8');

    const novaConfig: TestsCliGenerateGithubFundingRunNovaConfig = JSON.stringify({
      urls: {
        fundSources: ['https://github.com/sponsors/test'],
      },
    }, null, 2);

    const novaConfigPath: TestsCliGenerateGithubFundingRunNovaConfigPath = join(projectDirectory, 'nova.config.json');

    await writeFile(novaConfigPath, `${novaConfig}\n`, 'utf-8');

    process.chdir(projectDirectory);

    await CliGenerateGithubFunding.run({});

    const fundingYmlPath: TestsCliGenerateGithubFundingRunFundingYmlPath = join(projectDirectory, '.github', 'FUNDING.yml');

    await access(fundingYmlPath);

    const written: TestsCliGenerateGithubFundingRunWritten = await readFile(fundingYmlPath, 'utf-8');

    const expectedBanner: TestsCliGenerateGithubFundingRunExpectedBanner = [
      '# This file is generated by @cbnventures/nova.',
      '# Do not edit manually.',
      '#',
      '# Run `nova generate github funding` to regenerate.',
      '# See: https://nova.cbnventures.io/docs/cli/generators/github/funding',
      '',
      '',
    ].join('\n');

    ok(written.startsWith(expectedBanner));

    return;
  });

  return;
});
