import { ok, strictEqual } from 'node:assert/strict';
import {
  mkdir,
  mkdtemp,
  readFile,
  rm,
  writeFile,
} from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import {
  afterAll,
  describe,
  it,
  vi,
} from 'vitest';

import { CliGenerateGithubIssueTemplate } from '../../../../cli/generate/github/issue-template.js';

vi.mock('prompts', () => (
  {
    default: vi.fn().mockResolvedValue(
      {
        bugReportFields: [],
      },
    ),
  }
));

import type {
  TestsCliGenerateGithubIssueTemplateRunExpectedBanner,
  TestsCliGenerateGithubIssueTemplateRunIssueTemplatePath,
  TestsCliGenerateGithubIssueTemplateRunNovaConfig,
  TestsCliGenerateGithubIssueTemplateRunNovaConfigPath,
  TestsCliGenerateGithubIssueTemplateRunOriginalCwd,
  TestsCliGenerateGithubIssueTemplateRunPackageJson,
  TestsCliGenerateGithubIssueTemplateRunPackageJsonPath,
  TestsCliGenerateGithubIssueTemplateRunProjectDirectory,
  TestsCliGenerateGithubIssueTemplateRunSandboxRoot,
  TestsCliGenerateGithubIssueTemplateRunTemporaryDirectory,
  TestsCliGenerateGithubIssueTemplateRunTemporaryPrefix,
  TestsCliGenerateGithubIssueTemplateRunWritten,
} from '../../../../types/tests/cli/generate/github/issue-template.test.d.ts';

/**
 * Tests - CLI - Generate - GitHub - Issue Template - Run.
 *
 * @since 0.15.0
 */
describe('CliGenerateGithubIssueTemplate.run', async () => {
  const originalCwd: TestsCliGenerateGithubIssueTemplateRunOriginalCwd = process.cwd();
  const temporaryDirectory: TestsCliGenerateGithubIssueTemplateRunTemporaryDirectory = tmpdir();
  const temporaryPrefix: TestsCliGenerateGithubIssueTemplateRunTemporaryPrefix = join(temporaryDirectory, `nova-${'test'}-`);
  const sandboxRoot: TestsCliGenerateGithubIssueTemplateRunSandboxRoot = await mkdtemp(temporaryPrefix);

  afterAll(async () => {
    process.chdir(originalCwd);

    await rm(sandboxRoot, {
      recursive: true,
      force: true,
    });

    return;
  });

  it('sets exit code when not at project root', async () => {
    const projectDirectory: TestsCliGenerateGithubIssueTemplateRunProjectDirectory = join(sandboxRoot, 'not-project-root');

    await mkdir(projectDirectory, { recursive: true });

    process.chdir(projectDirectory);

    await CliGenerateGithubIssueTemplate.run({});

    strictEqual(process.exitCode, 1);

    return;
  });

  it('generates issue template files with header metadata', async () => {
    const projectDirectory: TestsCliGenerateGithubIssueTemplateRunProjectDirectory = join(sandboxRoot, 'generates-templates');

    await mkdir(projectDirectory, { recursive: true });

    const packageJson: TestsCliGenerateGithubIssueTemplateRunPackageJson = { name: 'test' };

    const packageJsonPath: TestsCliGenerateGithubIssueTemplateRunPackageJsonPath = join(projectDirectory, 'package.json');

    await writeFile(packageJsonPath, JSON.stringify(packageJson, null, 2));

    const novaConfig: TestsCliGenerateGithubIssueTemplateRunNovaConfig = {
      project: {
        name: { slug: 'test' },
      },
    };

    const novaConfigPath: TestsCliGenerateGithubIssueTemplateRunNovaConfigPath = join(projectDirectory, 'nova.config.json');

    await writeFile(novaConfigPath, JSON.stringify(novaConfig, null, 2));

    process.chdir(projectDirectory);

    await CliGenerateGithubIssueTemplate.run({});

    const issueTemplatePath: TestsCliGenerateGithubIssueTemplateRunIssueTemplatePath = join(projectDirectory, '.github', 'ISSUE_TEMPLATE', 'BUG-REPORT.yml');

    const written: TestsCliGenerateGithubIssueTemplateRunWritten = await readFile(issueTemplatePath, 'utf-8');

    const expectedBanner: TestsCliGenerateGithubIssueTemplateRunExpectedBanner = [
      '# This file is generated by @cbnventures/nova.',
      '# Do not edit manually.',
      '#',
      '# Run `nova generate github issue-template` to regenerate.',
      '# See: https://nova.cbnventures.io/docs/cli/generators/github/issue-template',
      '',
      '',
    ].join('\n');

    ok(written.startsWith(expectedBanner));

    return;
  });

  return;
});
