import type {
  Cli_Utility_Changelog_Runner_ValidateVersion_CurrentVersion,
  Cli_Utility_Changelog_Runner_ValidateVersion_PackageJsonPath,
  Cli_Utility_Changelog_Runner_ValidateVersion_Returns,
  Cli_Utility_Changelog_Runner_ValidateVersion_VersionStrategy,
} from '../../../cli/utility/changelog.d.ts';

/**
 * Tests - CLI - Utility - Changelog - Run.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_OriginalCwd = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_TemporaryDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SandboxPrefix = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SandboxRoot = string;

/**
 * Tests - CLI - Utility - Changelog - Run - CalVer Entry With Bump Field Errors.
 *
 * @since 0.23.0
 */
export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverEntryWithBumpFieldErrors_ProjectDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverEntryWithBumpFieldErrors_WorkspaceDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverEntryWithBumpFieldErrors_ChangelogDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverEntryWithBumpFieldErrors_PackageJsonPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverEntryWithBumpFieldErrors_PackageJsonContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverEntryWithBumpFieldErrors_ConfigPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverEntryWithBumpFieldErrors_ConfigContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverEntryWithBumpFieldErrors_WorkspacePackagePath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverEntryWithBumpFieldErrors_WorkspacePackageContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverEntryWithBumpFieldErrors_EntryPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverEntryWithBumpFieldErrors_EntryContents = string;

/**
 * Tests - CLI - Utility - Changelog - Run - CalVer Record Omits Bump From Entry File.
 *
 * @since 0.23.0
 */
export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverRecordOmitsBumpFromEntryFile_ProjectDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverRecordOmitsBumpFromEntryFile_PackageJsonPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverRecordOmitsBumpFromEntryFile_PackageJsonContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverRecordOmitsBumpFromEntryFile_ConfigPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverRecordOmitsBumpFromEntryFile_ConfigContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverRecordOmitsBumpFromEntryFile_ChangelogDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverRecordOmitsBumpFromEntryFile_Files = string[];

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverRecordOmitsBumpFromEntryFile_MdFiles = string[];

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverRecordOmitsBumpFromEntryFile_MdFile = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverRecordOmitsBumpFromEntryFile_EntryPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverRecordOmitsBumpFromEntryFile_Content = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverRecordOmitsBumpFromEntryFile_HasBump = boolean;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverRecordOmitsBumpFromEntryFile_HasPackage = boolean;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverRecordOmitsBumpFromEntryFile_HasCategory = boolean;

/**
 * Tests - CLI - Utility - Changelog - Run - CalVer Release Computes Version From Date.
 *
 * @since 0.23.0
 */
export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseComputesVersionFromDate_ProjectDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseComputesVersionFromDate_WorkspaceDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseComputesVersionFromDate_ChangelogDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseComputesVersionFromDate_PackageJsonPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseComputesVersionFromDate_PackageJsonContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseComputesVersionFromDate_ConfigPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseComputesVersionFromDate_ConfigContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseComputesVersionFromDate_WorkspacePackagePath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseComputesVersionFromDate_WorkspacePackageContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseComputesVersionFromDate_EntryPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseComputesVersionFromDate_EntryContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseComputesVersionFromDate_UpdatedPackagePath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseComputesVersionFromDate_PackageJsonRaw = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseComputesVersionFromDate_PackageJson = Record<string, unknown>;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseComputesVersionFromDate_ExpectedYear = number;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseComputesVersionFromDate_ExpectedMonth = number;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseComputesVersionFromDate_ExpectedVersion = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseComputesVersionFromDate_ChangelogPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseComputesVersionFromDate_ChangelogContent = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseComputesVersionFromDate_HasVersionHeading = boolean;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseComputesVersionFromDate_HasDateSuffix = boolean;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseComputesVersionFromDate_RemainingFiles = string[];

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseComputesVersionFromDate_RemainingMdFiles = string[];

/**
 * Tests - CLI - Utility - Changelog - Run - CalVer Release Increments Micro Within Same Month.
 *
 * @since 0.23.0
 */
export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseIncrementsMicroWithinSameMonth_ProjectDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseIncrementsMicroWithinSameMonth_WorkspaceDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseIncrementsMicroWithinSameMonth_ChangelogDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseIncrementsMicroWithinSameMonth_PackageJsonPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseIncrementsMicroWithinSameMonth_PackageJsonContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseIncrementsMicroWithinSameMonth_ConfigPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseIncrementsMicroWithinSameMonth_ConfigContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseIncrementsMicroWithinSameMonth_CurrentYear = number;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseIncrementsMicroWithinSameMonth_CurrentMonth = number;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseIncrementsMicroWithinSameMonth_CurrentVersion = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseIncrementsMicroWithinSameMonth_WorkspacePackagePath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseIncrementsMicroWithinSameMonth_WorkspacePackageContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseIncrementsMicroWithinSameMonth_EntryPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseIncrementsMicroWithinSameMonth_EntryContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseIncrementsMicroWithinSameMonth_UpdatedPackagePath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseIncrementsMicroWithinSameMonth_PackageJsonRaw = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseIncrementsMicroWithinSameMonth_PackageJson = Record<string, unknown>;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_CalverReleaseIncrementsMicroWithinSameMonth_ExpectedVersion = string;

/**
 * Tests - CLI - Utility - Changelog - Run - Dry Run Leaves UNRELEASED Tokens In Place.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_DryRunLeavesUNRELEASEDTokensInPlace_ProjectDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_DryRunLeavesUNRELEASEDTokensInPlace_WorkspaceDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_DryRunLeavesUNRELEASEDTokensInPlace_ChangelogDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_DryRunLeavesUNRELEASEDTokensInPlace_SrcDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_DryRunLeavesUNRELEASEDTokensInPlace_PackageJsonPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_DryRunLeavesUNRELEASEDTokensInPlace_PackageJsonContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_DryRunLeavesUNRELEASEDTokensInPlace_ConfigPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_DryRunLeavesUNRELEASEDTokensInPlace_ConfigContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_DryRunLeavesUNRELEASEDTokensInPlace_WorkspacePackagePath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_DryRunLeavesUNRELEASEDTokensInPlace_WorkspacePackageContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_DryRunLeavesUNRELEASEDTokensInPlace_SourceFilePath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_DryRunLeavesUNRELEASEDTokensInPlace_SourceFileContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_DryRunLeavesUNRELEASEDTokensInPlace_EntryPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_DryRunLeavesUNRELEASEDTokensInPlace_EntryContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_DryRunLeavesUNRELEASEDTokensInPlace_SourceAfterRun = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_DryRunLeavesUNRELEASEDTokensInPlace_StillHasUnreleased = boolean;

/**
 * Tests - CLI - Utility - Changelog - Run - Errors When Bump Is Invalid.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenBumpIsInvalid_ProjectDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenBumpIsInvalid_PackageJsonPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenBumpIsInvalid_PackageJsonContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenBumpIsInvalid_ConfigPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenBumpIsInvalid_ConfigContents = string;

/**
 * Tests - CLI - Utility - Changelog - Run - Errors When Category Is Invalid.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenCategoryIsInvalid_ProjectDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenCategoryIsInvalid_PackageJsonPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenCategoryIsInvalid_PackageJsonContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenCategoryIsInvalid_ConfigPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenCategoryIsInvalid_ConfigContents = string;

/**
 * Tests - CLI - Utility - Changelog - Run - Errors When Message Is Empty.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenMessageIsEmpty_ProjectDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenMessageIsEmpty_PackageJsonPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenMessageIsEmpty_PackageJsonContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenMessageIsEmpty_ConfigPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenMessageIsEmpty_ConfigContents = string;

/**
 * Tests - CLI - Utility - Changelog - Run - Errors When Package Is Invalid.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenPackageIsInvalid_ProjectDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenPackageIsInvalid_PackageJsonPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenPackageIsInvalid_PackageJsonContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenPackageIsInvalid_ConfigPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenPackageIsInvalid_ConfigContents = string;

/**
 * Tests - CLI - Utility - Changelog - Run - Errors When Partial Non Interactive Flags.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenPartialNonInteractiveFlags_ProjectDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenPartialNonInteractiveFlags_PackageJsonPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenPartialNonInteractiveFlags_PackageJsonContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenPartialNonInteractiveFlags_ConfigPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenPartialNonInteractiveFlags_ConfigContents = string;

/**
 * Tests - CLI - Utility - Changelog - Run - Errors When Record And Release Are Both Set.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenRecordAndReleaseAreBothSet_ProjectDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenRecordAndReleaseAreBothSet_PackageJsonPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenRecordAndReleaseAreBothSet_PackageJsonContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenRecordAndReleaseAreBothSet_ConfigPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenRecordAndReleaseAreBothSet_ConfigContents = string;

/**
 * Tests - CLI - Utility - Changelog - Run - Errors When Version Is Not Clean Numeric.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenVersionIsNotCleanNumeric_ProjectDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenVersionIsNotCleanNumeric_WorkspaceDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenVersionIsNotCleanNumeric_ChangelogDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenVersionIsNotCleanNumeric_PackageJsonPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenVersionIsNotCleanNumeric_PackageJsonContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenVersionIsNotCleanNumeric_ConfigPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenVersionIsNotCleanNumeric_ConfigContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenVersionIsNotCleanNumeric_WorkspacePackagePath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenVersionIsNotCleanNumeric_WorkspacePackageContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenVersionIsNotCleanNumeric_EntryPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenVersionIsNotCleanNumeric_EntryContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenVersionIsNotCleanNumeric_PackageJsonRaw = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ErrorsWhenVersionIsNotCleanNumeric_PackageJson = Record<string, unknown>;

/**
 * Tests - CLI - Utility - Changelog - Run - Keeps Pending Entries When Stamping Fails.
 *
 * @since 0.26.0
 */
export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_KeepsPendingEntriesWhenStampingFails_ProjectDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_KeepsPendingEntriesWhenStampingFails_WorkspaceDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_KeepsPendingEntriesWhenStampingFails_ChangelogDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_KeepsPendingEntriesWhenStampingFails_SourcePath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_KeepsPendingEntriesWhenStampingFails_RemainingFiles = string[];

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_KeepsPendingEntriesWhenStampingFails_RemainingMdFiles = string[];

/**
 * Tests - CLI - Utility - Changelog - Run - Prerelease Version Skips Stamp.
 *
 * Note: the normal bump arithmetic (split('.').map(Number)) always produces clean
 * semver (no '-' suffix), so the prerelease guard in stampUnreleased is not
 * reachable through the public run() API. This test exercises the closest
 * observable behavior: confirming that a non-prerelease release DOES stamp
 * (proving the guard is not blocking normal releases).
 *
 * @since 0.20.0
 */
export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_PrereleaseVersionSkipsStamp_ProjectDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_PrereleaseVersionSkipsStamp_WorkspaceDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_PrereleaseVersionSkipsStamp_ChangelogDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_PrereleaseVersionSkipsStamp_SrcDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_PrereleaseVersionSkipsStamp_PackageJsonPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_PrereleaseVersionSkipsStamp_PackageJsonContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_PrereleaseVersionSkipsStamp_ConfigPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_PrereleaseVersionSkipsStamp_ConfigContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_PrereleaseVersionSkipsStamp_WorkspacePackagePath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_PrereleaseVersionSkipsStamp_WorkspacePackageContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_PrereleaseVersionSkipsStamp_SourceFilePath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_PrereleaseVersionSkipsStamp_SourceFileContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_PrereleaseVersionSkipsStamp_EntryPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_PrereleaseVersionSkipsStamp_EntryContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_PrereleaseVersionSkipsStamp_SourceAfterRelease = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_PrereleaseVersionSkipsStamp_StampWasApplied = boolean;

/**
 * Tests - CLI - Utility - Changelog - Run - Records Entry In Non Interactive Mode.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RecordsEntryInNonInteractiveMode_ProjectDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RecordsEntryInNonInteractiveMode_PackageJsonPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RecordsEntryInNonInteractiveMode_PackageJsonContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RecordsEntryInNonInteractiveMode_ConfigPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RecordsEntryInNonInteractiveMode_ConfigContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RecordsEntryInNonInteractiveMode_ChangelogDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RecordsEntryInNonInteractiveMode_Files = string[];

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RecordsEntryInNonInteractiveMode_MdFiles = string[];

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RecordsEntryInNonInteractiveMode_MdFile = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RecordsEntryInNonInteractiveMode_EntryPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RecordsEntryInNonInteractiveMode_Content = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RecordsEntryInNonInteractiveMode_HasPackage = boolean;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RecordsEntryInNonInteractiveMode_HasCategory = boolean;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RecordsEntryInNonInteractiveMode_HasBump = boolean;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RecordsEntryInNonInteractiveMode_HasMessage = boolean;

/**
 * Tests - CLI - Utility - Changelog - Run - Rejects Lock Step Version Drift Before Writing.
 *
 * @since 0.26.0
 */
export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RejectsLockStepVersionDriftBeforeWriting_ProjectDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RejectsLockStepVersionDriftBeforeWriting_CoreDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RejectsLockStepVersionDriftBeforeWriting_ToolDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RejectsLockStepVersionDriftBeforeWriting_ChangelogDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RejectsLockStepVersionDriftBeforeWriting_PackageJsonPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RejectsLockStepVersionDriftBeforeWriting_PackageJsonContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RejectsLockStepVersionDriftBeforeWriting_ConfigPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RejectsLockStepVersionDriftBeforeWriting_ConfigContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RejectsLockStepVersionDriftBeforeWriting_CorePackagePath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RejectsLockStepVersionDriftBeforeWriting_CorePackageContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RejectsLockStepVersionDriftBeforeWriting_ToolPackagePath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RejectsLockStepVersionDriftBeforeWriting_ToolPackageContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RejectsLockStepVersionDriftBeforeWriting_EntryPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RejectsLockStepVersionDriftBeforeWriting_EntryContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RejectsLockStepVersionDriftBeforeWriting_CoreAfterRaw = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RejectsLockStepVersionDriftBeforeWriting_CoreAfter = Record<string, unknown>;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RejectsLockStepVersionDriftBeforeWriting_ToolAfterRaw = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RejectsLockStepVersionDriftBeforeWriting_ToolAfter = Record<string, unknown>;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_RejectsLockStepVersionDriftBeforeWriting_EntryAfter = string;

/**
 * Tests - CLI - Utility - Changelog - Run - Releases And Bumps Version.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ReleasesAndBumpsVersion_ProjectDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ReleasesAndBumpsVersion_WorkspaceDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ReleasesAndBumpsVersion_ChangelogDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ReleasesAndBumpsVersion_PackageJsonPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ReleasesAndBumpsVersion_PackageJsonContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ReleasesAndBumpsVersion_ConfigPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ReleasesAndBumpsVersion_ConfigContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ReleasesAndBumpsVersion_WorkspacePackagePath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ReleasesAndBumpsVersion_WorkspacePackageContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ReleasesAndBumpsVersion_EntryPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ReleasesAndBumpsVersion_EntryContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ReleasesAndBumpsVersion_UpdatedPackagePath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ReleasesAndBumpsVersion_PackageJsonRaw = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ReleasesAndBumpsVersion_PackageJson = Record<string, unknown>;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ReleasesAndBumpsVersion_ChangelogPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ReleasesAndBumpsVersion_ChangelogContent = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ReleasesAndBumpsVersion_HasVersion = boolean;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ReleasesAndBumpsVersion_HasFeature = boolean;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ReleasesAndBumpsVersion_RemainingFiles = string[];

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_ReleasesAndBumpsVersion_RemainingMdFiles = string[];

/**
 * Tests - CLI - Utility - Changelog - Run - SemVer Entry Without Bump Field Errors.
 *
 * @since 0.23.0
 */
export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SemverEntryWithoutBumpFieldErrors_ProjectDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SemverEntryWithoutBumpFieldErrors_WorkspaceDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SemverEntryWithoutBumpFieldErrors_ChangelogDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SemverEntryWithoutBumpFieldErrors_PackageJsonPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SemverEntryWithoutBumpFieldErrors_PackageJsonContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SemverEntryWithoutBumpFieldErrors_ConfigPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SemverEntryWithoutBumpFieldErrors_ConfigContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SemverEntryWithoutBumpFieldErrors_WorkspacePackagePath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SemverEntryWithoutBumpFieldErrors_WorkspacePackageContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SemverEntryWithoutBumpFieldErrors_EntryPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SemverEntryWithoutBumpFieldErrors_EntryContents = string;

/**
 * Tests - CLI - Utility - Changelog - Run - Skips Release When No Entries Exist.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SkipsReleaseWhenNoEntriesExist_ProjectDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SkipsReleaseWhenNoEntriesExist_PackageJsonPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SkipsReleaseWhenNoEntriesExist_PackageJsonContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SkipsReleaseWhenNoEntriesExist_ConfigPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SkipsReleaseWhenNoEntriesExist_ConfigContents = string;

/**
 * Tests - CLI - Utility - Changelog - Run - Stamp Is Idempotent Second Run Changes Nothing.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampIsIdempotentSecondRunChangesNothing_ProjectDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampIsIdempotentSecondRunChangesNothing_WorkspaceDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampIsIdempotentSecondRunChangesNothing_ChangelogDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampIsIdempotentSecondRunChangesNothing_SrcDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampIsIdempotentSecondRunChangesNothing_PackageJsonPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampIsIdempotentSecondRunChangesNothing_PackageJsonContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampIsIdempotentSecondRunChangesNothing_ConfigPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampIsIdempotentSecondRunChangesNothing_ConfigContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampIsIdempotentSecondRunChangesNothing_WorkspacePackagePath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampIsIdempotentSecondRunChangesNothing_WorkspacePackageContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampIsIdempotentSecondRunChangesNothing_SourceFilePath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampIsIdempotentSecondRunChangesNothing_SourceFileContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampIsIdempotentSecondRunChangesNothing_EntryPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampIsIdempotentSecondRunChangesNothing_EntryContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampIsIdempotentSecondRunChangesNothing_ContentAfterFirst = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampIsIdempotentSecondRunChangesNothing_EntryPath2 = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampIsIdempotentSecondRunChangesNothing_EntryContents2 = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampIsIdempotentSecondRunChangesNothing_ContentAfterSecond = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampIsIdempotentSecondRunChangesNothing_IsIdempotent = boolean;

/**
 * Tests - CLI - Utility - Changelog - Run - Stamps UNRELEASED Only In The Releasing Package Not In Others.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDOnlyInTheReleasingPackageNotInOthers_ProjectDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDOnlyInTheReleasingPackageNotInOthers_WorkspaceADirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDOnlyInTheReleasingPackageNotInOthers_WorkspaceBDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDOnlyInTheReleasingPackageNotInOthers_ChangelogDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDOnlyInTheReleasingPackageNotInOthers_SrcADirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDOnlyInTheReleasingPackageNotInOthers_SrcBDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDOnlyInTheReleasingPackageNotInOthers_PackageJsonPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDOnlyInTheReleasingPackageNotInOthers_PackageJsonContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDOnlyInTheReleasingPackageNotInOthers_ConfigPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDOnlyInTheReleasingPackageNotInOthers_ConfigContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDOnlyInTheReleasingPackageNotInOthers_WorkspaceAPackagePath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDOnlyInTheReleasingPackageNotInOthers_WorkspaceAPackageContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDOnlyInTheReleasingPackageNotInOthers_WorkspaceBPackagePath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDOnlyInTheReleasingPackageNotInOthers_WorkspaceBPackageContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDOnlyInTheReleasingPackageNotInOthers_SourceAFilePath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDOnlyInTheReleasingPackageNotInOthers_SourceAFileContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDOnlyInTheReleasingPackageNotInOthers_SourceBFilePath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDOnlyInTheReleasingPackageNotInOthers_SourceBFileContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDOnlyInTheReleasingPackageNotInOthers_EntryPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDOnlyInTheReleasingPackageNotInOthers_EntryContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDOnlyInTheReleasingPackageNotInOthers_UpdatedSourceA = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDOnlyInTheReleasingPackageNotInOthers_UpdatedSourceB = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDOnlyInTheReleasingPackageNotInOthers_SourceAStamped = boolean;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDOnlyInTheReleasingPackageNotInOthers_SourceBUntouched = boolean;

/**
 * Tests - CLI - Utility - Changelog - Run - Stamps UNRELEASED Tokens In Source Files On Release.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDTokensInSourceFilesOnRelease_ProjectDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDTokensInSourceFilesOnRelease_WorkspaceDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDTokensInSourceFilesOnRelease_ChangelogDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDTokensInSourceFilesOnRelease_SrcDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDTokensInSourceFilesOnRelease_PackageJsonPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDTokensInSourceFilesOnRelease_PackageJsonContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDTokensInSourceFilesOnRelease_ConfigPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDTokensInSourceFilesOnRelease_ConfigContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDTokensInSourceFilesOnRelease_WorkspacePackagePath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDTokensInSourceFilesOnRelease_WorkspacePackageContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDTokensInSourceFilesOnRelease_SourceFilePath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDTokensInSourceFilesOnRelease_SourceFileContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDTokensInSourceFilesOnRelease_EntryPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDTokensInSourceFilesOnRelease_EntryContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDTokensInSourceFilesOnRelease_UpdatedSource = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDTokensInSourceFilesOnRelease_HasSince = boolean;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDTokensInSourceFilesOnRelease_HasDeprecated = boolean;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_StampsUNRELEASEDTokensInSourceFilesOnRelease_StringLiteralPreserved = boolean;

/**
 * Tests - CLI - Utility - Changelog - Run - Syncs Exact Pinned References To Released Packages.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SyncsExactPinnedReferencesToReleasedPackages_ProjectDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SyncsExactPinnedReferencesToReleasedPackages_CoreDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SyncsExactPinnedReferencesToReleasedPackages_TemplatesDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SyncsExactPinnedReferencesToReleasedPackages_ChangelogDirectory = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SyncsExactPinnedReferencesToReleasedPackages_RootPackagePath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SyncsExactPinnedReferencesToReleasedPackages_RootPackageContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SyncsExactPinnedReferencesToReleasedPackages_ConfigPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SyncsExactPinnedReferencesToReleasedPackages_ConfigContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SyncsExactPinnedReferencesToReleasedPackages_CorePackagePath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SyncsExactPinnedReferencesToReleasedPackages_CorePackageContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SyncsExactPinnedReferencesToReleasedPackages_TemplatePackagePath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SyncsExactPinnedReferencesToReleasedPackages_TemplatePackageContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SyncsExactPinnedReferencesToReleasedPackages_EntryPath = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SyncsExactPinnedReferencesToReleasedPackages_EntryContents = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SyncsExactPinnedReferencesToReleasedPackages_TemplateRaw = string;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SyncsExactPinnedReferencesToReleasedPackages_ExactBumped = boolean;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SyncsExactPinnedReferencesToReleasedPackages_RangeKept = boolean;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SyncsExactPinnedReferencesToReleasedPackages_WorkspaceKept = boolean;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SyncsExactPinnedReferencesToReleasedPackages_ThirdPartyKept = boolean;

export type Tests_Cli_Utility_Changelog_CliUtilityChangelogRun_SyncsExactPinnedReferencesToReleasedPackages_VersionKept = boolean;

/**
 * Tests - CLI - Utility - Changelog - Validate Version.
 *
 * @since 0.26.0
 */
export type Tests_Cli_Utility_Changelog_ValidateVersion_ValidateVersion = (
  currentVersion: Cli_Utility_Changelog_Runner_ValidateVersion_CurrentVersion,
  versionStrategy: Cli_Utility_Changelog_Runner_ValidateVersion_VersionStrategy,
  packageJsonPath: Cli_Utility_Changelog_Runner_ValidateVersion_PackageJsonPath,
) => Cli_Utility_Changelog_Runner_ValidateVersion_Returns;

/**
 * Tests - CLI - Utility - Changelog - Validate Version - Allows The Initial CalVer Sentinel.
 *
 * @since 0.26.0
 */
export type Tests_Cli_Utility_Changelog_ValidateVersion_AllowsTheInitialCalVerSentinel_CurrentVersion = string;

/**
 * Tests - CLI - Utility - Changelog - Validate Version - Rejects Future CalVer.
 *
 * @since 0.26.0
 */
export type Tests_Cli_Utility_Changelog_ValidateVersion_RejectsFutureCalVer_FutureVersion = string;

/**
 * Tests - CLI - Utility - Changelog - Validate Version - Rejects Malformed CalVer.
 *
 * @since 0.26.0
 */
export type Tests_Cli_Utility_Changelog_ValidateVersion_RejectsMalformedCalVer_CurrentVersion = string;
