import type { PromptObject } from 'prompts';

import type {
  Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Options,
  Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Options_ExistingWorkspace,
  Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Options_ProjectSlug,
  Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Options_WorkspacePath,
  Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Returns,
} from '../../../cli/utility/initialize.d.ts';

/**
 * Tests - CLI - Utility - Initialize - Is Non Empty Literal Input - Returns The Error Message For An Empty String.
 *
 * @since 0.18.0
 */
export type Tests_Cli_Utility_Initialize_CliUtilityInitializeIsNonEmptyLiteralInput_ReturnsTheErrorMessageForAnEmptyString_Result = true | string;

/**
 * Tests - CLI - Utility - Initialize - Is Non Empty Literal Input - Returns The Error Message For Non String Input.
 *
 * @since 0.18.0
 */
export type Tests_Cli_Utility_Initialize_CliUtilityInitializeIsNonEmptyLiteralInput_ReturnsTheErrorMessageForNonStringInput_Result = true | string;

/**
 * Tests - CLI - Utility - Initialize - Is Non Empty Literal Input - Returns The Error Message For Whitespace Only Input.
 *
 * @since 0.18.0
 */
export type Tests_Cli_Utility_Initialize_CliUtilityInitializeIsNonEmptyLiteralInput_ReturnsTheErrorMessageForWhitespaceOnlyInput_Result = true | string;

/**
 * Tests - CLI - Utility - Initialize - Is Non Empty Literal Input - Returns True For A Non Empty String.
 *
 * @since 0.18.0
 */
export type Tests_Cli_Utility_Initialize_CliUtilityInitializeIsNonEmptyLiteralInput_ReturnsTrueForANonEmptyString_Result = true | string;

/**
 * Tests - CLI - Utility - Initialize - Run.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Utility_Initialize_CliUtilityInitializeRun_OriginalCwd = string;

export type Tests_Cli_Utility_Initialize_CliUtilityInitializeRun_TemporaryDirectory = string;

export type Tests_Cli_Utility_Initialize_CliUtilityInitializeRun_TemporaryPrefix = string;

export type Tests_Cli_Utility_Initialize_CliUtilityInitializeRun_SandboxRoot = string;

/**
 * Tests - CLI - Utility - Initialize - Run - Sets Exit Code When Not At Project Root.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Utility_Initialize_CliUtilityInitializeRun_SetsExitCodeWhenNotAtProjectRoot_ProjectDirectory = string;

/**
 * Tests - CLI - Utility - Initialize - Prompts.
 *
 * @since 0.14.0
 */
export type Tests_Cli_Utility_Initialize_Prompts_MockModule_Default = ReturnType<typeof import('vitest')['vi']['fn']>;

export type Tests_Cli_Utility_Initialize_Prompts_MockModule = Readonly<{
  default: Tests_Cli_Utility_Initialize_Prompts_MockModule_Default;
}>;

/**
 * Tests - CLI - Utility - Initialize - Prompt Workspaces Form Display Name Capture - Omits Display Name When Input Is Whitespace Only.
 *
 * @since 0.18.0
 */
export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_OmitsDisplayNameWhenInputIsWhitespaceOnly_ScriptedAnswers = Record<string, unknown>;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_OmitsDisplayNameWhenInputIsWhitespaceOnly_Question = PromptObject;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_OmitsDisplayNameWhenInputIsWhitespaceOnly_RawName = unknown;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_OmitsDisplayNameWhenInputIsWhitespaceOnly_Name = string;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_OmitsDisplayNameWhenInputIsWhitespaceOnly_HasAnswer = boolean;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_OmitsDisplayNameWhenInputIsWhitespaceOnly_Answer = unknown;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_OmitsDisplayNameWhenInputIsWhitespaceOnly_Response = Record<string, unknown>;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_OmitsDisplayNameWhenInputIsWhitespaceOnly_Form = (options: Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Options) => Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Returns;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_OmitsDisplayNameWhenInputIsWhitespaceOnly_FormOptions_WorkspacePath = Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Options_WorkspacePath;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_OmitsDisplayNameWhenInputIsWhitespaceOnly_FormOptions_ExistingWorkspace = Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Options_ExistingWorkspace;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_OmitsDisplayNameWhenInputIsWhitespaceOnly_FormOptions_ProjectSlug = Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Options_ProjectSlug;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_OmitsDisplayNameWhenInputIsWhitespaceOnly_FormOptions = Readonly<{
  workspacePath: Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_OmitsDisplayNameWhenInputIsWhitespaceOnly_FormOptions_WorkspacePath;
  existingWorkspace: Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_OmitsDisplayNameWhenInputIsWhitespaceOnly_FormOptions_ExistingWorkspace;
  projectSlug: Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_OmitsDisplayNameWhenInputIsWhitespaceOnly_FormOptions_ProjectSlug;
}>;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_OmitsDisplayNameWhenInputIsWhitespaceOnly_FormResult = Awaited<Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Returns>;

/**
 * Tests - CLI - Utility - Initialize - Prompt Workspaces Form Display Name Capture - Preserves Existing Workspace Dotenv Through The Form.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PreservesExistingWorkspaceDotenvThroughTheForm_ScriptedAnswers = Record<string, unknown>;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PreservesExistingWorkspaceDotenvThroughTheForm_Question = PromptObject;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PreservesExistingWorkspaceDotenvThroughTheForm_RawName = unknown;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PreservesExistingWorkspaceDotenvThroughTheForm_Name = string;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PreservesExistingWorkspaceDotenvThroughTheForm_Response = Record<string, unknown>;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PreservesExistingWorkspaceDotenvThroughTheForm_Form = (options: Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Options) => Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Returns;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PreservesExistingWorkspaceDotenvThroughTheForm_FormOptions_WorkspacePath = Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Options_WorkspacePath;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PreservesExistingWorkspaceDotenvThroughTheForm_FormOptions_ExistingWorkspace = Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Options_ExistingWorkspace;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PreservesExistingWorkspaceDotenvThroughTheForm_FormOptions_ProjectSlug = Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Options_ProjectSlug;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PreservesExistingWorkspaceDotenvThroughTheForm_FormOptions = Readonly<{
  workspacePath: Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PreservesExistingWorkspaceDotenvThroughTheForm_FormOptions_WorkspacePath;
  existingWorkspace: Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PreservesExistingWorkspaceDotenvThroughTheForm_FormOptions_ExistingWorkspace;
  projectSlug: Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PreservesExistingWorkspaceDotenvThroughTheForm_FormOptions_ProjectSlug;
}>;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PreservesExistingWorkspaceDotenvThroughTheForm_FormResult = Awaited<Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Returns>;

/**
 * Tests - CLI - Utility - Initialize - Prompt Workspaces Form Display Name Capture - Prompts For Workspace Display Name And Persists The Captured Value.
 *
 * @since 0.18.0
 */
export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PromptsForWorkspaceDisplayNameAndPersistsTheCapturedValue_CapturedQuestions = PromptObject[];

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PromptsForWorkspaceDisplayNameAndPersistsTheCapturedValue_ScriptedAnswers = Record<string, unknown>;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PromptsForWorkspaceDisplayNameAndPersistsTheCapturedValue_Question = PromptObject;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PromptsForWorkspaceDisplayNameAndPersistsTheCapturedValue_RawName = unknown;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PromptsForWorkspaceDisplayNameAndPersistsTheCapturedValue_Name = string;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PromptsForWorkspaceDisplayNameAndPersistsTheCapturedValue_HasAnswer = boolean;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PromptsForWorkspaceDisplayNameAndPersistsTheCapturedValue_Answer = unknown;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PromptsForWorkspaceDisplayNameAndPersistsTheCapturedValue_Response = Record<string, unknown>;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PromptsForWorkspaceDisplayNameAndPersistsTheCapturedValue_Form = (options: Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Options) => Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Returns;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PromptsForWorkspaceDisplayNameAndPersistsTheCapturedValue_FormOptions_WorkspacePath = Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Options_WorkspacePath;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PromptsForWorkspaceDisplayNameAndPersistsTheCapturedValue_FormOptions_ExistingWorkspace = Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Options_ExistingWorkspace;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PromptsForWorkspaceDisplayNameAndPersistsTheCapturedValue_FormOptions_ProjectSlug = Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Options_ProjectSlug;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PromptsForWorkspaceDisplayNameAndPersistsTheCapturedValue_FormOptions = Readonly<{
  workspacePath: Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PromptsForWorkspaceDisplayNameAndPersistsTheCapturedValue_FormOptions_WorkspacePath;
  existingWorkspace: Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PromptsForWorkspaceDisplayNameAndPersistsTheCapturedValue_FormOptions_ExistingWorkspace;
  projectSlug: Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PromptsForWorkspaceDisplayNameAndPersistsTheCapturedValue_FormOptions_ProjectSlug;
}>;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PromptsForWorkspaceDisplayNameAndPersistsTheCapturedValue_FormResult = Awaited<Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Returns>;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PromptsForWorkspaceDisplayNameAndPersistsTheCapturedValue_DisplayNameQuestion = PromptObject | undefined;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PromptsForWorkspaceDisplayNameAndPersistsTheCapturedValue_NameIndex = number;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_PromptsForWorkspaceDisplayNameAndPersistsTheCapturedValue_DisplayNameIndex = number;

/**
 * Tests - CLI - Utility - Initialize - Prompt Workspaces Form Display Name Capture - Returns Back Action When User Cancels At Display Name Prompt.
 *
 * @since 0.18.0
 */
export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_ReturnsBackActionWhenUserCancelsAtDisplayNamePrompt_ScriptedAnswers = Record<string, unknown>;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_ReturnsBackActionWhenUserCancelsAtDisplayNamePrompt_Question = PromptObject;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_ReturnsBackActionWhenUserCancelsAtDisplayNamePrompt_RawName = unknown;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_ReturnsBackActionWhenUserCancelsAtDisplayNamePrompt_Name = string;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_ReturnsBackActionWhenUserCancelsAtDisplayNamePrompt_HasAnswer = boolean;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_ReturnsBackActionWhenUserCancelsAtDisplayNamePrompt_Answer = unknown;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_ReturnsBackActionWhenUserCancelsAtDisplayNamePrompt_Response = Record<string, unknown>;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_ReturnsBackActionWhenUserCancelsAtDisplayNamePrompt_Form = (options: Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Options) => Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Returns;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_ReturnsBackActionWhenUserCancelsAtDisplayNamePrompt_FormOptions_WorkspacePath = Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Options_WorkspacePath;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_ReturnsBackActionWhenUserCancelsAtDisplayNamePrompt_FormOptions_ExistingWorkspace = Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Options_ExistingWorkspace;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_ReturnsBackActionWhenUserCancelsAtDisplayNamePrompt_FormOptions_ProjectSlug = Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Options_ProjectSlug;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_ReturnsBackActionWhenUserCancelsAtDisplayNamePrompt_FormOptions = Readonly<{
  workspacePath: Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_ReturnsBackActionWhenUserCancelsAtDisplayNamePrompt_FormOptions_WorkspacePath;
  existingWorkspace: Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_ReturnsBackActionWhenUserCancelsAtDisplayNamePrompt_FormOptions_ExistingWorkspace;
  projectSlug: Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_ReturnsBackActionWhenUserCancelsAtDisplayNamePrompt_FormOptions_ProjectSlug;
}>;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_ReturnsBackActionWhenUserCancelsAtDisplayNamePrompt_FormResult = Awaited<Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Returns>;

/**
 * Tests - CLI - Utility - Initialize - Prompt Workspaces Form Display Name Capture - Seeds Display Name Prompt Initial From Existing Workspace Display Name.
 *
 * @since 0.18.0
 */
export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_SeedsDisplayNamePromptInitialFromExistingWorkspaceDisplayName_CapturedQuestions = PromptObject[];

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_SeedsDisplayNamePromptInitialFromExistingWorkspaceDisplayName_ScriptedAnswers = Record<string, unknown>;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_SeedsDisplayNamePromptInitialFromExistingWorkspaceDisplayName_Question = PromptObject;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_SeedsDisplayNamePromptInitialFromExistingWorkspaceDisplayName_RawName = unknown;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_SeedsDisplayNamePromptInitialFromExistingWorkspaceDisplayName_Name = string;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_SeedsDisplayNamePromptInitialFromExistingWorkspaceDisplayName_HasAnswer = boolean;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_SeedsDisplayNamePromptInitialFromExistingWorkspaceDisplayName_Answer = unknown;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_SeedsDisplayNamePromptInitialFromExistingWorkspaceDisplayName_Response = Record<string, unknown>;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_SeedsDisplayNamePromptInitialFromExistingWorkspaceDisplayName_Form = (options: Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Options) => Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Returns;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_SeedsDisplayNamePromptInitialFromExistingWorkspaceDisplayName_FormOptions_WorkspacePath = Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Options_WorkspacePath;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_SeedsDisplayNamePromptInitialFromExistingWorkspaceDisplayName_FormOptions_ExistingWorkspace = Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Options_ExistingWorkspace;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_SeedsDisplayNamePromptInitialFromExistingWorkspaceDisplayName_FormOptions_ProjectSlug = Cli_Utility_Initialize_Runner_PromptWorkspacesForm_Options_ProjectSlug;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_SeedsDisplayNamePromptInitialFromExistingWorkspaceDisplayName_FormOptions = Readonly<{
  workspacePath: Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_SeedsDisplayNamePromptInitialFromExistingWorkspaceDisplayName_FormOptions_WorkspacePath;
  existingWorkspace: Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_SeedsDisplayNamePromptInitialFromExistingWorkspaceDisplayName_FormOptions_ExistingWorkspace;
  projectSlug: Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_SeedsDisplayNamePromptInitialFromExistingWorkspaceDisplayName_FormOptions_ProjectSlug;
}>;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_SeedsDisplayNamePromptInitialFromExistingWorkspaceDisplayName_DisplayNameQuestion = PromptObject | undefined;

export type Tests_Cli_Utility_Initialize_PromptWorkspacesFormDisplayNameCapture_SeedsDisplayNamePromptInitialFromExistingWorkspaceDisplayName_Initial = unknown;
