/**
 * Tests - CLI - Recipe - Miscellaneous - Fix Markdown Tables - CliRecipeMiscellaneousFixMarkdownTables Run.
 *
 * @since 0.27.0
 */
export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_OriginalCwd = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_TemporaryDirectory = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_TemporaryPrefix = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_SandboxDirectory = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_SandboxRoot = string;

/**
 * Tests - CLI - Recipe - Miscellaneous - Fix Markdown Tables - CliRecipeMiscellaneousFixMarkdownTables Run - Formats Project Root Tables From A Nested Workspace.
 *
 * @since 0.27.0
 */
export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_FormatsProjectRootTablesFromANestedWorkspace_ProjectDirectory = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_FormatsProjectRootTablesFromANestedWorkspace_NestedDirectory = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_FormatsProjectRootTablesFromANestedWorkspace_PackageJsonPath = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_FormatsProjectRootTablesFromANestedWorkspace_PackageJsonContents = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_FormatsProjectRootTablesFromANestedWorkspace_MarkdownPath = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_FormatsProjectRootTablesFromANestedWorkspace_MarkdownContents = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_FormatsProjectRootTablesFromANestedWorkspace_FormattedContents = string;

/**
 * Tests - CLI - Recipe - Miscellaneous - Fix Markdown Tables - CliRecipeMiscellaneousFixMarkdownTables Run - Preserves Fences Aligned Tables And Generated Output.
 *
 * @since 0.27.0
 */
export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_PreservesFencesAlignedTablesAndGeneratedOutput_ProjectDirectory = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_PreservesFencesAlignedTablesAndGeneratedOutput_BuildDirectory = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_PreservesFencesAlignedTablesAndGeneratedOutput_PackageJsonPath = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_PreservesFencesAlignedTablesAndGeneratedOutput_PackageJsonContents = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_PreservesFencesAlignedTablesAndGeneratedOutput_MarkdownPath = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_PreservesFencesAlignedTablesAndGeneratedOutput_MarkdownContents = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_PreservesFencesAlignedTablesAndGeneratedOutput_GeneratedPath = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_PreservesFencesAlignedTablesAndGeneratedOutput_GeneratedContents = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_PreservesFencesAlignedTablesAndGeneratedOutput_ReadMarkdownContents = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_PreservesFencesAlignedTablesAndGeneratedOutput_ReadGeneratedContents = string;

/**
 * Tests - CLI - Recipe - Miscellaneous - Fix Markdown Tables - CliRecipeMiscellaneousFixMarkdownTables Run - Previews Changes Without Writing Files.
 *
 * @since 0.27.0
 */
export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_PreviewsChangesWithoutWritingFiles_ProjectDirectory = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_PreviewsChangesWithoutWritingFiles_PackageJsonPath = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_PreviewsChangesWithoutWritingFiles_PackageJsonContents = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_PreviewsChangesWithoutWritingFiles_MarkdownPath = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_PreviewsChangesWithoutWritingFiles_MarkdownContents = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_PreviewsChangesWithoutWritingFiles_ReadMarkdownContents = string;

/**
 * Tests - CLI - Recipe - Miscellaneous - Fix Markdown Tables - CliRecipeMiscellaneousFixMarkdownTables Run - Rejects Conflicting Read Only Modes.
 *
 * @since 0.27.0
 */
export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_RejectsConflictingReadOnlyModes_Options_Check = boolean;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_RejectsConflictingReadOnlyModes_Options_DryRun = boolean;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_RejectsConflictingReadOnlyModes_Options = {
  check: Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_RejectsConflictingReadOnlyModes_Options_Check;
  dryRun: Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_RejectsConflictingReadOnlyModes_Options_DryRun;
};

/**
 * Tests - CLI - Recipe - Miscellaneous - Fix Markdown Tables - CliRecipeMiscellaneousFixMarkdownTables Run - Reports Formatting Drift Without Writing Files.
 *
 * @since 0.27.0
 */
export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_ReportsFormattingDriftWithoutWritingFiles_ProjectDirectory = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_ReportsFormattingDriftWithoutWritingFiles_PackageJsonPath = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_ReportsFormattingDriftWithoutWritingFiles_PackageJsonContents = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_ReportsFormattingDriftWithoutWritingFiles_MarkdownPath = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_ReportsFormattingDriftWithoutWritingFiles_MarkdownContents = string;

export type Tests_Cli_Recipe_Miscellaneous_FixMarkdownTables_CliRecipeMiscellaneousFixMarkdownTablesRun_ReportsFormattingDriftWithoutWritingFiles_ReadMarkdownContents = string;
