/**
 * Tests - Frontmatter - Frontmatter Config.
 *
 * @since 0.18.0
 */
export type Tests_Frontmatter_FrontmatterConfig_RequiredFields = string[];

export type Tests_Frontmatter_FrontmatterConfig_RequiredBlogFields = string[];

export type Tests_Frontmatter_FrontmatterConfig = {
  requiredFields: Tests_Frontmatter_FrontmatterConfig_RequiredFields;
  requiredBlogFields: Tests_Frontmatter_FrontmatterConfig_RequiredBlogFields;
};

/**
 * Tests - Frontmatter - Frontmatter Validation.
 *
 * @since 0.14.0
 */
export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_Cwd = string;

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_ContentDirs = string[];

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_MdFiles = string[];

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_ContentPath = string;

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_Entries = string[];

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_Ext = string;

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_Failures = string[];

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_Warnings = string[];

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_FilePath = string;

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_Content = string;

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_EndIndex = number;

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_Frontmatter = string;

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_Body = string;

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_FileExt = string;

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_FileName = string;

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_IsBlogPost = boolean;

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_IsPlaceholder = boolean;

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_Target = string[];

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_RequiredFields = string[];

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_FieldSource = string;

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_FieldRegex = RegExp;

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_IdMatch = RegExpExecArray | null;

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_Id = string;

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_ExpectedId = string;

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_DescMatch = RegExpExecArray | null;

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_KeywordsIndex = number;

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_AfterKeywords = string;

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_KeywordLines = string[];

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_Lines = string[];

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_Line = string | undefined;

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_TagsIndex = number;

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_AfterTags = string;

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_TagLines = string[];

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_TagSplitLines = string[];

export type Tests_Frontmatter_FrontmatterValidation_AllDocumentationFilesHaveValidFrontmatter_TagSplitLine = string | undefined;
