/**
 * Tests - Import - Import Validation.
 *
 * @since 0.14.0
 */
export type Tests_Import_ImportValidation_AllCodeBlockImportPathsMatchPackageJsonExports_Cwd = string;

export type Tests_Import_ImportValidation_AllCodeBlockImportPathsMatchPackageJsonExports_ContentDirs = string[];

export type Tests_Import_ImportValidation_AllCodeBlockImportPathsMatchPackageJsonExports_NovaPackagePath = string;

export type Tests_Import_ImportValidation_AllCodeBlockImportPathsMatchPackageJsonExports_NovaPackageRaw = string;

export type Tests_Import_ImportValidation_AllCodeBlockImportPathsMatchPackageJsonExports_NovaPackage = Record<string, unknown>;

export type Tests_Import_ImportValidation_AllCodeBlockImportPathsMatchPackageJsonExports_Exports = Record<string, unknown>;

export type Tests_Import_ImportValidation_AllCodeBlockImportPathsMatchPackageJsonExports_ExportKeys = string[];

export type Tests_Import_ImportValidation_AllCodeBlockImportPathsMatchPackageJsonExports_ValidSpecifiers = Set<string>;

export type Tests_Import_ImportValidation_AllCodeBlockImportPathsMatchPackageJsonExports_Specifier = string;

export type Tests_Import_ImportValidation_AllCodeBlockImportPathsMatchPackageJsonExports_MdFiles = string[];

export type Tests_Import_ImportValidation_AllCodeBlockImportPathsMatchPackageJsonExports_ContentPath = string;

export type Tests_Import_ImportValidation_AllCodeBlockImportPathsMatchPackageJsonExports_Entries = string[];

export type Tests_Import_ImportValidation_AllCodeBlockImportPathsMatchPackageJsonExports_Ext = string;

export type Tests_Import_ImportValidation_AllCodeBlockImportPathsMatchPackageJsonExports_Failures = string[];

export type Tests_Import_ImportValidation_AllCodeBlockImportPathsMatchPackageJsonExports_FilePath = string;

export type Tests_Import_ImportValidation_AllCodeBlockImportPathsMatchPackageJsonExports_Content = string;

export type Tests_Import_ImportValidation_AllCodeBlockImportPathsMatchPackageJsonExports_CodeBlock = string;

export type Tests_Import_ImportValidation_AllCodeBlockImportPathsMatchPackageJsonExports_ImportSpecifier = string;

export type Tests_Import_ImportValidation_AllCodeBlockImportPathsMatchPackageJsonExports_MatchesWildcard = boolean;

export type Tests_Import_ImportValidation_AllCodeBlockImportPathsMatchPackageJsonExports_Prefix = string;
