import type { SpawnSyncReturns } from 'node:child_process';

/**
 * Tests - Scaffold Template Source - Has TypeScript Source Counterpart.
 *
 * @since 0.26.0
 */
export type Tests_ScaffoldTemplateSource_HasTypeScriptSourceCounterpart_EmittedFile = string;

export type Tests_ScaffoldTemplateSource_HasTypeScriptSourceCounterpart_ScaffoldDirectory = string;

export type Tests_ScaffoldTemplateSource_HasTypeScriptSourceCounterpart_Returns = boolean;

export type Tests_ScaffoldTemplateSource_HasTypeScriptSourceCounterpart_EmittedExtension = string;

export type Tests_ScaffoldTemplateSource_HasTypeScriptSourceCounterpart_SourceStem = string;

export type Tests_ScaffoldTemplateSource_HasTypeScriptSourceCounterpart_SourceExtension = string;

export type Tests_ScaffoldTemplateSource_HasTypeScriptSourceCounterpart_SourceExtensions = Tests_ScaffoldTemplateSource_HasTypeScriptSourceCounterpart_SourceExtension[];

/**
 * Tests - Scaffold Template Source - Scaffold Template Source.
 *
 * @since 0.26.0
 */
export type Tests_ScaffoldTemplateSource_ScaffoldTemplateSource_PackageDirectory = string;

export type Tests_ScaffoldTemplateSource_ScaffoldTemplateSource_TemplatesDirectory = string;

export type Tests_ScaffoldTemplateSource_ScaffoldTemplateSource_ScaffoldDirectory = string;

/**
 * Tests - Scaffold Template Source - Scaffold Template Source - Contains No Emitted JavaScript Beside TypeScript Source.
 *
 * @since 0.26.0
 */
export type Tests_ScaffoldTemplateSource_ScaffoldTemplateSource_ContainsNoEmittedJavaScriptBesideTypeScriptSource_EmittedFile = string;

export type Tests_ScaffoldTemplateSource_ScaffoldTemplateSource_ContainsNoEmittedJavaScriptBesideTypeScriptSource_EmittedFiles = Tests_ScaffoldTemplateSource_ScaffoldTemplateSource_ContainsNoEmittedJavaScriptBesideTypeScriptSource_EmittedFile[];

export type Tests_ScaffoldTemplateSource_ScaffoldTemplateSource_ContainsNoEmittedJavaScriptBesideTypeScriptSource_EmittedSourcePair = string;

export type Tests_ScaffoldTemplateSource_ScaffoldTemplateSource_ContainsNoEmittedJavaScriptBesideTypeScriptSource_EmittedSourcePairs = Tests_ScaffoldTemplateSource_ScaffoldTemplateSource_ContainsNoEmittedJavaScriptBesideTypeScriptSource_EmittedSourcePair[];

export type Tests_ScaffoldTemplateSource_ScaffoldTemplateSource_ContainsNoEmittedJavaScriptBesideTypeScriptSource_FailureMessage = string;

/**
 * Tests - Scaffold Template Source - Scaffold Template Source - Contains No Git Ignored Template Files.
 *
 * @since 0.29.0
 */
export type Tests_ScaffoldTemplateSource_ScaffoldTemplateSource_ContainsNoGitIgnoredTemplateFiles_TemplateFile = string;

export type Tests_ScaffoldTemplateSource_ScaffoldTemplateSource_ContainsNoGitIgnoredTemplateFiles_TemplateFiles = Tests_ScaffoldTemplateSource_ScaffoldTemplateSource_ContainsNoGitIgnoredTemplateFiles_TemplateFile[];

export type Tests_ScaffoldTemplateSource_ScaffoldTemplateSource_ContainsNoGitIgnoredTemplateFiles_TemplatePath = string;

export type Tests_ScaffoldTemplateSource_ScaffoldTemplateSource_ContainsNoGitIgnoredTemplateFiles_TemplatePaths = Tests_ScaffoldTemplateSource_ScaffoldTemplateSource_ContainsNoGitIgnoredTemplateFiles_TemplatePath[];

export type Tests_ScaffoldTemplateSource_ScaffoldTemplateSource_ContainsNoGitIgnoredTemplateFiles_CheckIgnoreResult = SpawnSyncReturns<string>;

export type Tests_ScaffoldTemplateSource_ScaffoldTemplateSource_ContainsNoGitIgnoredTemplateFiles_IgnoredTemplateFile = string;

export type Tests_ScaffoldTemplateSource_ScaffoldTemplateSource_ContainsNoGitIgnoredTemplateFiles_IgnoredTemplateFiles = Tests_ScaffoldTemplateSource_ScaffoldTemplateSource_ContainsNoGitIgnoredTemplateFiles_IgnoredTemplateFile[];

export type Tests_ScaffoldTemplateSource_ScaffoldTemplateSource_ContainsNoGitIgnoredTemplateFiles_FailureMessage = string;
