import type { Lib_Search_Indexer_Document, Lib_Search_Indexer_Heading } from '../../../lib/search/indexer.d.ts';

/**
 * Tests - Lib - Search - Indexer.
 *
 * @since 0.15.0
 */
export type Tests_Lib_Search_Indexer_TempDirs = string[];

export type Tests_Lib_Search_Indexer_TypedTempDir = string;

/**
 * Tests - Lib - Search - Indexer - BuildSearchIndexExtractsBodyText - ExtractsArticleTextAndStripsNavAndFooter.
 *
 * @since 0.15.0
 */
export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsBodyText_ExtractsArticleTextAndStripsNavAndFooter_SystemTempDir = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsBodyText_ExtractsArticleTextAndStripsNavAndFooter_TempPathPrefix = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsBodyText_ExtractsArticleTextAndStripsNavAndFooter_TempDir = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsBodyText_ExtractsArticleTextAndStripsNavAndFooter_OutDir = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsBodyText_ExtractsArticleTextAndStripsNavAndFooter_HtmlFilePath = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsBodyText_ExtractsArticleTextAndStripsNavAndFooter_ParentDirectory = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsBodyText_ExtractsArticleTextAndStripsNavAndFooter_HtmlContent = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsBodyText_ExtractsArticleTextAndStripsNavAndFooter_RoutesPaths = string[];

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsBodyText_ExtractsArticleTextAndStripsNavAndFooter_IndexUrl = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsBodyText_ExtractsArticleTextAndStripsNavAndFooter_IndexPath = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsBodyText_ExtractsArticleTextAndStripsNavAndFooter_IndexContent = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsBodyText_ExtractsArticleTextAndStripsNavAndFooter_Payload = Record<string, unknown>;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsBodyText_ExtractsArticleTextAndStripsNavAndFooter_Documents = Lib_Search_Indexer_Document[] & {};

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsBodyText_ExtractsArticleTextAndStripsNavAndFooter_FirstDocument = Lib_Search_Indexer_Document | undefined;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsBodyText_ExtractsArticleTextAndStripsNavAndFooter_IncludesArticle = boolean;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsBodyText_ExtractsArticleTextAndStripsNavAndFooter_ExcludesNav = boolean;

/**
 * Tests - Lib - Search - Indexer - BuildSearchIndexExtractsHeadings - ExtractsH2AndH3HeadingsWithIDs.
 *
 * @since 0.15.0
 */
export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsHeadings_ExtractsH2AndH3HeadingsWithIDs_SystemTempDir = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsHeadings_ExtractsH2AndH3HeadingsWithIDs_TempPathPrefix = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsHeadings_ExtractsH2AndH3HeadingsWithIDs_TempDir = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsHeadings_ExtractsH2AndH3HeadingsWithIDs_OutDir = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsHeadings_ExtractsH2AndH3HeadingsWithIDs_HtmlFilePath = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsHeadings_ExtractsH2AndH3HeadingsWithIDs_ParentDirectory = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsHeadings_ExtractsH2AndH3HeadingsWithIDs_HtmlContent = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsHeadings_ExtractsH2AndH3HeadingsWithIDs_RoutesPaths = string[];

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsHeadings_ExtractsH2AndH3HeadingsWithIDs_IndexUrl = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsHeadings_ExtractsH2AndH3HeadingsWithIDs_IndexPath = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsHeadings_ExtractsH2AndH3HeadingsWithIDs_IndexContent = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsHeadings_ExtractsH2AndH3HeadingsWithIDs_Payload = Record<string, unknown>;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsHeadings_ExtractsH2AndH3HeadingsWithIDs_Documents = Lib_Search_Indexer_Document[] & {};

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsHeadings_ExtractsH2AndH3HeadingsWithIDs_FirstDocument = Lib_Search_Indexer_Document | undefined;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsHeadings_ExtractsH2AndH3HeadingsWithIDs_FirstHeading = Lib_Search_Indexer_Heading | undefined;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsHeadings_ExtractsH2AndH3HeadingsWithIDs_FirstHeadingId = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsHeadings_ExtractsH2AndH3HeadingsWithIDs_FirstHeadingText = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsHeadings_ExtractsH2AndH3HeadingsWithIDs_FirstHeadingLevel = number;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsHeadings_ExtractsH2AndH3HeadingsWithIDs_SecondHeading = Lib_Search_Indexer_Heading | undefined;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsHeadings_ExtractsH2AndH3HeadingsWithIDs_SecondHeadingId = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsHeadings_ExtractsH2AndH3HeadingsWithIDs_SecondHeadingText = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsHeadings_ExtractsH2AndH3HeadingsWithIDs_SecondHeadingLevel = number;

/**
 * Tests - Lib - Search - Indexer - BuildSearchIndexExtractsMetaDescription - ExtractsDescriptionFromMetaTag.
 *
 * @since 0.15.0
 */
export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsMetaDescription_ExtractsDescriptionFromMetaTag_SystemTempDir = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsMetaDescription_ExtractsDescriptionFromMetaTag_TempPathPrefix = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsMetaDescription_ExtractsDescriptionFromMetaTag_TempDir = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsMetaDescription_ExtractsDescriptionFromMetaTag_OutDir = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsMetaDescription_ExtractsDescriptionFromMetaTag_HtmlFilePath = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsMetaDescription_ExtractsDescriptionFromMetaTag_ParentDirectory = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsMetaDescription_ExtractsDescriptionFromMetaTag_HtmlContent = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsMetaDescription_ExtractsDescriptionFromMetaTag_RoutesPaths = string[];

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsMetaDescription_ExtractsDescriptionFromMetaTag_IndexUrl = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsMetaDescription_ExtractsDescriptionFromMetaTag_IndexPath = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsMetaDescription_ExtractsDescriptionFromMetaTag_IndexContent = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsMetaDescription_ExtractsDescriptionFromMetaTag_Payload = Record<string, unknown>;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsMetaDescription_ExtractsDescriptionFromMetaTag_Documents = Lib_Search_Indexer_Document[] & {};

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsMetaDescription_ExtractsDescriptionFromMetaTag_FirstDocument = Lib_Search_Indexer_Document | undefined;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsMetaDescription_ExtractsDescriptionFromMetaTag_FirstDocumentDescription = string;

/**
 * Tests - Lib - Search - Indexer - BuildSearchIndexExtractsTitle - ExtractsTitleFromTheTitleTag.
 *
 * @since 0.15.0
 */
export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsTitle_ExtractsTitleFromTheTitleTag_SystemTempDir = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsTitle_ExtractsTitleFromTheTitleTag_TempPathPrefix = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsTitle_ExtractsTitleFromTheTitleTag_TempDir = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsTitle_ExtractsTitleFromTheTitleTag_OutDir = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsTitle_ExtractsTitleFromTheTitleTag_HtmlFilePath = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsTitle_ExtractsTitleFromTheTitleTag_ParentDirectory = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsTitle_ExtractsTitleFromTheTitleTag_HtmlContent = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsTitle_ExtractsTitleFromTheTitleTag_RoutesPaths = string[];

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsTitle_ExtractsTitleFromTheTitleTag_ManifestPath = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsTitle_ExtractsTitleFromTheTitleTag_ManifestExists = boolean;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsTitle_ExtractsTitleFromTheTitleTag_ManifestContent = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsTitle_ExtractsTitleFromTheTitleTag_Manifest = Record<string, unknown>;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsTitle_ExtractsTitleFromTheTitleTag_IndexUrl = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsTitle_ExtractsTitleFromTheTitleTag_IndexPath = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsTitle_ExtractsTitleFromTheTitleTag_IndexExists = boolean;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsTitle_ExtractsTitleFromTheTitleTag_IndexContent = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsTitle_ExtractsTitleFromTheTitleTag_Payload = Record<string, unknown>;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsTitle_ExtractsTitleFromTheTitleTag_Documents = Lib_Search_Indexer_Document[] & {};

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsTitle_ExtractsTitleFromTheTitleTag_FirstDocument = Lib_Search_Indexer_Document | undefined;

export type Tests_Lib_Search_Indexer_BuildSearchIndexExtractsTitle_ExtractsTitleFromTheTitleTag_FirstDocumentTitle = string;

/**
 * Tests - Lib - Search - Indexer - BuildSearchIndexFiltersIgnoredPatterns - ExcludesPathsMatchingIgnorePatterns.
 *
 * @since 0.15.0
 */
export type Tests_Lib_Search_Indexer_BuildSearchIndexFiltersIgnoredPatterns_ExcludesPathsMatchingIgnorePatterns_SystemTempDir = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexFiltersIgnoredPatterns_ExcludesPathsMatchingIgnorePatterns_TempPathPrefix = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexFiltersIgnoredPatterns_ExcludesPathsMatchingIgnorePatterns_TempDir = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexFiltersIgnoredPatterns_ExcludesPathsMatchingIgnorePatterns_OutDir = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexFiltersIgnoredPatterns_ExcludesPathsMatchingIgnorePatterns_HtmlFilePathDocs = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexFiltersIgnoredPatterns_ExcludesPathsMatchingIgnorePatterns_HtmlFilePathAdmin = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexFiltersIgnoredPatterns_ExcludesPathsMatchingIgnorePatterns_ParentDirectoryDocs = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexFiltersIgnoredPatterns_ExcludesPathsMatchingIgnorePatterns_ParentDirectoryAdmin = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexFiltersIgnoredPatterns_ExcludesPathsMatchingIgnorePatterns_HtmlContentDocs = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexFiltersIgnoredPatterns_ExcludesPathsMatchingIgnorePatterns_HtmlContentAdmin = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexFiltersIgnoredPatterns_ExcludesPathsMatchingIgnorePatterns_RoutesPaths = string[];

export type Tests_Lib_Search_Indexer_BuildSearchIndexFiltersIgnoredPatterns_ExcludesPathsMatchingIgnorePatterns_IndexUrl = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexFiltersIgnoredPatterns_ExcludesPathsMatchingIgnorePatterns_IndexPath = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexFiltersIgnoredPatterns_ExcludesPathsMatchingIgnorePatterns_IndexContent = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexFiltersIgnoredPatterns_ExcludesPathsMatchingIgnorePatterns_Payload = Record<string, unknown>;

export type Tests_Lib_Search_Indexer_BuildSearchIndexFiltersIgnoredPatterns_ExcludesPathsMatchingIgnorePatterns_Documents = Lib_Search_Indexer_Document[] & {};

export type Tests_Lib_Search_Indexer_BuildSearchIndexFiltersIgnoredPatterns_ExcludesPathsMatchingIgnorePatterns_DocumentsLength = number;

export type Tests_Lib_Search_Indexer_BuildSearchIndexFiltersIgnoredPatterns_ExcludesPathsMatchingIgnorePatterns_FirstDocumentPath = string;

/**
 * Tests - Lib - Search - Indexer - BuildSearchIndexProducesValidLunrIndex - SerializesLunrIndexWithExpectedStructure.
 *
 * @since 0.15.0
 */
export type Tests_Lib_Search_Indexer_BuildSearchIndexProducesValidLunrIndex_SerializesLunrIndexWithExpectedStructure_SystemTempDir = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexProducesValidLunrIndex_SerializesLunrIndexWithExpectedStructure_TempPathPrefix = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexProducesValidLunrIndex_SerializesLunrIndexWithExpectedStructure_TempDir = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexProducesValidLunrIndex_SerializesLunrIndexWithExpectedStructure_OutDir = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexProducesValidLunrIndex_SerializesLunrIndexWithExpectedStructure_HtmlFilePath = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexProducesValidLunrIndex_SerializesLunrIndexWithExpectedStructure_ParentDirectory = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexProducesValidLunrIndex_SerializesLunrIndexWithExpectedStructure_HtmlContent = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexProducesValidLunrIndex_SerializesLunrIndexWithExpectedStructure_RoutesPaths = string[];

export type Tests_Lib_Search_Indexer_BuildSearchIndexProducesValidLunrIndex_SerializesLunrIndexWithExpectedStructure_IndexUrl = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexProducesValidLunrIndex_SerializesLunrIndexWithExpectedStructure_IndexPath = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexProducesValidLunrIndex_SerializesLunrIndexWithExpectedStructure_IndexContent = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexProducesValidLunrIndex_SerializesLunrIndexWithExpectedStructure_Payload = Record<string, unknown>;

export type Tests_Lib_Search_Indexer_BuildSearchIndexProducesValidLunrIndex_SerializesLunrIndexWithExpectedStructure_Index = Record<string, unknown>;

export type Tests_Lib_Search_Indexer_BuildSearchIndexProducesValidLunrIndex_SerializesLunrIndexWithExpectedStructure_HasVersion = boolean;

export type Tests_Lib_Search_Indexer_BuildSearchIndexProducesValidLunrIndex_SerializesLunrIndexWithExpectedStructure_HasFields = boolean;

export type Tests_Lib_Search_Indexer_BuildSearchIndexProducesValidLunrIndex_SerializesLunrIndexWithExpectedStructure_HasInvertedIndex = boolean;

/**
 * Tests - Lib - Search - Indexer - BuildSearchIndexRespectsIndexDocsFlag - SkipsDocsRoutesWhenIndexDocsIsFalse.
 *
 * @since 0.15.0
 */
export type Tests_Lib_Search_Indexer_BuildSearchIndexRespectsIndexDocsFlag_SkipsDocsRoutesWhenIndexDocsIsFalse_SystemTempDir = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexRespectsIndexDocsFlag_SkipsDocsRoutesWhenIndexDocsIsFalse_TempPathPrefix = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexRespectsIndexDocsFlag_SkipsDocsRoutesWhenIndexDocsIsFalse_TempDir = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexRespectsIndexDocsFlag_SkipsDocsRoutesWhenIndexDocsIsFalse_OutDir = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexRespectsIndexDocsFlag_SkipsDocsRoutesWhenIndexDocsIsFalse_HtmlFilePathDocs = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexRespectsIndexDocsFlag_SkipsDocsRoutesWhenIndexDocsIsFalse_HtmlFilePathBlog = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexRespectsIndexDocsFlag_SkipsDocsRoutesWhenIndexDocsIsFalse_ParentDirectoryDocs = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexRespectsIndexDocsFlag_SkipsDocsRoutesWhenIndexDocsIsFalse_ParentDirectoryBlog = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexRespectsIndexDocsFlag_SkipsDocsRoutesWhenIndexDocsIsFalse_HtmlContentDocs = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexRespectsIndexDocsFlag_SkipsDocsRoutesWhenIndexDocsIsFalse_HtmlContentBlog = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexRespectsIndexDocsFlag_SkipsDocsRoutesWhenIndexDocsIsFalse_RoutesPaths = string[];

export type Tests_Lib_Search_Indexer_BuildSearchIndexRespectsIndexDocsFlag_SkipsDocsRoutesWhenIndexDocsIsFalse_IndexUrl = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexRespectsIndexDocsFlag_SkipsDocsRoutesWhenIndexDocsIsFalse_IndexPath = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexRespectsIndexDocsFlag_SkipsDocsRoutesWhenIndexDocsIsFalse_IndexContent = string;

export type Tests_Lib_Search_Indexer_BuildSearchIndexRespectsIndexDocsFlag_SkipsDocsRoutesWhenIndexDocsIsFalse_Payload = Record<string, unknown>;

export type Tests_Lib_Search_Indexer_BuildSearchIndexRespectsIndexDocsFlag_SkipsDocsRoutesWhenIndexDocsIsFalse_Documents = Lib_Search_Indexer_Document[] & {};

export type Tests_Lib_Search_Indexer_BuildSearchIndexRespectsIndexDocsFlag_SkipsDocsRoutesWhenIndexDocsIsFalse_DocumentsLength = number;

export type Tests_Lib_Search_Indexer_BuildSearchIndexRespectsIndexDocsFlag_SkipsDocsRoutesWhenIndexDocsIsFalse_FirstDocumentPath = string;
