import { ok, strictEqual } from 'node:assert/strict';
import { promises as fsPromises } from 'node:fs';
import {
  mkdir,
  mkdtemp,
  readFile,
  rm,
  writeFile,
} from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  afterAll,
  afterEach,
  describe,
  it,
  vi,
} from 'vitest';

import { Runner as CliRecipeLicenseUpdateCopyright } from '../../../../cli/recipe/license/update-copyright.js';
import { Runner as LibNovaConfig } from '../../../../lib/nova-config.js';
import {
  LIB_REGEX_PLACEHOLDER_ENTITY_NAME,
  LIB_REGEX_PLACEHOLDER_YEAR_RANGE,
} from '../../../../lib/regex.js';
import * as utility from '../../../../lib/utility.js';
import * as toolkit from '../../../../toolkit/index.js';

import type {
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_BrokenSuffix,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_CustomizedLoggerMock,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_ExpectedContent,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_GoodOutput,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_GoodPath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_InfoCalls,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_IsProjectRootSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_LoadSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_LoggerCustomizeReturn,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_LoggerCustomizeSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_OriginalReadFile,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_PermissionError,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_ProjectDirectory,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_ReadFileSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_RootOutput,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_RootPath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_StaleContent,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_Template,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_Threw,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_UnreadablePath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_WarnCalls,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_CustomizedLoggerMock,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_DirLicensePath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_ExpectedContent,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_GoodOutput,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_GoodPath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_InfoCalls,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_IsProjectRootSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_LoadSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_LoggerCustomizeReturn,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_LoggerCustomizeSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_ProjectDirectory,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_RootOutput,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_RootPath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_StaleContent,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_Template,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_Threw,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_WarnCalls,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ApacheIndentedRegeneratesHolderAndYearAndKeepsBodyByteIdentical_ExpectedContent,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ApacheIndentedRegeneratesHolderAndYearAndKeepsBodyByteIdentical_IsProjectRootSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ApacheIndentedRegeneratesHolderAndYearAndKeepsBodyByteIdentical_LicensePath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ApacheIndentedRegeneratesHolderAndYearAndKeepsBodyByteIdentical_LoadSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ApacheIndentedRegeneratesHolderAndYearAndKeepsBodyByteIdentical_Output,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ApacheIndentedRegeneratesHolderAndYearAndKeepsBodyByteIdentical_ProjectDirectory,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ApacheIndentedRegeneratesHolderAndYearAndKeepsBodyByteIdentical_Template,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_BSDCommaRegeneratesHolderAndYearAndKeepsBodyByteIdentical_ExpectedContent,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_BSDCommaRegeneratesHolderAndYearAndKeepsBodyByteIdentical_IsProjectRootSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_BSDCommaRegeneratesHolderAndYearAndKeepsBodyByteIdentical_LicensePath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_BSDCommaRegeneratesHolderAndYearAndKeepsBodyByteIdentical_LoadSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_BSDCommaRegeneratesHolderAndYearAndKeepsBodyByteIdentical_Output,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_BSDCommaRegeneratesHolderAndYearAndKeepsBodyByteIdentical_ProjectDirectory,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_BSDCommaRegeneratesHolderAndYearAndKeepsBodyByteIdentical_Template,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DisabledFlagSkipsAndDoesNotWrite_IsProjectRootSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DisabledFlagSkipsAndDoesNotWrite_LicensePath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DisabledFlagSkipsAndDoesNotWrite_LoadSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DisabledFlagSkipsAndDoesNotWrite_OnDiskContent,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DisabledFlagSkipsAndDoesNotWrite_Output,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DisabledFlagSkipsAndDoesNotWrite_ProjectDirectory,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DisabledFlagSkipsAndDoesNotWrite_Template,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_ExpectedContent,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_ExpectedHolderLine,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_IsProjectRootSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_LegalName,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_LicensePath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_LoadSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_OldContent,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_Output,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_ProjectDirectory,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_Template,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_YearRange,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunDoesNotWrite_IsProjectRootSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunDoesNotWrite_LicensePath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunDoesNotWrite_LoadSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunDoesNotWrite_OnDiskContent,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunDoesNotWrite_Output,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunDoesNotWrite_ProjectDirectory,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunDoesNotWrite_Template,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_AppOutput,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_AppPath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_IsProjectRootSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_LoadSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_ProjectDirectory,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_RootOutput,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_RootPath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_SaveGeneratedFileSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_StaleContent,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_Template,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_CustomizedLoggerMock,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_InjectedHolder,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_IsProjectRootSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_LicensePath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_LoadSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_LoggerCustomizeReturn,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_LoggerCustomizeSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_OnDiskContent,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_Output,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_ProjectDirectory,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_Template,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_WarnCalls,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_AppOutput,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_AppPath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_ExpectedContent,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_IsProjectRootSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_LoadSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_PackageOutput,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_PackagePath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_ProjectDirectory,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_RootOutput,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_RootPath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_StaleContent,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_Template,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_EditedContent,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_EditedOutput,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_EditedPath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_ExpectedRootContent,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_IsProjectRootSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_LoadSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_MissingExists,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_MissingPath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_ProjectDirectory,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_RootOutput,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_RootPath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_RootStaleContent,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_Template,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_CustomizedLoggerMock,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_IsProjectRootSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_LicensePath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_LoadSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_LoggerCustomizeReturn,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_LoggerCustomizeSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_OnDiskContent,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_Output,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_ProjectDirectory,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_Template,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_WarnCalls,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_IdempotentSecondRunIsANoOp_IsProjectRootSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_IdempotentSecondRunIsANoOp_LicensePath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_IdempotentSecondRunIsANoOp_LoadSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_IdempotentSecondRunIsANoOp_OnDiskContent,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_IdempotentSecondRunIsANoOp_Output,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_IdempotentSecondRunIsANoOp_ProjectDirectory,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_IdempotentSecondRunIsANoOp_SaveGeneratedFileSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_IdempotentSecondRunIsANoOp_Template,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MissingEnableFlagSkipsAndDoesNotWrite_IsProjectRootSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MissingEnableFlagSkipsAndDoesNotWrite_LicensePath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MissingEnableFlagSkipsAndDoesNotWrite_LoadSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MissingEnableFlagSkipsAndDoesNotWrite_OnDiskContent,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MissingEnableFlagSkipsAndDoesNotWrite_Output,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MissingEnableFlagSkipsAndDoesNotWrite_ProjectDirectory,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MissingEnableFlagSkipsAndDoesNotWrite_Template,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MITRegeneratesHolderAndYearAndKeepsBodyByteIdentical_ExpectedContent,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MITRegeneratesHolderAndYearAndKeepsBodyByteIdentical_IsProjectRootSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MITRegeneratesHolderAndYearAndKeepsBodyByteIdentical_LicensePath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MITRegeneratesHolderAndYearAndKeepsBodyByteIdentical_LoadSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MITRegeneratesHolderAndYearAndKeepsBodyByteIdentical_Output,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MITRegeneratesHolderAndYearAndKeepsBodyByteIdentical_ProjectDirectory,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MITRegeneratesHolderAndYearAndKeepsBodyByteIdentical_Template,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_NonNovaLICENSEIsSkippedAndNeverRewritten_IsProjectRootSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_NonNovaLICENSEIsSkippedAndNeverRewritten_LicensePath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_NonNovaLICENSEIsSkippedAndNeverRewritten_LoadSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_NonNovaLICENSEIsSkippedAndNeverRewritten_OnDiskContent,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_NonNovaLICENSEIsSkippedAndNeverRewritten_Output,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_NonNovaLICENSEIsSkippedAndNeverRewritten_ProjectDirectory,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_OriginalCwd,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_CustomizedLoggerMock,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_InfoCalls,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_IsProjectRootSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_LicensePath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_LoadSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_LoggerCustomizeReturn,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_LoggerCustomizeSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_OnDiskContent,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_Output,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_ProjectDirectory,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_Template,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ProprietaryRegeneratesHolderAndYearAndKeepsBodyByteIdentical_ExpectedContent,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ProprietaryRegeneratesHolderAndYearAndKeepsBodyByteIdentical_IsProjectRootSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ProprietaryRegeneratesHolderAndYearAndKeepsBodyByteIdentical_LicensePath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ProprietaryRegeneratesHolderAndYearAndKeepsBodyByteIdentical_LoadSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ProprietaryRegeneratesHolderAndYearAndKeepsBodyByteIdentical_Output,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ProprietaryRegeneratesHolderAndYearAndKeepsBodyByteIdentical_ProjectDirectory,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ProprietaryRegeneratesHolderAndYearAndKeepsBodyByteIdentical_Template,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_RegexSpecialHolderRoundTripsThroughTheFingerprint_ExpectedContent,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_RegexSpecialHolderRoundTripsThroughTheFingerprint_IsProjectRootSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_RegexSpecialHolderRoundTripsThroughTheFingerprint_LicensePath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_RegexSpecialHolderRoundTripsThroughTheFingerprint_LoadSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_RegexSpecialHolderRoundTripsThroughTheFingerprint_OldContent,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_RegexSpecialHolderRoundTripsThroughTheFingerprint_Output,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_RegexSpecialHolderRoundTripsThroughTheFingerprint_ProjectDirectory,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_RegexSpecialHolderRoundTripsThroughTheFingerprint_Template,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_SandboxPath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_SandboxRoot,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_TemporaryDirectory,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_WithNoConsumerWorkspacesBehavesAsBefore_ExpectedContent,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_WithNoConsumerWorkspacesBehavesAsBefore_IsProjectRootSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_WithNoConsumerWorkspacesBehavesAsBefore_LicensePath,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_WithNoConsumerWorkspacesBehavesAsBefore_LoadSpy,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_WithNoConsumerWorkspacesBehavesAsBefore_Output,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_WithNoConsumerWorkspacesBehavesAsBefore_ProjectDirectory,
  Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_WithNoConsumerWorkspacesBehavesAsBefore_Template,
  Tests_Cli_Recipe_License_UpdateCopyright_ReadTemplate_LicenseId,
  Tests_Cli_Recipe_License_UpdateCopyright_ReadTemplate_Returns,
  Tests_Cli_Recipe_License_UpdateCopyright_ReadTemplate_TemplatePath,
  Tests_Cli_Recipe_License_UpdateCopyright_ReadTemplate_TemplatesDirectory,
  Tests_Cli_Recipe_License_UpdateCopyright_Substitute_EntityName,
  Tests_Cli_Recipe_License_UpdateCopyright_Substitute_Returns,
  Tests_Cli_Recipe_License_UpdateCopyright_Substitute_Template,
  Tests_Cli_Recipe_License_UpdateCopyright_Substitute_YearRange,
} from '../../../../types/tests/cli/recipe/license/update-copyright.test.d.ts';

/**
 * Tests - CLI - Recipe - License - Update Copyright - Read Template.
 *
 * Reads a bundled SPDX license template from the same location the recipe resolves, so
 * fixtures are byte-accurate against the real template body.
 *
 * @param {Tests_Cli_Recipe_License_UpdateCopyright_ReadTemplate_LicenseId} licenseId - License id.
 *
 * @returns {Tests_Cli_Recipe_License_UpdateCopyright_ReadTemplate_Returns}
 *
 * @since 0.20.0
 */
async function readTemplate(licenseId: Tests_Cli_Recipe_License_UpdateCopyright_ReadTemplate_LicenseId): Tests_Cli_Recipe_License_UpdateCopyright_ReadTemplate_Returns {
  const templatesDirectory: Tests_Cli_Recipe_License_UpdateCopyright_ReadTemplate_TemplatesDirectory = join(fileURLToPath(import.meta.url), '..', '..', '..', '..', '..', '..', 'templates', 'generators', 'must-haves', 'license');
  const templatePath: Tests_Cli_Recipe_License_UpdateCopyright_ReadTemplate_TemplatePath = join(templatesDirectory, licenseId);

  return readFile(templatePath, 'utf-8');
}

/**
 * Tests - CLI - Recipe - License - Update Copyright - Substitute.
 *
 * Substitutes the holder and year range placeholders into a template body exactly as the
 * license generator does, producing a nova-generated LICENSE fixture.
 *
 * @param {Tests_Cli_Recipe_License_UpdateCopyright_Substitute_Template}   template   - Template.
 * @param {Tests_Cli_Recipe_License_UpdateCopyright_Substitute_YearRange}  yearRange  - Year range.
 * @param {Tests_Cli_Recipe_License_UpdateCopyright_Substitute_EntityName} entityName - Entity name.
 *
 * @returns {Tests_Cli_Recipe_License_UpdateCopyright_Substitute_Returns}
 *
 * @since 0.20.0
 */
function substitute(template: Tests_Cli_Recipe_License_UpdateCopyright_Substitute_Template, yearRange: Tests_Cli_Recipe_License_UpdateCopyright_Substitute_YearRange, entityName: Tests_Cli_Recipe_License_UpdateCopyright_Substitute_EntityName): Tests_Cli_Recipe_License_UpdateCopyright_Substitute_Returns {
  return template
    .replace(new RegExp(LIB_REGEX_PLACEHOLDER_YEAR_RANGE.source, 'g'), () => yearRange)
    .replace(new RegExp(LIB_REGEX_PLACEHOLDER_ENTITY_NAME.source, 'g'), () => entityName);
}

/**
 * Tests - CLI - Recipe - License - Update Copyright - Run.
 *
 * @since 0.20.0
 */
describe('CliRecipeLicenseUpdateCopyright.run', async () => {
  const originalCwd: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_OriginalCwd = process.cwd();
  const temporaryDirectory: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_TemporaryDirectory = tmpdir();
  const sandboxPath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_SandboxPath = join(temporaryDirectory, `nova-${'test'}-`);
  const sandboxRoot: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_SandboxRoot = await mkdtemp(sandboxPath);

  afterEach(() => {
    vi.restoreAllMocks();

    process.chdir(originalCwd);

    process.exitCode = 0;

    return;
  });

  afterAll(async () => {
    process.chdir(originalCwd);

    await rm(sandboxRoot, {
      recursive: true,
      force: true,
    });

    return;
  });

  it('MIT regenerates holder and year and keeps body byte-identical', async () => {
    const projectDirectory: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MITRegeneratesHolderAndYearAndKeepsBodyByteIdentical_ProjectDirectory = await mkdtemp(join(sandboxRoot, 'mit-'));

    const template: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MITRegeneratesHolderAndYearAndKeepsBodyByteIdentical_Template = await readTemplate('MIT');
    const licensePath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MITRegeneratesHolderAndYearAndKeepsBodyByteIdentical_LicensePath = join(projectDirectory, 'LICENSE');

    await writeFile(licensePath, substitute(template, '2019-2024', 'Old Holder Inc.'), 'utf-8');

    const isProjectRootSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MITRegeneratesHolderAndYearAndKeepsBodyByteIdentical_IsProjectRootSpy = vi.spyOn(utility, 'isProjectRoot').mockResolvedValue(true);

    const loadSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MITRegeneratesHolderAndYearAndKeepsBodyByteIdentical_LoadSpy = vi.spyOn(LibNovaConfig.prototype, 'load').mockResolvedValue({
      project: {
        legalName: 'New Holder LLC',
        startingYear: 2019,
        license: 'MIT',
      },
      recipes: {
        license: {
          'update-copyright': {
            enabled: true,
          },
        },
      },
    });

    process.chdir(projectDirectory);

    await CliRecipeLicenseUpdateCopyright.run({
      replaceFile: true,
    });

    const output: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MITRegeneratesHolderAndYearAndKeepsBodyByteIdentical_Output = await readFile(licensePath, 'utf-8');
    const expectedContent: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MITRegeneratesHolderAndYearAndKeepsBodyByteIdentical_ExpectedContent = substitute(template, `2019-${new Date().getFullYear()}`, 'New Holder LLC');

    strictEqual(output, expectedContent);

    ok(output.includes('New Holder LLC'), 'Expected new holder in the LICENSE');
    ok(output.includes('Old Holder Inc.') === false, 'Expected old holder removed from the LICENSE');

    isProjectRootSpy.mockRestore();

    loadSpy.mockRestore();

    return;
  });

  it('Proprietary regenerates holder and year and keeps body byte-identical', async () => {
    const projectDirectory: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ProprietaryRegeneratesHolderAndYearAndKeepsBodyByteIdentical_ProjectDirectory = await mkdtemp(join(sandboxRoot, 'proprietary-'));

    const template: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ProprietaryRegeneratesHolderAndYearAndKeepsBodyByteIdentical_Template = await readTemplate('Proprietary');
    const licensePath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ProprietaryRegeneratesHolderAndYearAndKeepsBodyByteIdentical_LicensePath = join(projectDirectory, 'LICENSE');

    await writeFile(licensePath, substitute(template, '2021', 'Prior Owner'), 'utf-8');

    const isProjectRootSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ProprietaryRegeneratesHolderAndYearAndKeepsBodyByteIdentical_IsProjectRootSpy = vi.spyOn(utility, 'isProjectRoot').mockResolvedValue(true);

    const loadSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ProprietaryRegeneratesHolderAndYearAndKeepsBodyByteIdentical_LoadSpy = vi.spyOn(LibNovaConfig.prototype, 'load').mockResolvedValue({
      project: {
        legalName: 'CBN Ventures LLC',
        startingYear: 2020,
        license: 'Proprietary',
      },
      recipes: {
        license: {
          'update-copyright': {
            enabled: true,
          },
        },
      },
    });

    process.chdir(projectDirectory);

    await CliRecipeLicenseUpdateCopyright.run({
      replaceFile: true,
    });

    const output: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ProprietaryRegeneratesHolderAndYearAndKeepsBodyByteIdentical_Output = await readFile(licensePath, 'utf-8');
    const expectedContent: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ProprietaryRegeneratesHolderAndYearAndKeepsBodyByteIdentical_ExpectedContent = substitute(template, `2020-${new Date().getFullYear()}`, 'CBN Ventures LLC');

    strictEqual(output, expectedContent);

    isProjectRootSpy.mockRestore();

    loadSpy.mockRestore();

    return;
  });

  it('BSD comma regenerates holder and year and keeps body byte-identical', async () => {
    const projectDirectory: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_BSDCommaRegeneratesHolderAndYearAndKeepsBodyByteIdentical_ProjectDirectory = await mkdtemp(join(sandboxRoot, 'bsd-'));

    const template: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_BSDCommaRegeneratesHolderAndYearAndKeepsBodyByteIdentical_Template = await readTemplate('BSD-3-Clause');
    const licensePath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_BSDCommaRegeneratesHolderAndYearAndKeepsBodyByteIdentical_LicensePath = join(projectDirectory, 'LICENSE');

    await writeFile(licensePath, substitute(template, '2018', 'Original Authors'), 'utf-8');

    const isProjectRootSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_BSDCommaRegeneratesHolderAndYearAndKeepsBodyByteIdentical_IsProjectRootSpy = vi.spyOn(utility, 'isProjectRoot').mockResolvedValue(true);

    const loadSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_BSDCommaRegeneratesHolderAndYearAndKeepsBodyByteIdentical_LoadSpy = vi.spyOn(LibNovaConfig.prototype, 'load').mockResolvedValue({
      project: {
        legalName: 'Contributors Collective',
        startingYear: 2018,
        license: 'BSD-3-Clause',
      },
      recipes: {
        license: {
          'update-copyright': {
            enabled: true,
          },
        },
      },
    });

    process.chdir(projectDirectory);

    await CliRecipeLicenseUpdateCopyright.run({
      replaceFile: true,
    });

    const output: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_BSDCommaRegeneratesHolderAndYearAndKeepsBodyByteIdentical_Output = await readFile(licensePath, 'utf-8');
    const expectedContent: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_BSDCommaRegeneratesHolderAndYearAndKeepsBodyByteIdentical_ExpectedContent = substitute(template, `2018-${new Date().getFullYear()}`, 'Contributors Collective');

    strictEqual(output, expectedContent);

    // The comma between year and holder must survive untouched.
    ok(output.includes(', Contributors Collective'), 'Expected BSD comma format preserved');

    isProjectRootSpy.mockRestore();

    loadSpy.mockRestore();

    return;
  });

  it('Apache indented regenerates holder and year and keeps body byte-identical', async () => {
    const projectDirectory: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ApacheIndentedRegeneratesHolderAndYearAndKeepsBodyByteIdentical_ProjectDirectory = await mkdtemp(join(sandboxRoot, 'apache-'));

    const template: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ApacheIndentedRegeneratesHolderAndYearAndKeepsBodyByteIdentical_Template = await readTemplate('Apache-2.0');
    const licensePath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ApacheIndentedRegeneratesHolderAndYearAndKeepsBodyByteIdentical_LicensePath = join(projectDirectory, 'LICENSE');

    await writeFile(licensePath, substitute(template, '2022', 'Legacy Name'), 'utf-8');

    const isProjectRootSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ApacheIndentedRegeneratesHolderAndYearAndKeepsBodyByteIdentical_IsProjectRootSpy = vi.spyOn(utility, 'isProjectRoot').mockResolvedValue(true);

    const loadSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ApacheIndentedRegeneratesHolderAndYearAndKeepsBodyByteIdentical_LoadSpy = vi.spyOn(LibNovaConfig.prototype, 'load').mockResolvedValue({
      project: {
        legalName: 'Apache Adopter Inc.',
        startingYear: 2022,
        license: 'Apache-2.0',
      },
      recipes: {
        license: {
          'update-copyright': {
            enabled: true,
          },
        },
      },
    });

    process.chdir(projectDirectory);

    await CliRecipeLicenseUpdateCopyright.run({
      replaceFile: true,
    });

    const output: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ApacheIndentedRegeneratesHolderAndYearAndKeepsBodyByteIdentical_Output = await readFile(licensePath, 'utf-8');
    const expectedContent: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ApacheIndentedRegeneratesHolderAndYearAndKeepsBodyByteIdentical_ExpectedContent = substitute(template, `2022-${new Date().getFullYear()}`, 'Apache Adopter Inc.');

    strictEqual(output, expectedContent);

    // The indented, no-"(c)" copyright line must survive untouched.
    ok(output.includes(`   Copyright 2022-${new Date().getFullYear()} Apache Adopter Inc.`), 'Expected Apache indented copyright line preserved');

    isProjectRootSpy.mockRestore();

    loadSpy.mockRestore();

    return;
  });

  it('hand-edited LICENSE is skipped and never rewritten', async () => {
    const projectDirectory: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_ProjectDirectory = await mkdtemp(join(sandboxRoot, 'hand-edited-'));

    const template: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_Template = await readTemplate('MIT');
    const licensePath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_LicensePath = join(projectDirectory, 'LICENSE');

    // Hand-edited: a nova body with an extra appended line.
    const onDiskContent: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_OnDiskContent = `${substitute(template, '2019-2024', 'Old Holder Inc.')}${[
      '',
      'EXTRA HAND-EDITED CLAUSE.',
      '',
    ].join('\n')}`;

    await writeFile(licensePath, onDiskContent, 'utf-8');

    const isProjectRootSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_IsProjectRootSpy = vi.spyOn(utility, 'isProjectRoot').mockResolvedValue(true);

    const loadSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_LoadSpy = vi.spyOn(LibNovaConfig.prototype, 'load').mockResolvedValue({
      project: {
        legalName: 'New Holder LLC',
        startingYear: 2019,
        license: 'MIT',
      },
      recipes: {
        license: {
          'update-copyright': {
            enabled: true,
          },
        },
      },
    });

    const customizedLoggerMock: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_CustomizedLoggerMock = {
      debug: vi.fn(),
      dev: vi.fn(),
      info: vi.fn(),
      warn: vi.fn(),
      error: vi.fn(),
    };
    const loggerCustomizeSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_LoggerCustomizeSpy = vi.spyOn(toolkit['Logger'], 'customize').mockReturnValue(customizedLoggerMock as Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_LoggerCustomizeReturn);

    process.chdir(projectDirectory);

    await CliRecipeLicenseUpdateCopyright.run({
      replaceFile: true,
    });

    const output: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_Output = await readFile(licensePath, 'utf-8');

    strictEqual(output, onDiskContent);

    const warnCalls: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_WarnCalls = customizedLoggerMock['warn']['mock']['calls'];

    ok(
      warnCalls.some((call) => (
        typeof call[0] === 'string'
        && call[0].includes('hand-edited or custom') === true
      )),
      'Expected warn about a hand-edited or custom LICENSE',
    );

    isProjectRootSpy.mockRestore();

    loadSpy.mockRestore();

    loggerCustomizeSpy.mockRestore();

    return;
  });

  it('non-nova LICENSE is skipped and never rewritten', async () => {
    const projectDirectory: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_NonNovaLICENSEIsSkippedAndNeverRewritten_ProjectDirectory = await mkdtemp(join(sandboxRoot, 'non-nova-'));

    const licensePath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_NonNovaLICENSEIsSkippedAndNeverRewritten_LicensePath = join(projectDirectory, 'LICENSE');

    const onDiskContent: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_NonNovaLICENSEIsSkippedAndNeverRewritten_OnDiskContent = [
      'This project is licensed under my own bespoke terms.',
      'Copyright whoever, whenever.',
      '',
    ].join('\n');

    await writeFile(licensePath, onDiskContent, 'utf-8');

    const isProjectRootSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_NonNovaLICENSEIsSkippedAndNeverRewritten_IsProjectRootSpy = vi.spyOn(utility, 'isProjectRoot').mockResolvedValue(true);

    const loadSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_NonNovaLICENSEIsSkippedAndNeverRewritten_LoadSpy = vi.spyOn(LibNovaConfig.prototype, 'load').mockResolvedValue({
      project: {
        legalName: 'New Holder LLC',
        startingYear: 2019,
        license: 'MIT',
      },
      recipes: {
        license: {
          'update-copyright': {
            enabled: true,
          },
        },
      },
    });

    process.chdir(projectDirectory);

    await CliRecipeLicenseUpdateCopyright.run({
      replaceFile: true,
    });

    const output: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_NonNovaLICENSEIsSkippedAndNeverRewritten_Output = await readFile(licensePath, 'utf-8');

    strictEqual(output, onDiskContent);

    isProjectRootSpy.mockRestore();

    loadSpy.mockRestore();

    return;
  });

  it('regex-special holder round-trips through the fingerprint', async () => {
    const projectDirectory: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_RegexSpecialHolderRoundTripsThroughTheFingerprint_ProjectDirectory = await mkdtemp(join(sandboxRoot, 'special-'));

    const template: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_RegexSpecialHolderRoundTripsThroughTheFingerprint_Template = await readTemplate('MIT');
    const licensePath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_RegexSpecialHolderRoundTripsThroughTheFingerprint_LicensePath = join(projectDirectory, 'LICENSE');

    // On-disk holder itself contains regex metacharacters. The fingerprint capture must not
    // choke on it, and the recipe must recognize the file as nova-generated and update it.
    const oldContent: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_RegexSpecialHolderRoundTripsThroughTheFingerprint_OldContent = substitute(template, '2020', 'Corp & Co. (US) [Intl] * .+');

    await writeFile(licensePath, oldContent, 'utf-8');

    const isProjectRootSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_RegexSpecialHolderRoundTripsThroughTheFingerprint_IsProjectRootSpy = vi.spyOn(utility, 'isProjectRoot').mockResolvedValue(true);

    const loadSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_RegexSpecialHolderRoundTripsThroughTheFingerprint_LoadSpy = vi.spyOn(LibNovaConfig.prototype, 'load').mockResolvedValue({
      project: {
        legalName: 'Renamed Corp $1 \\d+ (Global)',
        startingYear: 2020,
        license: 'MIT',
      },
      recipes: {
        license: {
          'update-copyright': {
            enabled: true,
          },
        },
      },
    });

    process.chdir(projectDirectory);

    await CliRecipeLicenseUpdateCopyright.run({
      replaceFile: true,
    });

    const output: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_RegexSpecialHolderRoundTripsThroughTheFingerprint_Output = await readFile(licensePath, 'utf-8');
    const expectedContent: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_RegexSpecialHolderRoundTripsThroughTheFingerprint_ExpectedContent = substitute(template, `2020-${new Date().getFullYear()}`, 'Renamed Corp $1 \\d+ (Global)');

    strictEqual(output, expectedContent);

    ok(output.includes('Renamed Corp $1 \\d+ (Global)'), 'Expected regex-special holder written verbatim');

    isProjectRootSpy.mockRestore();

    loadSpy.mockRestore();

    return;
  });

  it('dual copyright holder is skipped and never rewritten', async () => {
    const projectDirectory: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_ProjectDirectory = await mkdtemp(join(sandboxRoot, 'dual-holder-'));

    const template: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_Template = await readTemplate('MIT');
    const licensePath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_LicensePath = join(projectDirectory, 'LICENSE');

    // Hand-edited: a legitimate second copyright-holder line inserted INSIDE the copyright
    // region, between the year/holder line and the license body. Nova only ever emits one
    // holder line, so this file is by definition not pristine-nova and must never be rewritten.
    // A newline-crossing holder capture would swallow this line into the fingerprint and let
    // the single-line regeneration silently delete it. The holder value carries the injected
    // second line so it lands inside the copyright region rather than after the body.
    const injectedHolder: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_InjectedHolder = [
      'Old Holder Inc.',
      'Copyright (c) 2019-2024 Second Holder Ltd.',
    ].join('\n');
    const onDiskContent: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_OnDiskContent = substitute(template, '2019-2024', injectedHolder);

    await writeFile(licensePath, onDiskContent, 'utf-8');

    const isProjectRootSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_IsProjectRootSpy = vi.spyOn(utility, 'isProjectRoot').mockResolvedValue(true);

    const loadSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_LoadSpy = vi.spyOn(LibNovaConfig.prototype, 'load').mockResolvedValue({
      project: {
        legalName: 'New Holder LLC',
        startingYear: 2019,
        license: 'MIT',
      },
      recipes: {
        license: {
          'update-copyright': {
            enabled: true,
          },
        },
      },
    });

    const customizedLoggerMock: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_CustomizedLoggerMock = {
      debug: vi.fn(),
      dev: vi.fn(),
      info: vi.fn(),
      warn: vi.fn(),
      error: vi.fn(),
    };
    const loggerCustomizeSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_LoggerCustomizeSpy = vi.spyOn(toolkit['Logger'], 'customize').mockReturnValue(customizedLoggerMock as Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_LoggerCustomizeReturn);

    process.chdir(projectDirectory);

    await CliRecipeLicenseUpdateCopyright.run({
      replaceFile: true,
    });

    const output: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_Output = await readFile(licensePath, 'utf-8');

    // The file is left byte-identical: the second holder line survives untouched.
    strictEqual(output, onDiskContent);

    ok(output.includes('Second Holder Ltd.'), 'Expected the second copyright holder preserved');

    const warnCalls: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_WarnCalls = customizedLoggerMock['warn']['mock']['calls'];

    ok(
      warnCalls.some((call) => (
        typeof call[0] === 'string'
        && call[0].includes('hand-edited or custom') === true
      )),
      'Expected warn about a hand-edited or custom LICENSE',
    );

    isProjectRootSpy.mockRestore();

    loadSpy.mockRestore();

    loggerCustomizeSpy.mockRestore();

    return;
  });

  it('dollar-metacharacter holder is written verbatim', async () => {
    const projectDirectory: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_ProjectDirectory = await mkdtemp(join(sandboxRoot, 'dollar-'));

    const template: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_Template = await readTemplate('MIT');
    const licensePath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_LicensePath = join(projectDirectory, 'LICENSE');

    // On-disk holder is a plain pristine-nova holder, so the fingerprint gate passes.
    const oldContent: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_OldContent = substitute(template, '2020', 'Old Holder Inc.');

    await writeFile(licensePath, oldContent, 'utf-8');

    // Holder full of replacement-string metacharacters. Each "$" sequence (dollar-apostrophe,
    // dollar-backtick, dollar-ampersand, dollar-dollar) would corrupt the output if the value
    // were passed as a replacement STRING to String.prototype.replace.
    const legalName: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_LegalName = '$\' $` $& A $$ B Corp';

    const isProjectRootSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_IsProjectRootSpy = vi.spyOn(utility, 'isProjectRoot').mockResolvedValue(true);

    const loadSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_LoadSpy = vi.spyOn(LibNovaConfig.prototype, 'load').mockResolvedValue({
      project: {
        legalName,
        startingYear: 2020,
        license: 'MIT',
      },
      recipes: {
        license: {
          'update-copyright': {
            enabled: true,
          },
        },
      },
    });

    process.chdir(projectDirectory);

    await CliRecipeLicenseUpdateCopyright.run({
      replaceFile: true,
    });

    const output: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_Output = await readFile(licensePath, 'utf-8');

    // Build the expected content by literal token replacement (split/join never interprets
    // "$" sequences) so the assertion does not depend on the substitute helper's semantics.
    const yearRange: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_YearRange = `2020-${new Date().getFullYear()}`;
    const expectedContent: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_ExpectedContent = template
      .split('[__YEAR_RANGE__]').join(yearRange)
      .split('[__ENTITY_NAME__]').join(legalName);

    strictEqual(output, expectedContent);

    // The whole holder, "$" sequences and all, must land on the copyright line verbatim.
    const expectedHolderLine: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_ExpectedHolderLine = `Copyright (c) ${yearRange} ${legalName}`;

    ok(output.includes(expectedHolderLine), 'Expected the dollar-metacharacter holder written verbatim');

    isProjectRootSpy.mockRestore();

    loadSpy.mockRestore();

    return;
  });

  it('idempotent second run is a no-op', async () => {
    const projectDirectory: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_IdempotentSecondRunIsANoOp_ProjectDirectory = await mkdtemp(join(sandboxRoot, 'idempotent-'));

    const template: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_IdempotentSecondRunIsANoOp_Template = await readTemplate('MIT');
    const licensePath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_IdempotentSecondRunIsANoOp_LicensePath = join(projectDirectory, 'LICENSE');

    // Already up to date: holder and year already match what the config resolves to.
    const onDiskContent: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_IdempotentSecondRunIsANoOp_OnDiskContent = substitute(template, `2015-${new Date().getFullYear()}`, 'Steady State Inc.');

    await writeFile(licensePath, onDiskContent, 'utf-8');

    const isProjectRootSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_IdempotentSecondRunIsANoOp_IsProjectRootSpy = vi.spyOn(utility, 'isProjectRoot').mockResolvedValue(true);

    const loadSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_IdempotentSecondRunIsANoOp_LoadSpy = vi.spyOn(LibNovaConfig.prototype, 'load').mockResolvedValue({
      project: {
        legalName: 'Steady State Inc.',
        startingYear: 2015,
        license: 'MIT',
      },
      recipes: {
        license: {
          'update-copyright': {
            enabled: true,
          },
        },
      },
    });

    const saveGeneratedFileSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_IdempotentSecondRunIsANoOp_SaveGeneratedFileSpy = vi.spyOn(utility, 'saveGeneratedFile').mockResolvedValue(undefined);

    process.chdir(projectDirectory);

    await CliRecipeLicenseUpdateCopyright.run({
      replaceFile: true,
    });

    // Already-up-to-date short circuits before any write attempt.
    strictEqual(saveGeneratedFileSpy['mock']['calls'].length, 0);

    const output: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_IdempotentSecondRunIsANoOp_Output = await readFile(licensePath, 'utf-8');

    strictEqual(output, onDiskContent);

    isProjectRootSpy.mockRestore();

    loadSpy.mockRestore();

    saveGeneratedFileSpy.mockRestore();

    return;
  });

  it('disabled flag skips and does not write', async () => {
    const projectDirectory: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DisabledFlagSkipsAndDoesNotWrite_ProjectDirectory = await mkdtemp(join(sandboxRoot, 'disabled-'));

    const template: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DisabledFlagSkipsAndDoesNotWrite_Template = await readTemplate('MIT');
    const licensePath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DisabledFlagSkipsAndDoesNotWrite_LicensePath = join(projectDirectory, 'LICENSE');

    const onDiskContent: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DisabledFlagSkipsAndDoesNotWrite_OnDiskContent = substitute(template, '2019-2024', 'Old Holder Inc.');

    await writeFile(licensePath, onDiskContent, 'utf-8');

    const isProjectRootSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DisabledFlagSkipsAndDoesNotWrite_IsProjectRootSpy = vi.spyOn(utility, 'isProjectRoot').mockResolvedValue(true);

    const loadSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DisabledFlagSkipsAndDoesNotWrite_LoadSpy = vi.spyOn(LibNovaConfig.prototype, 'load').mockResolvedValue({
      project: {
        legalName: 'New Holder LLC',
        startingYear: 2019,
        license: 'MIT',
      },
      recipes: {
        license: {
          'update-copyright': {
            enabled: false,
          },
        },
      },
    });

    process.chdir(projectDirectory);

    await CliRecipeLicenseUpdateCopyright.run({
      replaceFile: true,
    });

    const output: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DisabledFlagSkipsAndDoesNotWrite_Output = await readFile(licensePath, 'utf-8');

    strictEqual(output, onDiskContent);
    strictEqual(process.exitCode, undefined);

    isProjectRootSpy.mockRestore();

    loadSpy.mockRestore();

    return;
  });

  it('missing enable flag skips and does not write', async () => {
    const projectDirectory: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MissingEnableFlagSkipsAndDoesNotWrite_ProjectDirectory = await mkdtemp(join(sandboxRoot, 'no-flag-'));

    const template: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MissingEnableFlagSkipsAndDoesNotWrite_Template = await readTemplate('MIT');
    const licensePath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MissingEnableFlagSkipsAndDoesNotWrite_LicensePath = join(projectDirectory, 'LICENSE');

    const onDiskContent: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MissingEnableFlagSkipsAndDoesNotWrite_OnDiskContent = substitute(template, '2019-2024', 'Old Holder Inc.');

    await writeFile(licensePath, onDiskContent, 'utf-8');

    const isProjectRootSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MissingEnableFlagSkipsAndDoesNotWrite_IsProjectRootSpy = vi.spyOn(utility, 'isProjectRoot').mockResolvedValue(true);

    const loadSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MissingEnableFlagSkipsAndDoesNotWrite_LoadSpy = vi.spyOn(LibNovaConfig.prototype, 'load').mockResolvedValue({
      project: {
        legalName: 'New Holder LLC',
        startingYear: 2019,
        license: 'MIT',
      },
    });

    process.chdir(projectDirectory);

    await CliRecipeLicenseUpdateCopyright.run({
      replaceFile: true,
    });

    const output: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MissingEnableFlagSkipsAndDoesNotWrite_Output = await readFile(licensePath, 'utf-8');

    strictEqual(output, onDiskContent);
    strictEqual(process.exitCode, undefined);

    isProjectRootSpy.mockRestore();

    loadSpy.mockRestore();

    return;
  });

  it('placeholder-less template skips informationally', async () => {
    const projectDirectory: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_ProjectDirectory = await mkdtemp(join(sandboxRoot, 'cc0-'));

    const template: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_Template = await readTemplate('CC0-1.0');
    const licensePath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_LicensePath = join(projectDirectory, 'LICENSE');

    // CC0-1.0 has no placeholders, so the on-disk file is just the template verbatim.
    const onDiskContent: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_OnDiskContent = template;

    await writeFile(licensePath, onDiskContent, 'utf-8');

    const isProjectRootSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_IsProjectRootSpy = vi.spyOn(utility, 'isProjectRoot').mockResolvedValue(true);

    const loadSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_LoadSpy = vi.spyOn(LibNovaConfig.prototype, 'load').mockResolvedValue({
      project: {
        legalName: 'New Holder LLC',
        startingYear: 2019,
        license: 'CC0-1.0',
      },
      recipes: {
        license: {
          'update-copyright': {
            enabled: true,
          },
        },
      },
    });

    const customizedLoggerMock: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_CustomizedLoggerMock = {
      debug: vi.fn(),
      dev: vi.fn(),
      info: vi.fn(),
      warn: vi.fn(),
      error: vi.fn(),
    };
    const loggerCustomizeSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_LoggerCustomizeSpy = vi.spyOn(toolkit['Logger'], 'customize').mockReturnValue(customizedLoggerMock as Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_LoggerCustomizeReturn);

    process.chdir(projectDirectory);

    await CliRecipeLicenseUpdateCopyright.run({
      replaceFile: true,
    });

    const output: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_Output = await readFile(licensePath, 'utf-8');

    strictEqual(output, onDiskContent);

    const infoCalls: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_InfoCalls = customizedLoggerMock['info']['mock']['calls'];

    ok(
      infoCalls.some((call) => (
        typeof call[0] === 'string'
        && call[0].includes('no copyright holder or year to update') === true
      )),
      'Expected an informational skip for a placeholder-less license',
    );

    isProjectRootSpy.mockRestore();

    loadSpy.mockRestore();

    loggerCustomizeSpy.mockRestore();

    return;
  });

  it('dry run does not write', async () => {
    const projectDirectory: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunDoesNotWrite_ProjectDirectory = await mkdtemp(join(sandboxRoot, 'dry-run-'));

    const template: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunDoesNotWrite_Template = await readTemplate('MIT');
    const licensePath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunDoesNotWrite_LicensePath = join(projectDirectory, 'LICENSE');

    // Nova-generated but stale, so the recipe would rewrite it if not for dry run.
    const onDiskContent: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunDoesNotWrite_OnDiskContent = substitute(template, '2019-2024', 'Old Holder Inc.');

    await writeFile(licensePath, onDiskContent, 'utf-8');

    const isProjectRootSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunDoesNotWrite_IsProjectRootSpy = vi.spyOn(utility, 'isProjectRoot').mockResolvedValue(true);

    const loadSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunDoesNotWrite_LoadSpy = vi.spyOn(LibNovaConfig.prototype, 'load').mockResolvedValue({
      project: {
        legalName: 'New Holder LLC',
        startingYear: 2019,
        license: 'MIT',
      },
      recipes: {
        license: {
          'update-copyright': {
            enabled: true,
          },
        },
      },
    });

    process.chdir(projectDirectory);

    await CliRecipeLicenseUpdateCopyright.run({
      dryRun: true,
    });

    const output: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunDoesNotWrite_Output = await readFile(licensePath, 'utf-8');

    // The file is unchanged because dry run never writes.
    strictEqual(output, onDiskContent);

    isProjectRootSpy.mockRestore();

    loadSpy.mockRestore();

    return;
  });

  it('fans out to every consumer workspace LICENSE', async () => {
    const projectDirectory: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_ProjectDirectory = await mkdtemp(join(sandboxRoot, 'fan-out-'));

    const template: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_Template = await readTemplate('MIT');

    const rootPath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_RootPath = join(projectDirectory, 'LICENSE');
    const appPath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_AppPath = join(projectDirectory, 'apps', 'web', 'LICENSE');
    const packagePath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_PackagePath = join(projectDirectory, 'packages', 'lib-a', 'LICENSE');

    const staleContent: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_StaleContent = substitute(template, '2019-2024', 'Old Holder Inc.');

    await mkdir(join(projectDirectory, 'apps', 'web'), {
      recursive: true,
    });

    await mkdir(join(projectDirectory, 'packages', 'lib-a'), {
      recursive: true,
    });

    await writeFile(rootPath, staleContent, 'utf-8');

    await writeFile(appPath, staleContent, 'utf-8');

    await writeFile(packagePath, staleContent, 'utf-8');

    const isProjectRootSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_IsProjectRootSpy = vi.spyOn(utility, 'isProjectRoot').mockResolvedValue(true);

    const loadSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_LoadSpy = vi.spyOn(LibNovaConfig.prototype, 'load').mockResolvedValue({
      project: {
        legalName: 'New Holder LLC',
        startingYear: 2019,
        license: 'MIT',
      },
      recipes: {
        license: {
          'update-copyright': {
            enabled: true,
          },
        },
      },
      workspaces: {
        './': {
          name: 'test-project',
          role: 'project',
          policy: 'freezable',
        },
        './apps/web': {
          name: 'test-app-web',
          role: 'app',
          policy: 'trackable',
        },
        './packages/lib-a': {
          name: 'lib-a',
          role: 'package',
          policy: 'distributable',
        },
      },
    });

    process.chdir(projectDirectory);

    await CliRecipeLicenseUpdateCopyright.run({
      replaceFile: true,
    });

    const expectedContent: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_ExpectedContent = substitute(template, `2019-${new Date().getFullYear()}`, 'New Holder LLC');

    const rootOutput: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_RootOutput = await readFile(rootPath, 'utf-8');
    const appOutput: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_AppOutput = await readFile(appPath, 'utf-8');
    const packageOutput: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_PackageOutput = await readFile(packagePath, 'utf-8');

    // Root and every consumer copy are refreshed independently to the same new content.
    strictEqual(rootOutput, expectedContent);
    strictEqual(appOutput, expectedContent);
    strictEqual(packageOutput, expectedContent);

    isProjectRootSpy.mockRestore();

    loadSpy.mockRestore();

    return;
  });

  it('gates each LICENSE independently in a mixed tree', async () => {
    const projectDirectory: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_ProjectDirectory = await mkdtemp(join(sandboxRoot, 'mixed-'));

    const template: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_Template = await readTemplate('MIT');

    const rootPath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_RootPath = join(projectDirectory, 'LICENSE');
    const editedPath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_EditedPath = join(projectDirectory, 'apps', 'web', 'LICENSE');
    const missingPath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_MissingPath = join(projectDirectory, 'packages', 'lib-a', 'LICENSE');

    // Root: a pristine-nova but stale copy (will be updated).
    const rootStaleContent: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_RootStaleContent = substitute(template, '2019-2024', 'Old Holder Inc.');

    // App consumer: hand-edited (nova body plus an appended clause) so it must be skipped and
    // left byte-identical even while the root is refreshed.
    const editedContent: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_EditedContent = `${substitute(template, '2019-2024', 'Old Holder Inc.')}${[
      '',
      'EXTRA HAND-EDITED CLAUSE.',
      '',
    ].join('\n')}`;

    await mkdir(join(projectDirectory, 'apps', 'web'), {
      recursive: true,
    });

    // The package consumer directory exists but its LICENSE is missing on disk.
    await mkdir(join(projectDirectory, 'packages', 'lib-a'), {
      recursive: true,
    });

    await writeFile(rootPath, rootStaleContent, 'utf-8');

    await writeFile(editedPath, editedContent, 'utf-8');

    const isProjectRootSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_IsProjectRootSpy = vi.spyOn(utility, 'isProjectRoot').mockResolvedValue(true);

    const loadSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_LoadSpy = vi.spyOn(LibNovaConfig.prototype, 'load').mockResolvedValue({
      project: {
        legalName: 'New Holder LLC',
        startingYear: 2019,
        license: 'MIT',
      },
      recipes: {
        license: {
          'update-copyright': {
            enabled: true,
          },
        },
      },
      workspaces: {
        './': {
          name: 'test-project',
          role: 'project',
          policy: 'freezable',
        },
        './apps/web': {
          name: 'test-app-web',
          role: 'app',
          policy: 'trackable',
        },
        './packages/lib-a': {
          name: 'lib-a',
          role: 'package',
          policy: 'distributable',
        },
      },
    });

    process.chdir(projectDirectory);

    await CliRecipeLicenseUpdateCopyright.run({
      replaceFile: true,
    });

    const expectedRootContent: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_ExpectedRootContent = substitute(template, `2019-${new Date().getFullYear()}`, 'New Holder LLC');

    const rootOutput: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_RootOutput = await readFile(rootPath, 'utf-8');
    const editedOutput: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_EditedOutput = await readFile(editedPath, 'utf-8');
    const missingExists: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_MissingExists = await utility.pathExists(missingPath);

    // Root pristine-nova copy is refreshed.
    strictEqual(rootOutput, expectedRootContent);

    // Hand-edited consumer copy is left byte-identical: the appended clause survives.
    strictEqual(editedOutput, editedContent);

    ok(editedOutput.includes('EXTRA HAND-EDITED CLAUSE.'), 'Expected the hand-edited clause preserved');
    ok(editedOutput.includes('Old Holder Inc.'), 'Expected the hand-edited holder left untouched');

    // Missing consumer copy is not created.
    strictEqual(missingExists, false);

    isProjectRootSpy.mockRestore();

    loadSpy.mockRestore();

    return;
  });

  it('with no consumer workspaces behaves as before', async () => {
    const projectDirectory: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_WithNoConsumerWorkspacesBehavesAsBefore_ProjectDirectory = await mkdtemp(join(sandboxRoot, 'no-consumers-'));

    const template: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_WithNoConsumerWorkspacesBehavesAsBefore_Template = await readTemplate('MIT');
    const licensePath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_WithNoConsumerWorkspacesBehavesAsBefore_LicensePath = join(projectDirectory, 'LICENSE');

    await writeFile(licensePath, substitute(template, '2019-2024', 'Old Holder Inc.'), 'utf-8');

    const isProjectRootSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_WithNoConsumerWorkspacesBehavesAsBefore_IsProjectRootSpy = vi.spyOn(utility, 'isProjectRoot').mockResolvedValue(true);

    // Only the root workspace (role 'project') is configured, so there are no consumer copies.
    const loadSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_WithNoConsumerWorkspacesBehavesAsBefore_LoadSpy = vi.spyOn(LibNovaConfig.prototype, 'load').mockResolvedValue({
      project: {
        legalName: 'New Holder LLC',
        startingYear: 2019,
        license: 'MIT',
      },
      recipes: {
        license: {
          'update-copyright': {
            enabled: true,
          },
        },
      },
      workspaces: {
        './': {
          name: 'test-project',
          role: 'project',
          policy: 'freezable',
        },
      },
    });

    process.chdir(projectDirectory);

    await CliRecipeLicenseUpdateCopyright.run({
      replaceFile: true,
    });

    const output: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_WithNoConsumerWorkspacesBehavesAsBefore_Output = await readFile(licensePath, 'utf-8');
    const expectedContent: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_WithNoConsumerWorkspacesBehavesAsBefore_ExpectedContent = substitute(template, `2019-${new Date().getFullYear()}`, 'New Holder LLC');

    strictEqual(output, expectedContent);

    isProjectRootSpy.mockRestore();

    loadSpy.mockRestore();

    return;
  });

  it('dry run writes nothing anywhere in a fan-out tree', async () => {
    const projectDirectory: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_ProjectDirectory = await mkdtemp(join(sandboxRoot, 'fan-out-dry-'));

    const template: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_Template = await readTemplate('MIT');

    const rootPath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_RootPath = join(projectDirectory, 'LICENSE');
    const appPath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_AppPath = join(projectDirectory, 'apps', 'web', 'LICENSE');

    // Both copies are pristine-nova but stale, so they would be rewritten if not for dry run.
    const staleContent: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_StaleContent = substitute(template, '2019-2024', 'Old Holder Inc.');

    await mkdir(join(projectDirectory, 'apps', 'web'), {
      recursive: true,
    });

    await writeFile(rootPath, staleContent, 'utf-8');

    await writeFile(appPath, staleContent, 'utf-8');

    const isProjectRootSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_IsProjectRootSpy = vi.spyOn(utility, 'isProjectRoot').mockResolvedValue(true);

    const loadSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_LoadSpy = vi.spyOn(LibNovaConfig.prototype, 'load').mockResolvedValue({
      project: {
        legalName: 'New Holder LLC',
        startingYear: 2019,
        license: 'MIT',
      },
      recipes: {
        license: {
          'update-copyright': {
            enabled: true,
          },
        },
      },
      workspaces: {
        './': {
          name: 'test-project',
          role: 'project',
          policy: 'freezable',
        },
        './apps/web': {
          name: 'test-app-web',
          role: 'app',
          policy: 'trackable',
        },
      },
    });

    const saveGeneratedFileSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_SaveGeneratedFileSpy = vi.spyOn(utility, 'saveGeneratedFile').mockResolvedValue(undefined);

    process.chdir(projectDirectory);

    await CliRecipeLicenseUpdateCopyright.run({
      dryRun: true,
    });

    // Dry run never writes to any copy.
    strictEqual(saveGeneratedFileSpy['mock']['calls'].length, 0);

    const rootOutput: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_RootOutput = await readFile(rootPath, 'utf-8');
    const appOutput: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_AppOutput = await readFile(appPath, 'utf-8');

    strictEqual(rootOutput, staleContent);
    strictEqual(appOutput, staleContent);

    isProjectRootSpy.mockRestore();

    loadSpy.mockRestore();

    saveGeneratedFileSpy.mockRestore();

    return;
  });

  it('a consumer LICENSE that is a directory is skipped while other copies refresh', async () => {
    const projectDirectory: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_ProjectDirectory = await mkdtemp(join(sandboxRoot, 'dir-license-'));

    const template: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_Template = await readTemplate('MIT');

    const rootPath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_RootPath = join(projectDirectory, 'LICENSE');

    // The broken consumer's LICENSE is a DIRECTORY, so fs.access succeeds but the fingerprint
    // read throws EISDIR. This copy iterates BEFORE the good consumer, so if the failure were not
    // isolated, the good copy would be left stale and the CLI would crash.
    const dirLicensePath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_DirLicensePath = join(projectDirectory, 'apps', 'a-broken', 'LICENSE');
    const goodPath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_GoodPath = join(projectDirectory, 'apps', 'z-good', 'LICENSE');

    const staleContent: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_StaleContent = substitute(template, '2019-2024', 'Old Holder Inc.');

    // Create the directory-as-LICENSE for the broken consumer.
    await mkdir(dirLicensePath, {
      recursive: true,
    });

    await mkdir(join(projectDirectory, 'apps', 'z-good'), {
      recursive: true,
    });

    await writeFile(rootPath, staleContent, 'utf-8');

    await writeFile(goodPath, staleContent, 'utf-8');

    const isProjectRootSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_IsProjectRootSpy = vi.spyOn(utility, 'isProjectRoot').mockResolvedValue(true);

    const loadSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_LoadSpy = vi.spyOn(LibNovaConfig.prototype, 'load').mockResolvedValue({
      project: {
        legalName: 'New Holder LLC',
        startingYear: 2019,
        license: 'MIT',
      },
      recipes: {
        license: {
          'update-copyright': {
            enabled: true,
          },
        },
      },
      workspaces: {
        './': {
          name: 'test-project',
          role: 'project',
          policy: 'freezable',
        },
        './apps/a-broken': {
          name: 'test-app-a-broken',
          role: 'app',
          policy: 'trackable',
        },
        './apps/z-good': {
          name: 'test-app-z-good',
          role: 'app',
          policy: 'trackable',
        },
      },
    });

    const customizedLoggerMock: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_CustomizedLoggerMock = {
      debug: vi.fn(),
      dev: vi.fn(),
      info: vi.fn(),
      warn: vi.fn(),
      error: vi.fn(),
    };
    const loggerCustomizeSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_LoggerCustomizeSpy = vi.spyOn(toolkit['Logger'], 'customize').mockReturnValue(customizedLoggerMock as Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_LoggerCustomizeReturn);

    process.chdir(projectDirectory);

    // The run must NOT throw. A missing per-file guard would let EISDIR propagate out of run().
    let threw: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_Threw = false;

    try {
      await CliRecipeLicenseUpdateCopyright.run({
        replaceFile: true,
      });
    } catch {
      threw = true;
    }

    strictEqual(threw, false);

    const expectedContent: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_ExpectedContent = substitute(template, `2019-${new Date().getFullYear()}`, 'New Holder LLC');

    const rootOutput: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_RootOutput = await readFile(rootPath, 'utf-8');
    const goodOutput: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_GoodOutput = await readFile(goodPath, 'utf-8');

    // Root (iterated first) AND the good consumer (iterated AFTER the broken one) are refreshed.
    strictEqual(rootOutput, expectedContent);
    strictEqual(goodOutput, expectedContent);

    const warnCalls: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_WarnCalls = customizedLoggerMock['warn']['mock']['calls'];

    ok(
      warnCalls.some((call) => (
        typeof call[0] === 'string'
        && call[0].includes('Could not read the LICENSE file') === true
      )),
      'Expected a warn about the unreadable LICENSE copy',
    );

    // The summary still prints even though a copy errored mid-fan-out.
    const infoCalls: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_InfoCalls = customizedLoggerMock['info']['mock']['calls'];

    ok(
      infoCalls.some((call) => (
        typeof call[0] === 'string'
        && call[0].includes('update-copyright summary:') === true
        && call[0].includes('1 errored') === true
      )),
      'Expected the summary to print with one errored copy',
    );

    isProjectRootSpy.mockRestore();

    loadSpy.mockRestore();

    loggerCustomizeSpy.mockRestore();

    return;
  });

  it('a consumer LICENSE read rejection is skipped while other copies refresh', async () => {
    const projectDirectory: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_ProjectDirectory = await mkdtemp(join(sandboxRoot, 'read-reject-'));

    const template: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_Template = await readTemplate('MIT');

    const rootPath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_RootPath = join(projectDirectory, 'LICENSE');
    const unreadablePath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_UnreadablePath = join(projectDirectory, 'apps', 'a-broken', 'LICENSE');
    const goodPath: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_GoodPath = join(projectDirectory, 'apps', 'z-good', 'LICENSE');

    const staleContent: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_StaleContent = substitute(template, '2019-2024', 'Old Holder Inc.');

    await mkdir(join(projectDirectory, 'apps', 'a-broken'), {
      recursive: true,
    });

    await mkdir(join(projectDirectory, 'apps', 'z-good'), {
      recursive: true,
    });

    await writeFile(rootPath, staleContent, 'utf-8');

    // The broken consumer's LICENSE exists on disk but its read is forced to reject (EACCES-like),
    // standing in for a present-but-unreadable file. It iterates BEFORE the good consumer.
    await writeFile(unreadablePath, staleContent, 'utf-8');

    await writeFile(goodPath, staleContent, 'utf-8');

    const isProjectRootSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_IsProjectRootSpy = vi.spyOn(utility, 'isProjectRoot').mockResolvedValue(true);

    const loadSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_LoadSpy = vi.spyOn(LibNovaConfig.prototype, 'load').mockResolvedValue({
      project: {
        legalName: 'New Holder LLC',
        startingYear: 2019,
        license: 'MIT',
      },
      recipes: {
        license: {
          'update-copyright': {
            enabled: true,
          },
        },
      },
      workspaces: {
        './': {
          name: 'test-project',
          role: 'project',
          policy: 'freezable',
        },
        './apps/a-broken': {
          name: 'test-app-a-broken',
          role: 'app',
          policy: 'trackable',
        },
        './apps/z-good': {
          name: 'test-app-z-good',
          role: 'app',
          policy: 'trackable',
        },
      },
    });

    // Force ONLY the broken consumer's read to reject; every other read (root, good consumer, and
    // the test's own assertion reads) delegates to the real readFile.
    const originalReadFile: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_OriginalReadFile = fsPromises['readFile'];
    const brokenSuffix: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_BrokenSuffix = join('apps', 'a-broken', 'LICENSE');
    const readFileSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_ReadFileSpy = vi.spyOn(fsPromises, 'readFile').mockImplementation((path, options) => {
      // Match by suffix, not full equality: the source resolves the path from process.cwd(), which
      // on some platforms is realpath-normalized (for example "/private/var" versus "/var") and
      // would not string-equal the mkdtemp path. Only the broken consumer's read is forced to fail.
      if (typeof path === 'string' && path.endsWith(brokenSuffix) === true) {
        const permissionError: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_PermissionError = new Error(`EACCES: permission denied, open '${unreadablePath}'`);

        Reflect.set(permissionError, 'code', 'EACCES');

        return Promise.reject(permissionError);
      }

      return originalReadFile(path, options);
    });

    const customizedLoggerMock: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_CustomizedLoggerMock = {
      debug: vi.fn(),
      dev: vi.fn(),
      info: vi.fn(),
      warn: vi.fn(),
      error: vi.fn(),
    };
    const loggerCustomizeSpy: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_LoggerCustomizeSpy = vi.spyOn(toolkit['Logger'], 'customize').mockReturnValue(customizedLoggerMock as Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_LoggerCustomizeReturn);

    process.chdir(projectDirectory);

    // The run must NOT throw. A missing per-file guard would let the rejection propagate.
    let threw: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_Threw = false;

    try {
      await CliRecipeLicenseUpdateCopyright.run({
        replaceFile: true,
      });
    } catch {
      threw = true;
    }

    strictEqual(threw, false);

    const expectedContent: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_ExpectedContent = substitute(template, `2019-${new Date().getFullYear()}`, 'New Holder LLC');

    // Restore the read spy BEFORE the assertion reads so they run against the real file system.
    readFileSpy.mockRestore();

    const rootOutput: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_RootOutput = await readFile(rootPath, 'utf-8');
    const goodOutput: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_GoodOutput = await readFile(goodPath, 'utf-8');

    // Root and the good consumer (iterated AFTER the failing one) are still refreshed.
    strictEqual(rootOutput, expectedContent);
    strictEqual(goodOutput, expectedContent);

    const warnCalls: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_WarnCalls = customizedLoggerMock['warn']['mock']['calls'];

    ok(
      warnCalls.some((call) => (
        typeof call[0] === 'string'
        && call[0].includes('Could not read the LICENSE file') === true
      )),
      'Expected a warn about the unreadable LICENSE copy',
    );

    const infoCalls: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_InfoCalls = customizedLoggerMock['info']['mock']['calls'];

    ok(
      infoCalls.some((call) => (
        typeof call[0] === 'string'
        && call[0].includes('update-copyright summary:') === true
        && call[0].includes('1 errored') === true
      )),
      'Expected the summary to print with one errored copy',
    );

    isProjectRootSpy.mockRestore();

    loadSpy.mockRestore();

    loggerCustomizeSpy.mockRestore();

    return;
  });

  return;
});
