import type { Options_PluginOptions } from '../options.d.ts';

/**
 * Tests - Config Drift - ConfigDrift OverridesSchemaParity.
 *
 * @since 0.19.0
 */
export type Tests_ConfigDrift_ConfigDriftOverridesSchemaParity_PublicOverridesTypeMatchesTheJoiOverridesSchema_TypeFilePath = string;

export type Tests_ConfigDrift_ConfigDriftOverridesSchemaParity_PublicOverridesTypeMatchesTheJoiOverridesSchema_PublicLeaves = readonly string[];

export type Tests_ConfigDrift_ConfigDriftOverridesSchemaParity_PublicOverridesTypeMatchesTheJoiOverridesSchema_Description = {
  type?: string;
  keys?: Record<string, Tests_ConfigDrift_ConfigDriftOverridesSchemaParity_PublicOverridesTypeMatchesTheJoiOverridesSchema_Description>;
};

export type Tests_ConfigDrift_ConfigDriftOverridesSchemaParity_PublicOverridesTypeMatchesTheJoiOverridesSchema_JoiSchema_Describe = () => Tests_ConfigDrift_ConfigDriftOverridesSchemaParity_PublicOverridesTypeMatchesTheJoiOverridesSchema_Description;

export type Tests_ConfigDrift_ConfigDriftOverridesSchemaParity_PublicOverridesTypeMatchesTheJoiOverridesSchema_JoiSchema = {
  describe: Tests_ConfigDrift_ConfigDriftOverridesSchemaParity_PublicOverridesTypeMatchesTheJoiOverridesSchema_JoiSchema_Describe;
};

export type Tests_ConfigDrift_ConfigDriftOverridesSchemaParity_PublicOverridesTypeMatchesTheJoiOverridesSchema_SchemaLeaves = readonly string[];

export type Tests_ConfigDrift_ConfigDriftOverridesSchemaParity_PublicOverridesTypeMatchesTheJoiOverridesSchema_PublicSet = Set<string>;

export type Tests_ConfigDrift_ConfigDriftOverridesSchemaParity_PublicOverridesTypeMatchesTheJoiOverridesSchema_SchemaSet = Set<string>;

export type Tests_ConfigDrift_ConfigDriftOverridesSchemaParity_PublicOverridesTypeMatchesTheJoiOverridesSchema_MissingInSchema = string[];

export type Tests_ConfigDrift_ConfigDriftOverridesSchemaParity_PublicOverridesTypeMatchesTheJoiOverridesSchema_StaleInSchema = string[];

export type Tests_ConfigDrift_ConfigDriftOverridesSchemaParity_PublicOverridesTypeMatchesTheJoiOverridesSchema_ParityMessage = string;

/**
 * Tests - Config Drift - ConfigDrift ValidateOptions.
 *
 * @since 0.15.0
 */
export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_Result_Preset = Options_PluginOptions['preset'];

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_Result_Overrides = Options_PluginOptions['overrides'];

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_Result_Plugins = Options_PluginOptions['plugins'];

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_Result_Analytics = Options_PluginOptions['analytics'];

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_Result_ProgressBar = Options_PluginOptions['progressBar'];

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_Result_Search = Options_PluginOptions['search'];

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_Result_IconSafelist = Options_PluginOptions['iconSafelist'];

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_Result_MaxBundleFileSize = Options_PluginOptions['maxBundleFileSize'];

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_Result = {
  preset: Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_Result_Preset;
  overrides: Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_Result_Overrides;
  plugins: Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_Result_Plugins;
  analytics: Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_Result_Analytics;
  progressBar: Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_Result_ProgressBar;
  search: Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_Result_Search;
  iconSafelist: Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_Result_IconSafelist;
  maxBundleFileSize: Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_Result_MaxBundleFileSize;
};

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_JoiSchema_Validate = (value: unknown) => Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_Validated;

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_JoiSchema = {
  validate: Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_JoiSchema_Validate;
};

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_Validated_Value = unknown;

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_Validated = {
  value: Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_Validated_Value;
  error?: Error;
};

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_PresetValue = string;

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_Overrides = Options_PluginOptions['overrides'];

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_OverridesColorsPrimary = Options_PluginOptions['overrides']['colors']['primary'];

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_OverridesColorsSecondary = Options_PluginOptions['overrides']['colors']['secondary'];

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_OverridesFontsDisplay = string | undefined;

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_OverridesFontsBody = string | undefined;

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_OverridesFontsCode = string | undefined;

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_OverridesNavbar = string | undefined;

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_OverridesFooter = string | undefined;

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_Plugins = Options_PluginOptions['plugins'];

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_PluginsDocs = Record<string, unknown> | undefined;

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_PluginsBlog = Record<string, unknown> | false | undefined;

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_PluginsPages = Record<string, unknown> | false | undefined;

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_PluginsSitemap = Record<string, unknown> | false | undefined;

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_Analytics = Options_PluginOptions['analytics'];

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_AnalyticsGtmContainerId = string;

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_ProgressBar = boolean | Record<string, unknown>;

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_Search = Options_PluginOptions['search'];

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_SearchLanguage = string[];

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_SearchIndexDocs = boolean;

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_SearchIndexBlog = boolean;

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_SearchIndexPages = boolean;

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_SearchHashed = boolean;

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_SearchResultLimits = number;

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_SearchHighlight = boolean;

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_SearchShortcut = string;

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_SearchFuzzy = number;

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_SearchIgnore = string[];

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_SearchDocsRoute = string;

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_IconSafelist = Options_PluginOptions['iconSafelist'];

export type Tests_ConfigDrift_ConfigDriftValidateOptions_ValidatesAFullyPopulatedPresetOptionsObject_MaxBundleFileSize = Options_PluginOptions['maxBundleFileSize'];

/**
 * Tests - Config Drift - ConfigDrift ValidateThemeConfig.
 *
 * @since 0.15.0
 */
export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_Result = Record<string, unknown>;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_JoiSchema_Validate = (value: unknown) => Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_Validated;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_JoiSchema = {
  validate: Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_JoiSchema_Validate;
};

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_Validated_Value = unknown;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_Validated = {
  value: Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_Validated_Value;
  error?: Error;
};

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_Site = Record<string, unknown>;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_SiteLogo = Record<string, unknown>;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_SiteLogoAlt = string;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_SiteLogoSrc = Record<string, unknown>;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_SiteLogoSrcLight = string | undefined;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_SiteLogoSrcDark = string | undefined;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_SiteLogoHref = string | undefined;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_SiteLogoWordmark = Record<string, unknown>;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_SiteLogoWordmarkLight = string | undefined;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_SiteLogoWordmarkDark = string | undefined;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_SiteImage = string;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_SiteMetadata = unknown[];

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_ColorMode = Record<string, unknown>;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_ColorModeDefaultMode = string;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_ColorModeDisableSwitch = boolean;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_Navbar = Record<string, unknown>;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_NavbarHideOnScroll = boolean;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_NavbarItems = unknown[];

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_Docs = Record<string, unknown>;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_DocsVersionPersistence = string;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_DocsSidebar = Record<string, unknown>;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_DocsSidebarHideable = boolean;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_DocsSidebarAutoCollapse = boolean;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_Blog = Record<string, unknown>;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_BlogSidebar = Record<string, unknown>;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_BlogSidebarGroupByYear = boolean;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_BlogLayout = Record<string, unknown>;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_BlogLayoutHeading = string;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_BlogLayoutDescription = string;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_BlogShare = Record<string, unknown>;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_BlogSharePlatforms = string[];

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_TableOfContents = Record<string, unknown>;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_TableOfContentsMinHeadingLevel = number;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_TableOfContentsMaxHeadingLevel = number;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_AnnouncementBar = Record<string, unknown>;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_AnnouncementBarId = string;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_AnnouncementBarContent = string;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_AnnouncementBarBackgroundColor = string | undefined;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_AnnouncementBarTextColor = string | undefined;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_AnnouncementBarIsCloseable = boolean;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_ErrorPages = Record<string, unknown>;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_ErrorPagesNotFound = Record<string, unknown>;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_ErrorPagesNotFoundTitle = string;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_ErrorPagesNotFoundDescription = string;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_ErrorPagesNotFoundBackHomeLabel = string;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_ErrorPagesNotFoundBackHomeHref = string;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_ErrorPagesErrorPageContent = Record<string, unknown>;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_ErrorPagesErrorPageContentTitle = string;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_ErrorPagesErrorPageContentRetryLabel = string;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_ErrorPagesError = Record<string, unknown>;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_ErrorPagesErrorRetryLabel = string;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_Footer = Record<string, unknown>;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_FooterCta = string | Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_FooterCtaObject | undefined;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_FooterCtaObject_Label = string;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_FooterCtaObject_Href = string;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_FooterCtaObject = {
  label: Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_FooterCtaObject_Label;
  href: Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_FooterCtaObject_Href;
};

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_FooterCtaLabel = string;

export type Tests_ConfigDrift_ConfigDriftValidateThemeConfig_ValidatesAFullyPopulatedThemeConfigObject_FooterCtaHref = string;

/**
 * Tests - Config Drift - Derive Public Override Leaf Paths.
 *
 * @since 0.19.0
 */
export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_TypeFilePath = string;

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_Returns = Promise<readonly string[]>;

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_FileText = string;

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_ObjectTypes = Map<string, Map<string, string>>;

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_PartialAliases = Map<string, string>;

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_BlockPattern = RegExp;

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_BlockMatch = RegExpExecArray | null;

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_TypeName = string;

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_BlockBody = string;

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_Fields = Map<string, string>;

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_FieldPattern = RegExp;

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_FieldMatch = RegExpExecArray | null;

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_FieldName = string;

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_FieldExpression = string;

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_FieldTypeMatch = RegExpMatchArray | null;

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_FieldType = string;

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_PartialPattern = RegExp;

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_PartialMatch = RegExpExecArray | null;

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_Leaves = string[];

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_WalkEntry_TypeName = string;

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_WalkEntry_Path = string[];

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_WalkEntry = {
  typeName: Tests_ConfigDrift_DerivePublicOverrideLeafPaths_WalkEntry_TypeName;
  path: Tests_ConfigDrift_DerivePublicOverrideLeafPaths_WalkEntry_Path;
};

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_WalkStack = Tests_ConfigDrift_DerivePublicOverrideLeafPaths_WalkEntry[];

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_Entry = Tests_ConfigDrift_DerivePublicOverrideLeafPaths_WalkEntry;

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_ResolvedType = string;

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_EntryFields = Tests_ConfigDrift_DerivePublicOverrideLeafPaths_Fields | undefined;

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_WalkFieldEntry = readonly [string, string];

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_WalkFieldName = string;

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_FieldTypeReference = string;

export type Tests_ConfigDrift_DerivePublicOverrideLeafPaths_WalkFieldType = string;

/**
 * Tests - Config Drift - Derive Schema Override Leaf Paths.
 *
 * @since 0.19.0
 */
export type Tests_ConfigDrift_DeriveSchemaOverrideLeafPaths_RootNode = {
  type?: string;
  keys?: Record<string, Tests_ConfigDrift_DeriveSchemaOverrideLeafPaths_RootNode>;
};

export type Tests_ConfigDrift_DeriveSchemaOverrideLeafPaths_Returns = readonly string[];

export type Tests_ConfigDrift_DeriveSchemaOverrideLeafPaths_OverridesNode = Tests_ConfigDrift_DeriveSchemaOverrideLeafPaths_RootNode | undefined;

export type Tests_ConfigDrift_DeriveSchemaOverrideLeafPaths_Leaves = string[];

export type Tests_ConfigDrift_DeriveSchemaOverrideLeafPaths_WalkEntry_Node = Tests_ConfigDrift_DeriveSchemaOverrideLeafPaths_RootNode;

export type Tests_ConfigDrift_DeriveSchemaOverrideLeafPaths_WalkEntry_Path = string[];

export type Tests_ConfigDrift_DeriveSchemaOverrideLeafPaths_WalkEntry = {
  node: Tests_ConfigDrift_DeriveSchemaOverrideLeafPaths_WalkEntry_Node;
  path: Tests_ConfigDrift_DeriveSchemaOverrideLeafPaths_WalkEntry_Path;
};

export type Tests_ConfigDrift_DeriveSchemaOverrideLeafPaths_WalkStack = Tests_ConfigDrift_DeriveSchemaOverrideLeafPaths_WalkEntry[];

export type Tests_ConfigDrift_DeriveSchemaOverrideLeafPaths_Entry = Tests_ConfigDrift_DeriveSchemaOverrideLeafPaths_WalkEntry;

export type Tests_ConfigDrift_DeriveSchemaOverrideLeafPaths_EntryKeys = Record<string, Tests_ConfigDrift_DeriveSchemaOverrideLeafPaths_RootNode> | undefined;

export type Tests_ConfigDrift_DeriveSchemaOverrideLeafPaths_ChildNode = Tests_ConfigDrift_DeriveSchemaOverrideLeafPaths_RootNode;

/**
 * Tests - Config Drift - Get Package Root.
 *
 * @since 0.19.0
 */
export type Tests_ConfigDrift_GetPackageRoot_Returns = string;

export type Tests_ConfigDrift_GetPackageRoot_CurrentFilePath = string;

export type Tests_ConfigDrift_GetPackageRoot_CurrentFileDirectory = string;
