/**
 * Tests - Documentation Dependencies - Documentation Dependencies.
 *
 * @since 0.26.0
 */
export type Tests_DocumentationDependencies_DocumentationDependencies_DocumentsEveryRuntimeAndPeerDependency_CurrentFileDirectory = string;

export type Tests_DocumentationDependencies_DocumentationDependencies_DocumentsEveryRuntimeAndPeerDependency_PackageDirectory = string;

export type Tests_DocumentationDependencies_DocumentationDependencies_DocumentsEveryRuntimeAndPeerDependency_ManifestPath = string;

export type Tests_DocumentationDependencies_DocumentationDependencies_DocumentsEveryRuntimeAndPeerDependency_LedgerPath = string;

export type Tests_DocumentationDependencies_DocumentationDependencies_DocumentsEveryRuntimeAndPeerDependency_ManifestRaw = string;

export type Tests_DocumentationDependencies_DocumentationDependencies_DocumentsEveryRuntimeAndPeerDependency_ManifestDependencies = Record<string, string>;

export type Tests_DocumentationDependencies_DocumentationDependencies_DocumentsEveryRuntimeAndPeerDependency_ManifestPeerDependencies = Record<string, string>;

export type Tests_DocumentationDependencies_DocumentationDependencies_DocumentsEveryRuntimeAndPeerDependency_Manifest = {
  dependencies: Tests_DocumentationDependencies_DocumentationDependencies_DocumentsEveryRuntimeAndPeerDependency_ManifestDependencies;
  peerDependencies: Tests_DocumentationDependencies_DocumentationDependencies_DocumentsEveryRuntimeAndPeerDependency_ManifestPeerDependencies;
};

export type Tests_DocumentationDependencies_DocumentationDependencies_DocumentsEveryRuntimeAndPeerDependency_Ledger = string;

export type Tests_DocumentationDependencies_DocumentationDependencies_DocumentsEveryRuntimeAndPeerDependency_DependencyNames = string[];
