import type {
  Shared_BlueprintConfigWorkflow,
  Shared_BlueprintWorkflow,
  Shared_NovaConfig_Workspaces,
  Shared_NovaConfigEnvironment,
} from '../../../../shared.d.ts';

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Publish Parity - Action.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityAction_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityAction_Entry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityAction_ReproducesTheSyntheticActionWorkflowByteForByte_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityAction_ReproducesTheSyntheticActionWorkflowByteForByte_Generated = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityAction_ReproducesTheSyntheticActionWorkflowByteForByte_FixturesDir = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityAction_ReproducesTheSyntheticActionWorkflowByteForByte_FixturePath = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityAction_ReproducesTheSyntheticActionWorkflowByteForByte_Committed = string;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Publish Parity - Cloudflare Workers Secret Sync.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityCloudflareWorkersSecretSync_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityCloudflareWorkersSecretSync_Environment = Shared_NovaConfigEnvironment;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityCloudflareWorkersSecretSync_Entry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityCloudflareWorkersSecretSync_EmitsNoSyncStepWhenTheScopeWorkspaceHasNoPrivateSecrets_NoSecretsWorkspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityCloudflareWorkersSecretSync_EmitsNoSyncStepWhenTheScopeWorkspaceHasNoPrivateSecrets_NoSecretsEntry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityCloudflareWorkersSecretSync_EmitsNoSyncStepWhenTheScopeWorkspaceHasNoPrivateSecrets_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityCloudflareWorkersSecretSync_EmitsNoSyncStepWhenTheScopeWorkspaceHasNoPrivateSecrets_Generated = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityCloudflareWorkersSecretSync_ReproducesTheSyntheticCloudflareWorkersSecretSyncWorkflowByteForByte_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityCloudflareWorkersSecretSync_ReproducesTheSyntheticCloudflareWorkersSecretSyncWorkflowByteForByte_Generated = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityCloudflareWorkersSecretSync_ReproducesTheSyntheticCloudflareWorkersSecretSyncWorkflowByteForByte_FixturesDir = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityCloudflareWorkersSecretSync_ReproducesTheSyntheticCloudflareWorkersSecretSyncWorkflowByteForByte_FixturePath = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityCloudflareWorkersSecretSync_ReproducesTheSyntheticCloudflareWorkersSecretSyncWorkflowByteForByte_Committed = string;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Publish Parity - Containers.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityContainers_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityContainers_Entry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityContainers_ReproducesTheSyntheticContainersWorkflowByteForByte_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityContainers_ReproducesTheSyntheticContainersWorkflowByteForByte_Generated = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityContainers_ReproducesTheSyntheticContainersWorkflowByteForByte_FixturesDir = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityContainers_ReproducesTheSyntheticContainersWorkflowByteForByte_FixturePath = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityContainers_ReproducesTheSyntheticContainersWorkflowByteForByte_Committed = string;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Publish Parity - Invariant.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityInvariant_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityInvariant_Environment = Shared_NovaConfigEnvironment;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityInvariant_Entry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityInvariant_DerivesCredNamesThatMatchTheProvisionManagedSet_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityInvariant_DerivesCredNamesThatMatchTheProvisionManagedSet_Generated = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityInvariant_DerivesCredNamesThatMatchTheProvisionManagedSet_ManagedNames = string[];

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Publish Parity - No Turbo.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityNoTurbo_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityNoTurbo_Entry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityNoTurbo_ReproducesTheSyntheticNoTurboWorkflowByteForByte_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityNoTurbo_ReproducesTheSyntheticNoTurboWorkflowByteForByte_Generated = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityNoTurbo_ReproducesTheSyntheticNoTurboWorkflowByteForByte_FixturesDir = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityNoTurbo_ReproducesTheSyntheticNoTurboWorkflowByteForByte_FixturePath = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityNoTurbo_ReproducesTheSyntheticNoTurboWorkflowByteForByte_Committed = string;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Publish Parity - Pages.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityPages_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityPages_Entry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityPages_ReproducesTheSyntheticPagesWorkflowByteForByte_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityPages_ReproducesTheSyntheticPagesWorkflowByteForByte_Generated = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityPages_ReproducesTheSyntheticPagesWorkflowByteForByte_FixturesDir = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityPages_ReproducesTheSyntheticPagesWorkflowByteForByte_FixturePath = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityPages_ReproducesTheSyntheticPagesWorkflowByteForByte_Committed = string;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Publish Parity - Project.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityProject_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityProject_Entry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityProject_ReproducesTheCommittedProjectWorkflowByteForByte_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityProject_ReproducesTheCommittedProjectWorkflowByteForByte_Generated = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityProject_ReproducesTheCommittedProjectWorkflowByteForByte_FixturesDir = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityProject_ReproducesTheCommittedProjectWorkflowByteForByte_FixturePath = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityProject_ReproducesTheCommittedProjectWorkflowByteForByte_Committed = string;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Publish Parity - Runtime Sync Fan Out.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityRuntimeSyncFanOut_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityRuntimeSyncFanOut_Environment = Shared_NovaConfigEnvironment;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityRuntimeSyncFanOut_Entry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityRuntimeSyncFanOut_EmitsASyncStepOnBothTheCloudflareAndVercelJobs_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityRuntimeSyncFanOut_EmitsASyncStepOnBothTheCloudflareAndVercelJobs_Generated = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityRuntimeSyncFanOut_SyncsTheSameRuntimeSecretsToEveryServerBearingTargetByteForByte_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityRuntimeSyncFanOut_SyncsTheSameRuntimeSecretsToEveryServerBearingTargetByteForByte_Generated = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityRuntimeSyncFanOut_SyncsTheSameRuntimeSecretsToEveryServerBearingTargetByteForByte_FixturesDir = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityRuntimeSyncFanOut_SyncsTheSameRuntimeSecretsToEveryServerBearingTargetByteForByte_FixturePath = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityRuntimeSyncFanOut_SyncsTheSameRuntimeSecretsToEveryServerBearingTargetByteForByte_Committed = string;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Publish Parity - Sites.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParitySites_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParitySites_Environment = Shared_NovaConfigEnvironment;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParitySites_Entry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParitySites_ReproducesTheCommittedSitesWorkflowByteForByte_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParitySites_ReproducesTheCommittedSitesWorkflowByteForByte_Generated = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParitySites_ReproducesTheCommittedSitesWorkflowByteForByte_FixturesDir = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParitySites_ReproducesTheCommittedSitesWorkflowByteForByte_FixturePath = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParitySites_ReproducesTheCommittedSitesWorkflowByteForByte_Committed = string;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Publish Parity - Vercel.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityVercel_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityVercel_Entry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityVercel_ReproducesTheSyntheticVercelWorkflowByteForByte_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityVercel_ReproducesTheSyntheticVercelWorkflowByteForByte_Generated = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityVercel_ReproducesTheSyntheticVercelWorkflowByteForByte_FixturesDir = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityVercel_ReproducesTheSyntheticVercelWorkflowByteForByte_FixturePath = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityVercel_ReproducesTheSyntheticVercelWorkflowByteForByte_Committed = string;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Publish Parity - Vercel Scope.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityVercelScope_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityVercelScope_Environment = Shared_NovaConfigEnvironment;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityVercelScope_Entry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityVercelScope_ReproducesTheSyntheticVercelScopeWorkflowByteForByte_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityVercelScope_ReproducesTheSyntheticVercelScopeWorkflowByteForByte_Generated = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityVercelScope_ReproducesTheSyntheticVercelScopeWorkflowByteForByte_FixturesDir = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityVercelScope_ReproducesTheSyntheticVercelScopeWorkflowByteForByte_FixturePath = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityVercelScope_ReproducesTheSyntheticVercelScopeWorkflowByteForByte_Committed = string;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Publish Parity - Vercel Secret Sync.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityVercelSecretSync_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityVercelSecretSync_Environment = Shared_NovaConfigEnvironment;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityVercelSecretSync_Entry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityVercelSecretSync_EmitsNoSyncStepWhenTheScopeWorkspaceHasNoPrivateSecrets_NoSecretsWorkspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityVercelSecretSync_EmitsNoSyncStepWhenTheScopeWorkspaceHasNoPrivateSecrets_NoSecretsEntry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityVercelSecretSync_EmitsNoSyncStepWhenTheScopeWorkspaceHasNoPrivateSecrets_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityVercelSecretSync_EmitsNoSyncStepWhenTheScopeWorkspaceHasNoPrivateSecrets_Generated = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityVercelSecretSync_ReproducesTheSyntheticVercelSecretSyncWorkflowByteForByte_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityVercelSecretSync_ReproducesTheSyntheticVercelSecretSyncWorkflowByteForByte_Generated = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityVercelSecretSync_ReproducesTheSyntheticVercelSecretSyncWorkflowByteForByte_FixturesDir = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityVercelSecretSync_ReproducesTheSyntheticVercelSecretSyncWorkflowByteForByte_FixturePath = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityVercelSecretSync_ReproducesTheSyntheticVercelSecretSyncWorkflowByteForByte_Committed = string;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Publish Parity - Workflow Run.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityWorkflowRun_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityWorkflowRun_CoreEntry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityWorkflowRun_AddonEntry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityWorkflowRun_Siblings = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityWorkflowRun_ReproducesTheSyntheticChainedSuccessWorkflowByteForByte_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityWorkflowRun_ReproducesTheSyntheticChainedSuccessWorkflowByteForByte_Generated = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityWorkflowRun_ReproducesTheSyntheticChainedSuccessWorkflowByteForByte_FixturesDir = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityWorkflowRun_ReproducesTheSyntheticChainedSuccessWorkflowByteForByte_FixturePath = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityWorkflowRun_ReproducesTheSyntheticChainedSuccessWorkflowByteForByte_Committed = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityWorkflowRun_ReproducesTheSyntheticUpstreamCoreWorkflowByteForByte_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityWorkflowRun_ReproducesTheSyntheticUpstreamCoreWorkflowByteForByte_Generated = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityWorkflowRun_ReproducesTheSyntheticUpstreamCoreWorkflowByteForByte_FixturesDir = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityWorkflowRun_ReproducesTheSyntheticUpstreamCoreWorkflowByteForByte_FixturePath = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintPublishParity_WorkflowsBlueprintPublishParityWorkflowRun_ReproducesTheSyntheticUpstreamCoreWorkflowByteForByte_Committed = string;
