import type {
  Cli_Generate_Github_WorkflowsBlueprint_Runner_AppBuildValues_AppPath,
  Cli_Generate_Github_WorkflowsBlueprint_Runner_AppBuildValues_Environment,
  Cli_Generate_Github_WorkflowsBlueprint_Runner_AppBuildValues_Returns,
  Cli_Generate_Github_WorkflowsBlueprint_Runner_AppRuntimeValues_AppPath,
  Cli_Generate_Github_WorkflowsBlueprint_Runner_AppRuntimeValues_Environment,
  Cli_Generate_Github_WorkflowsBlueprint_Runner_AppRuntimeValues_Returns,
  Cli_Generate_Github_WorkflowsBlueprint_Runner_EmitRuntimeSyncStep_Options,
  Cli_Generate_Github_WorkflowsBlueprint_Runner_EmitRuntimeSyncStep_Returns,
  Cli_Generate_Github_WorkflowsBlueprint_Runner_WriteEnvRun_Returns,
  Cli_Generate_Github_WorkflowsBlueprint_Runner_WriteEnvRun_Variables,
} from '../../../../cli/generate/github/workflows-blueprint.d.ts';
import type {
  Shared_BlueprintConfigWorkflow,
  Shared_BlueprintDeliveryValues,
  Shared_BlueprintEnvMap,
  Shared_BlueprintEnvMapEntry,
  Shared_BlueprintJob,
  Shared_BlueprintStep,
  Shared_BlueprintTriggerIssues,
  Shared_BlueprintTriggerPush,
  Shared_BlueprintTriggerSchedule,
  Shared_BlueprintTriggerWorkflowRun,
  Shared_BlueprintWithMapEntry,
  Shared_BlueprintWorkflow,
  Shared_NovaConfig_Workspaces,
  Shared_NovaConfigEnvironment,
} from '../../../../shared.d.ts';

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint - App Build Values.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintAppBuildValues_BuildValues = (environment: Cli_Generate_Github_WorkflowsBlueprint_Runner_AppBuildValues_Environment, appPath: Cli_Generate_Github_WorkflowsBlueprint_Runner_AppBuildValues_AppPath) => Cli_Generate_Github_WorkflowsBlueprint_Runner_AppBuildValues_Returns;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintAppBuildValues_RuntimeValues = (environment: Cli_Generate_Github_WorkflowsBlueprint_Runner_AppRuntimeValues_Environment, appPath: Cli_Generate_Github_WorkflowsBlueprint_Runner_AppRuntimeValues_AppPath) => Cli_Generate_Github_WorkflowsBlueprint_Runner_AppRuntimeValues_Returns;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintAppBuildValues_CarriesANonSecretBuildDefaultAndBakesItAsAShellFallback_WriteEnvRun = (variables: Cli_Generate_Github_WorkflowsBlueprint_Runner_WriteEnvRun_Variables) => Cli_Generate_Github_WorkflowsBlueprint_Runner_WriteEnvRun_Returns;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintAppBuildValues_CarriesANonSecretBuildDefaultAndBakesItAsAShellFallback_Environment = Shared_NovaConfigEnvironment;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintAppBuildValues_CarriesANonSecretBuildDefaultAndBakesItAsAShellFallback_Values = Shared_BlueprintDeliveryValues;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintAppBuildValues_CarriesANonSecretBuildDefaultAndBakesItAsAShellFallback_Run = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintAppBuildValues_SplitsAppValuesByBuildOnlyAndDerivesPrefixedNames_Environment = Shared_NovaConfigEnvironment;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildCheckSponsorGatedIssues_Entry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildCheckSponsorGatedIssues_EmitsTheCheckIssuesJobWithReadWritePermissions_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildCheckSponsorGatedIssues_MergesBothTriggersInConfigOrder_Ir = Shared_BlueprintWorkflow;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildIssueCommentTrigger_ReturnsTheIssueCommentTrigger_Result = Shared_BlueprintTriggerIssues;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildIssuesTrigger_ReturnsTheIssuesTrigger_Result = Shared_BlueprintTriggerIssues;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildLockInactiveIssues_Entry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildLockInactiveIssues_AppendsTheWorkflowDispatchInput_Ir = Shared_BlueprintWorkflow;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint - Build Publish.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_Entry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_Environment = Shared_NovaConfigEnvironment;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_DefaultsEntry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_TagPushEntry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_ReleasePushEntry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_ReleasePushEntryForBuild = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_TagBranchPushEntry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_TagBranchPushEntryForBuild = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_AddsNoStepForADotenvLessScope_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_AddsNoStepForADotenvLessScope_BuildJob = Shared_BlueprintJob | undefined;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_AddsNoStepForADotenvLessScope_PlainStep = Shared_BlueprintStep | undefined;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_AddsNoStepForADotenvLessScope_Result = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_AppliesNoJobsConditionForTheAnyVariant_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_BakesABuildOnlyDefaultAsAnEscapedShellFallback_DefaultEnvironment = Shared_NovaConfigEnvironment;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_BakesABuildOnlyDefaultAsAnEscapedShellFallback_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_BakesABuildOnlyDefaultAsAnEscapedShellFallback_BuildJob = Shared_BlueprintJob | undefined;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_BakesABuildOnlyDefaultAsAnEscapedShellFallback_WriteEnvStep = Shared_BlueprintStep | undefined;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_BakesABuildOnlyDefaultAsAnEscapedShellFallback_StepEnv = Shared_BlueprintEnvMap;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_BakesABuildOnlyDefaultAsAnEscapedShellFallback_RegionEntry = Shared_BlueprintEnvMapEntry | undefined;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_BakesABuildOnlyDefaultAsAnEscapedShellFallback_Result = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_BakesABuildOnlyDefaultAsAnEscapedShellFallback_DollarBrace = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_BakesABuildOnlyDefaultAsAnEscapedShellFallback_ExpectedFallback = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_BakesOnlyPublicVariablesIntoTheScopeEnvFile_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_BakesOnlyPublicVariablesIntoTheScopeEnvFile_BuildJob = Shared_BlueprintJob | undefined;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_BakesOnlyPublicVariablesIntoTheScopeEnvFile_WriteEnvStep = Shared_BlueprintStep | undefined;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_BakesOnlyPublicVariablesIntoTheScopeEnvFile_StepEnv = Shared_BlueprintEnvMap;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_BakesOnlyPublicVariablesIntoTheScopeEnvFile_SiteKeyEntry = Shared_BlueprintEnvMapEntry | undefined;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_BakesOnlyPublicVariablesIntoTheScopeEnvFile_GtmEntry = Shared_BlueprintEnvMapEntry | undefined;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_BakesOnlyPublicVariablesIntoTheScopeEnvFile_Result = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_GatesEveryJobOnTheFailureConclusionForTheFailureVariant_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_GatesEveryJobOnTheFailureConclusionForTheFailureVariant_BuildJob = Shared_BlueprintJob | undefined;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_GatesEveryJobOnTheSuccessConclusion_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_GatesEveryJobOnTheSuccessConclusion_DollarBrace = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_GatesEveryJobOnTheSuccessConclusion_Expected = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_GatesEveryJobOnTheSuccessConclusion_Result = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_GatesEveryJobOnTheSuccessConclusion_IfLine = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_GatesEveryJobOnTheSuccessConclusion_IfLines = Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_GatesEveryJobOnTheSuccessConclusion_IfLine[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_KeepsTheCurrentJobLevelDefaults_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_KeepsTheCurrentJobLevelDefaults_BuildJob = Shared_BlueprintJob | undefined;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_KeepsTheCurrentJobLevelDefaults_DeployJob = Shared_BlueprintJob | undefined;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_KeepsTheCurrentJobLevelDefaults_SetupStep = Shared_BlueprintStep | undefined;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_KeepsTheCurrentJobLevelDefaults_NodeVersionEntry = Shared_BlueprintWithMapEntry | undefined;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_KeepsTheCurrentJobLevelDefaults_CacheEntry = Shared_BlueprintWithMapEntry | undefined;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_KeepsTheCurrentJobLevelDefaults_DollarBrace = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_MergesReleaseAndPushTriggersInConfigOrder_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_MergesReleaseAndPushTriggersInConfigOrder_DollarBrace = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_MergesReleaseAndPushTriggersInConfigOrder_PublishEntry = Shared_BlueprintEnvMapEntry | undefined;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_MergesReleaseAndWorkflowRunPartsInConfigOrder_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_MergesReleaseAndWorkflowRunPartsInConfigOrder_DollarBrace = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_MergesReleaseAndWorkflowRunPartsInConfigOrder_PublishEntry = Shared_BlueprintEnvMapEntry | undefined;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_MergesTagPushAndBranchPushIntoASinglePushNode_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_MergesTagPushAndBranchPushIntoASinglePushNode_PushNode = Shared_BlueprintTriggerPush | undefined;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_MergesTagPushAndBranchPushIntoASinglePushNode_Result = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_MergesTagPushAndBranchPushIntoASinglePushNode_PushKeyLine = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_MergesTagPushAndBranchPushIntoASinglePushNode_PushKeyLines = Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_MergesTagPushAndBranchPushIntoASinglePushNode_PushKeyLine[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_MergesTheReleaseOnlyPublishConditionAndRunName_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_MergesTheReleaseOnlyPublishConditionAndRunName_DollarBrace = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_MergesTheReleaseOnlyPublishConditionAndRunName_PublishEntry = Shared_BlueprintEnvMapEntry | undefined;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_MergesTheTagPushOnlyPublishConditionAndRunName_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_MergesTheTagPushOnlyPublishConditionAndRunName_DollarBrace = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_MergesTheTagPushOnlyPublishConditionAndRunName_PublishEntry = Shared_BlueprintEnvMapEntry | undefined;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_WorkflowRunSiblings = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_WorkflowRunEntry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_WorkflowRunFailureEntry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_WorkflowRunAnyEntry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_ReleaseWorkflowRunEntry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_MergesTheWorkflowRunPublishConditionAndRunName_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_MergesTheWorkflowRunPublishConditionAndRunName_WorkflowRunNode = Shared_BlueprintTriggerWorkflowRun | undefined;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_MergesTheWorkflowRunPublishConditionAndRunName_DollarBrace = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPublish_MergesTheWorkflowRunPublishConditionAndRunName_PublishEntry = Shared_BlueprintEnvMapEntry | undefined;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPushTrigger_CarriesTheOptionalPathsFilter_Result = Shared_BlueprintTriggerPush;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildPushTrigger_ReturnsTheBranchPushTrigger_Result = Shared_BlueprintTriggerPush;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildScheduleDailyTrigger_ReturnsTheDailyScheduleTrigger_Result = Shared_BlueprintTriggerSchedule;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildScheduleMonthlyTrigger_ReturnsTheMonthlyScheduleTrigger_Result = Shared_BlueprintTriggerSchedule;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildScheduleWeeklyTrigger_ReturnsTheWeeklyScheduleTrigger_Result = Shared_BlueprintTriggerSchedule;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildTagPushTrigger_AppliesCustomTagGlobs_Result = Shared_BlueprintTriggerPush;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildTagPushTrigger_ReturnsTheTagPushTriggerWithTheDefaultGlob_Result = Shared_BlueprintTriggerPush;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintBuildWorkflowRunTrigger_ReturnsTheWorkflowRunTriggerWithTheResolvedNames_Result = Shared_BlueprintTriggerWorkflowRun;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint - Emit Runtime Sync Step.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintEmitRuntimeSyncStep_Emit = (options: Cli_Generate_Github_WorkflowsBlueprint_Runner_EmitRuntimeSyncStep_Options) => Cli_Generate_Github_WorkflowsBlueprint_Runner_EmitRuntimeSyncStep_Returns;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintEmitRuntimeSyncStep_ReturnsUndefinedWhenTheTargetDeclaresNoRuntimeValues_Step = Shared_BlueprintStep | undefined;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintEmitRuntimeSyncStep_RoutesACloudflareSecretThroughTheEncryptedChannelAndAVariableThroughTheDeployChannel_Step = Shared_BlueprintStep | undefined;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintEmitRuntimeSyncStep_RoutesAVercelSecretThroughTheSensitiveChannelAndAVariableThroughThePlainChannel_Step = Shared_BlueprintStep | undefined;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintSerialize_Entry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintSerialize_EmitsPushBranchesBeforePaths_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintSerialize_EmitsPushBranchesBeforePaths_PushTrigger = Shared_BlueprintTriggerPush;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintSerialize_EmitsPushBranchesBeforePaths_Result = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintSerialize_EmitsPushBranchesBeforePaths_ExpectedLine = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintSerialize_EmitsPushBranchesBeforePaths_ExpectedLines = Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintSerialize_EmitsPushBranchesBeforePaths_ExpectedLine[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintSerialize_EmitsPushBranchesBeforePaths_Expected = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintSerialize_EmitsTheFiveLineHeaderFollowedByABlankLine_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintSerialize_EmitsTheFiveLineHeaderFollowedByABlankLine_Result = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintSerialize_EmitsTheFiveLineHeaderFollowedByABlankLine_ExpectedPrefixLine = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintSerialize_EmitsTheFiveLineHeaderFollowedByABlankLine_ExpectedPrefixLines = Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintSerialize_EmitsTheFiveLineHeaderFollowedByABlankLine_ExpectedPrefixLine[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintSerialize_EmitsTheFiveLineHeaderFollowedByABlankLine_ExpectedPrefix = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintSerialize_EmitsThePushTagsOnBlock_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintSerialize_EmitsThePushTagsOnBlock_PushTrigger = Shared_BlueprintTriggerPush;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintSerialize_EmitsThePushTagsOnBlock_Result = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintSerialize_EmitsThePushTagsOnBlock_ExpectedLine = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintSerialize_EmitsThePushTagsOnBlock_ExpectedLines = Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintSerialize_EmitsThePushTagsOnBlock_ExpectedLine[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintSerialize_EmitsThePushTagsOnBlock_Expected = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintSerialize_LeavesBooleansAndIntegersBareWhileQuotingStrings_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprint_WorkflowsBlueprintSerialize_LeavesBooleansAndIntegersBareWhileQuotingStrings_Result = string;
