import type {
  Shared_BlueprintConfigWorkflow,
  Shared_BlueprintWorkflow,
  Shared_NovaConfigEnvironment,
} from '../../../../shared.d.ts';

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Parity - Check Sponsor Gated Issues.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintParity_WorkflowsBlueprintParityCheckSponsorGatedIssues_Entry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintParity_WorkflowsBlueprintParityCheckSponsorGatedIssues_Environment = Shared_NovaConfigEnvironment;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintParity_WorkflowsBlueprintParityCheckSponsorGatedIssues_ReproducesTheSponsorCheckWorkflowWithPrefixedKeysByteForByte_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintParity_WorkflowsBlueprintParityCheckSponsorGatedIssues_ReproducesTheSponsorCheckWorkflowWithPrefixedKeysByteForByte_Generated = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintParity_WorkflowsBlueprintParityCheckSponsorGatedIssues_ReproducesTheSponsorCheckWorkflowWithPrefixedKeysByteForByte_FixturesDir = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintParity_WorkflowsBlueprintParityCheckSponsorGatedIssues_ReproducesTheSponsorCheckWorkflowWithPrefixedKeysByteForByte_FixturePath = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintParity_WorkflowsBlueprintParityCheckSponsorGatedIssues_ReproducesTheSponsorCheckWorkflowWithPrefixedKeysByteForByte_Committed = string;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Parity - Lock Inactive Issues.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintParity_WorkflowsBlueprintParityLockInactiveIssues_Entry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintParity_WorkflowsBlueprintParityLockInactiveIssues_ReproducesTheCommittedProjectWorkflowByteForByte_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintParity_WorkflowsBlueprintParityLockInactiveIssues_ReproducesTheCommittedProjectWorkflowByteForByte_Generated = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintParity_WorkflowsBlueprintParityLockInactiveIssues_ReproducesTheCommittedProjectWorkflowByteForByte_FixturesDir = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintParity_WorkflowsBlueprintParityLockInactiveIssues_ReproducesTheCommittedProjectWorkflowByteForByte_FixturePath = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintParity_WorkflowsBlueprintParityLockInactiveIssues_ReproducesTheCommittedProjectWorkflowByteForByte_Committed = string;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Parity - Lock Schedule Daily.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintParity_WorkflowsBlueprintParityLockScheduleDaily_Entry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintParity_WorkflowsBlueprintParityLockScheduleDaily_ReproducesTheSyntheticDailyWorkflowByteForByte_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintParity_WorkflowsBlueprintParityLockScheduleDaily_ReproducesTheSyntheticDailyWorkflowByteForByte_Generated = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintParity_WorkflowsBlueprintParityLockScheduleDaily_ReproducesTheSyntheticDailyWorkflowByteForByte_FixturesDir = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintParity_WorkflowsBlueprintParityLockScheduleDaily_ReproducesTheSyntheticDailyWorkflowByteForByte_FixturePath = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintParity_WorkflowsBlueprintParityLockScheduleDaily_ReproducesTheSyntheticDailyWorkflowByteForByte_Committed = string;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Parity - Lock Schedule Monthly.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintParity_WorkflowsBlueprintParityLockScheduleMonthly_Entry = Shared_BlueprintConfigWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintParity_WorkflowsBlueprintParityLockScheduleMonthly_ReproducesTheSyntheticMonthlyWorkflowByteForByte_Ir = Shared_BlueprintWorkflow;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintParity_WorkflowsBlueprintParityLockScheduleMonthly_ReproducesTheSyntheticMonthlyWorkflowByteForByte_Generated = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintParity_WorkflowsBlueprintParityLockScheduleMonthly_ReproducesTheSyntheticMonthlyWorkflowByteForByte_FixturesDir = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintParity_WorkflowsBlueprintParityLockScheduleMonthly_ReproducesTheSyntheticMonthlyWorkflowByteForByte_FixturePath = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintParity_WorkflowsBlueprintParityLockScheduleMonthly_ReproducesTheSyntheticMonthlyWorkflowByteForByte_Committed = string;
