import type {
  Shared_BlueprintConfigWorkflow,
  Shared_BlueprintValidationResult,
  Shared_NovaConfig_Workspaces,
  Shared_NovaConfigWorkspace,
} from '../../../../shared.d.ts';

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_AcyclicDiamondDependsOnGraphPasses_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_AcyclicDiamondDependsOnGraphPasses_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_AcyclicDiamondDependsOnGraphPasses_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_AcyclicDiamondDependsOnGraphPasses_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_AcyclicDiamondDependsOnGraphPasses_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_AcyclicDiamondDependsOnGraphPasses_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_AcyclicDiamondDependsOnGraphPasses_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_AcyclicDiamondDependsOnGraphPasses_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_AcyclicDiamondDependsOnGraphPasses_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_AcyclicDiamondDependsOnGraphPasses_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_AcyclicDiamondDependsOnGraphPasses_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_AcyclicDiamondDependsOnGraphPasses_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_AcyclicDiamondDependsOnGraphPasses_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_BareStringPushTriggerIsFlagged_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_BareStringPushTriggerIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_BareStringPushTriggerIsFlagged_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_BareStringPushTriggerIsFlagged_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_BareStringPushTriggerIsFlagged_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_BareStringPushTriggerIsFlagged_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_BareStringPushTriggerIsFlagged_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_BareStringPushTriggerIsFlagged_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_BareStringPushTriggerIsFlagged_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_BareStringPushTriggerIsFlagged_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_BareStringPushTriggerIsFlagged_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_BareStringPushTriggerIsFlagged_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_BareStringPushTriggerIsFlagged_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CircularDependsOnReferencesAreFlagged_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CircularDependsOnReferencesAreFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CircularDependsOnReferencesAreFlagged_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CircularDependsOnReferencesAreFlagged_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CircularDependsOnReferencesAreFlagged_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CircularDependsOnReferencesAreFlagged_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CircularDependsOnReferencesAreFlagged_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CircularDependsOnReferencesAreFlagged_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CircularDependsOnReferencesAreFlagged_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CircularDependsOnReferencesAreFlagged_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CircularDependsOnReferencesAreFlagged_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CircularDependsOnReferencesAreFlagged_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CircularDependsOnReferencesAreFlagged_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CleanConfigProducesNoDiagnosticsAndKeepsAllWorkflows_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CleanConfigProducesNoDiagnosticsAndKeepsAllWorkflows_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CleanConfigProducesNoDiagnosticsAndKeepsAllWorkflows_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CleanConfigProducesNoDiagnosticsAndKeepsAllWorkflows_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CleanConfigProducesNoDiagnosticsAndKeepsAllWorkflows_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CleanConfigProducesNoDiagnosticsAndKeepsAllWorkflows_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CleanConfigProducesNoDiagnosticsAndKeepsAllWorkflows_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CleanConfigProducesNoDiagnosticsAndKeepsAllWorkflows_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CleanConfigProducesNoDiagnosticsAndKeepsAllWorkflows_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CleanConfigProducesNoDiagnosticsAndKeepsAllWorkflows_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CleanConfigProducesNoDiagnosticsAndKeepsAllWorkflows_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CleanConfigProducesNoDiagnosticsAndKeepsAllWorkflows_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CleanConfigProducesNoDiagnosticsAndKeepsAllWorkflows_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CrossWorkflowDestinationCollisionIsFlagged_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CrossWorkflowDestinationCollisionIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CrossWorkflowDestinationCollisionIsFlagged_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CrossWorkflowDestinationCollisionIsFlagged_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CrossWorkflowDestinationCollisionIsFlagged_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CrossWorkflowDestinationCollisionIsFlagged_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CrossWorkflowDestinationCollisionIsFlagged_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CrossWorkflowDestinationCollisionIsFlagged_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CrossWorkflowDestinationCollisionIsFlagged_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CrossWorkflowDestinationCollisionIsFlagged_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CrossWorkflowDestinationCollisionIsFlagged_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CrossWorkflowDestinationCollisionIsFlagged_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_CrossWorkflowDestinationCollisionIsFlagged_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DependsOnReferenceThatDoesNotExistIsFlagged_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DependsOnReferenceThatDoesNotExistIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DependsOnReferenceThatDoesNotExistIsFlagged_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DependsOnReferenceThatDoesNotExistIsFlagged_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DependsOnReferenceThatDoesNotExistIsFlagged_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DependsOnReferenceThatDoesNotExistIsFlagged_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DependsOnReferenceThatDoesNotExistIsFlagged_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DependsOnReferenceThatDoesNotExistIsFlagged_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DependsOnReferenceThatDoesNotExistIsFlagged_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DependsOnReferenceThatDoesNotExistIsFlagged_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DependsOnReferenceThatDoesNotExistIsFlagged_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DependsOnReferenceThatDoesNotExistIsFlagged_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DependsOnReferenceThatDoesNotExistIsFlagged_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DeployFieldNeedsMigrationHintIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DeployFieldNeedsMigrationHintIsFlagged_Result = Shared_BlueprintValidationResult;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DeployFieldSettingsMigrationHintIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DeployFieldSettingsMigrationHintIsFlagged_Result = Shared_BlueprintValidationResult;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DeployFieldTypeMigrationHintIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DeployFieldTypeMigrationHintIsFlagged_Result = Shared_BlueprintValidationResult;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DeployFieldWorkingDirMigrationHintIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DeployFieldWorkingDirMigrationHintIsFlagged_Result = Shared_BlueprintValidationResult;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DestinationCollisionIsFlagged_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DestinationCollisionIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DestinationCollisionIsFlagged_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DestinationCollisionIsFlagged_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DestinationCollisionIsFlagged_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DestinationCollisionIsFlagged_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DestinationCollisionIsFlagged_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DestinationCollisionIsFlagged_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DestinationCollisionIsFlagged_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DestinationCollisionIsFlagged_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DestinationCollisionIsFlagged_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DestinationCollisionIsFlagged_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DestinationCollisionIsFlagged_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DuplicateWorkflowKeyIsFlagged_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DuplicateWorkflowKeyIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DuplicateWorkflowKeyIsFlagged_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DuplicateWorkflowKeyIsFlagged_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DuplicateWorkflowKeyIsFlagged_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DuplicateWorkflowKeyIsFlagged_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DuplicateWorkflowKeyIsFlagged_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DuplicateWorkflowKeyIsFlagged_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DuplicateWorkflowKeyIsFlagged_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DuplicateWorkflowKeyIsFlagged_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DuplicateWorkflowKeyIsFlagged_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DuplicateWorkflowKeyIsFlagged_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_DuplicateWorkflowKeyIsFlagged_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_GithubActionDestinationCollisionIsFlagged_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_GithubActionDestinationCollisionIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_GithubActionDestinationCollisionIsFlagged_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_GithubActionDestinationCollisionIsFlagged_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_GithubActionDestinationCollisionIsFlagged_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_GithubActionDestinationCollisionIsFlagged_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_GithubActionDestinationCollisionIsFlagged_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_GithubActionDestinationCollisionIsFlagged_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_GithubActionDestinationCollisionIsFlagged_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_GithubActionDestinationCollisionIsFlagged_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_GithubActionDestinationCollisionIsFlagged_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_GithubActionDestinationCollisionIsFlagged_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_GithubActionDestinationCollisionIsFlagged_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_GithubActionMissingLiteralSettingsAreFlagged_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_GithubActionMissingLiteralSettingsAreFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_GithubActionMissingLiteralSettingsAreFlagged_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_GithubActionMissingLiteralSettingsAreFlagged_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_GithubActionMissingLiteralSettingsAreFlagged_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_GithubActionMissingLiteralSettingsAreFlagged_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_GithubActionMissingLiteralSettingsAreFlagged_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_GithubActionMissingLiteralSettingsAreFlagged_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_GithubActionMissingLiteralSettingsAreFlagged_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_GithubActionMissingLiteralSettingsAreFlagged_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_GithubActionMissingLiteralSettingsAreFlagged_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_GithubActionMissingLiteralSettingsAreFlagged_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_GithubActionMissingLiteralSettingsAreFlagged_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingLiteralIsFlagged_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingLiteralIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingLiteralIsFlagged_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingLiteralIsFlagged_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingLiteralIsFlagged_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingLiteralIsFlagged_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingLiteralIsFlagged_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingLiteralIsFlagged_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingLiteralIsFlagged_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingLiteralIsFlagged_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingLiteralIsFlagged_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingLiteralIsFlagged_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingLiteralIsFlagged_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingSuffixIsFlagged_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingSuffixIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingSuffixIsFlagged_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingSuffixIsFlagged_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingSuffixIsFlagged_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingSuffixIsFlagged_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingSuffixIsFlagged_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingSuffixIsFlagged_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingSuffixIsFlagged_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingSuffixIsFlagged_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingSuffixIsFlagged_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingSuffixIsFlagged_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingSuffixIsFlagged_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingTriggersIsFlagged_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingTriggersIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingTriggersIsFlagged_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingTriggersIsFlagged_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingTriggersIsFlagged_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingTriggersIsFlagged_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingTriggersIsFlagged_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingTriggersIsFlagged_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingTriggersIsFlagged_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingTriggersIsFlagged_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingTriggersIsFlagged_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingTriggersIsFlagged_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_MissingTriggersIsFlagged_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_ObjectFormTriggersPass_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_ObjectFormTriggersPass_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_ObjectFormTriggersPass_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_ObjectFormTriggersPass_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_ObjectFormTriggersPass_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_ObjectFormTriggersPass_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_ObjectFormTriggersPass_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_ObjectFormTriggersPass_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_ObjectFormTriggersPass_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_ObjectFormTriggersPass_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_ObjectFormTriggersPass_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_ObjectFormTriggersPass_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_ObjectFormTriggersPass_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerObjectWithoutBranchesIsFlagged_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerObjectWithoutBranchesIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerObjectWithoutBranchesIsFlagged_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerObjectWithoutBranchesIsFlagged_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerObjectWithoutBranchesIsFlagged_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerObjectWithoutBranchesIsFlagged_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerObjectWithoutBranchesIsFlagged_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerObjectWithoutBranchesIsFlagged_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerObjectWithoutBranchesIsFlagged_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerObjectWithoutBranchesIsFlagged_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerObjectWithoutBranchesIsFlagged_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerObjectWithoutBranchesIsFlagged_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerObjectWithoutBranchesIsFlagged_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerWithAnEmptyBranchesArrayIsFlagged_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerWithAnEmptyBranchesArrayIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerWithAnEmptyBranchesArrayIsFlagged_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerWithAnEmptyBranchesArrayIsFlagged_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerWithAnEmptyBranchesArrayIsFlagged_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerWithAnEmptyBranchesArrayIsFlagged_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerWithAnEmptyBranchesArrayIsFlagged_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerWithAnEmptyBranchesArrayIsFlagged_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerWithAnEmptyBranchesArrayIsFlagged_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerWithAnEmptyBranchesArrayIsFlagged_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerWithAnEmptyBranchesArrayIsFlagged_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerWithAnEmptyBranchesArrayIsFlagged_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerWithAnEmptyBranchesArrayIsFlagged_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerWithInvalidPathsIsFlagged_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerWithInvalidPathsIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerWithInvalidPathsIsFlagged_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerWithInvalidPathsIsFlagged_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerWithInvalidPathsIsFlagged_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerWithInvalidPathsIsFlagged_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerWithInvalidPathsIsFlagged_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerWithInvalidPathsIsFlagged_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerWithInvalidPathsIsFlagged_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerWithInvalidPathsIsFlagged_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerWithInvalidPathsIsFlagged_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerWithInvalidPathsIsFlagged_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_PushTriggerWithInvalidPathsIsFlagged_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_ScheduleDailyAndMonthlyTriggersPass_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_ScheduleDailyAndMonthlyTriggersPass_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_ScheduleDailyAndMonthlyTriggersPass_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_ScheduleDailyAndMonthlyTriggersPass_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_ScheduleDailyAndMonthlyTriggersPass_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_ScheduleDailyAndMonthlyTriggersPass_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_ScheduleDailyAndMonthlyTriggersPass_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_ScheduleDailyAndMonthlyTriggersPass_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_ScheduleDailyAndMonthlyTriggersPass_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_ScheduleDailyAndMonthlyTriggersPass_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_ScheduleDailyAndMonthlyTriggersPass_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_ScheduleDailyAndMonthlyTriggersPass_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_ScheduleDailyAndMonthlyTriggersPass_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_SingletonTargetCollisionIsFlagged_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_SingletonTargetCollisionIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_SingletonTargetCollisionIsFlagged_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_SingletonTargetCollisionIsFlagged_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_SingletonTargetCollisionIsFlagged_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_SingletonTargetCollisionIsFlagged_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_SingletonTargetCollisionIsFlagged_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_SingletonTargetCollisionIsFlagged_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_SingletonTargetCollisionIsFlagged_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_SingletonTargetCollisionIsFlagged_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_SingletonTargetCollisionIsFlagged_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_SingletonTargetCollisionIsFlagged_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_SingletonTargetCollisionIsFlagged_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_SingletonTargetViolationIsFlagged_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_SingletonTargetViolationIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_SingletonTargetViolationIsFlagged_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_SingletonTargetViolationIsFlagged_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_SingletonTargetViolationIsFlagged_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_SingletonTargetViolationIsFlagged_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_SingletonTargetViolationIsFlagged_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_SingletonTargetViolationIsFlagged_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_SingletonTargetViolationIsFlagged_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_SingletonTargetViolationIsFlagged_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_SingletonTargetViolationIsFlagged_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_SingletonTargetViolationIsFlagged_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_SingletonTargetViolationIsFlagged_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TagPushTriggerOnAnIssueTemplateIsFlagged_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TagPushTriggerOnAnIssueTemplateIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TagPushTriggerOnAnIssueTemplateIsFlagged_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TagPushTriggerOnAnIssueTemplateIsFlagged_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TagPushTriggerOnAnIssueTemplateIsFlagged_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TagPushTriggerOnAnIssueTemplateIsFlagged_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TagPushTriggerOnAnIssueTemplateIsFlagged_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TagPushTriggerOnAnIssueTemplateIsFlagged_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TagPushTriggerOnAnIssueTemplateIsFlagged_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TagPushTriggerOnAnIssueTemplateIsFlagged_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TagPushTriggerOnAnIssueTemplateIsFlagged_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TagPushTriggerOnAnIssueTemplateIsFlagged_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TagPushTriggerOnAnIssueTemplateIsFlagged_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TagPushTriggerWithInvalidTagsIsFlagged_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TagPushTriggerWithInvalidTagsIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TagPushTriggerWithInvalidTagsIsFlagged_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TagPushTriggerWithInvalidTagsIsFlagged_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TagPushTriggerWithInvalidTagsIsFlagged_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TagPushTriggerWithInvalidTagsIsFlagged_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TagPushTriggerWithInvalidTagsIsFlagged_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TagPushTriggerWithInvalidTagsIsFlagged_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TagPushTriggerWithInvalidTagsIsFlagged_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TagPushTriggerWithInvalidTagsIsFlagged_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TagPushTriggerWithInvalidTagsIsFlagged_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TagPushTriggerWithInvalidTagsIsFlagged_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TagPushTriggerWithInvalidTagsIsFlagged_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TargetTypeNotBuildableIsFlagged_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TargetTypeNotBuildableIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TargetTypeNotBuildableIsFlagged_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TargetTypeNotBuildableIsFlagged_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TargetTypeNotBuildableIsFlagged_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TargetTypeNotBuildableIsFlagged_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TargetTypeNotBuildableIsFlagged_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TargetTypeNotBuildableIsFlagged_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TargetTypeNotBuildableIsFlagged_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TargetTypeNotBuildableIsFlagged_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TargetTypeNotBuildableIsFlagged_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TargetTypeNotBuildableIsFlagged_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TargetTypeNotBuildableIsFlagged_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TriggerNotValidForTemplateIsFlagged_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TriggerNotValidForTemplateIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TriggerNotValidForTemplateIsFlagged_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TriggerNotValidForTemplateIsFlagged_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TriggerNotValidForTemplateIsFlagged_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TriggerNotValidForTemplateIsFlagged_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TriggerNotValidForTemplateIsFlagged_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TriggerNotValidForTemplateIsFlagged_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TriggerNotValidForTemplateIsFlagged_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TriggerNotValidForTemplateIsFlagged_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TriggerNotValidForTemplateIsFlagged_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TriggerNotValidForTemplateIsFlagged_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_TriggerNotValidForTemplateIsFlagged_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnknownTemplateIsFlagged_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnknownTemplateIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnknownTemplateIsFlagged_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnknownTemplateIsFlagged_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnknownTemplateIsFlagged_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnknownTemplateIsFlagged_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnknownTemplateIsFlagged_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnknownTemplateIsFlagged_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnknownTemplateIsFlagged_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnknownTemplateIsFlagged_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnknownTemplateIsFlagged_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnknownTemplateIsFlagged_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnknownTemplateIsFlagged_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnregisteredScopeIsFlagged_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnregisteredScopeIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnregisteredScopeIsFlagged_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnregisteredScopeIsFlagged_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnregisteredScopeIsFlagged_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnregisteredScopeIsFlagged_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnregisteredScopeIsFlagged_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnregisteredScopeIsFlagged_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnregisteredScopeIsFlagged_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnregisteredScopeIsFlagged_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnregisteredScopeIsFlagged_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnregisteredScopeIsFlagged_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnregisteredScopeIsFlagged_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnregisteredWorkingDirIsFlagged_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnregisteredWorkingDirIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnregisteredWorkingDirIsFlagged_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnregisteredWorkingDirIsFlagged_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnregisteredWorkingDirIsFlagged_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnregisteredWorkingDirIsFlagged_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnregisteredWorkingDirIsFlagged_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnregisteredWorkingDirIsFlagged_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnregisteredWorkingDirIsFlagged_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnregisteredWorkingDirIsFlagged_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnregisteredWorkingDirIsFlagged_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnregisteredWorkingDirIsFlagged_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_UnregisteredWorkingDirIsFlagged_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowFieldDependsOnMigrationHintIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowFieldDependsOnMigrationHintIsFlagged_Result = Shared_BlueprintValidationResult;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowFieldScopesMigrationHintIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowFieldScopesMigrationHintIsFlagged_Result = Shared_BlueprintValidationResult;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowFieldSettingsMigrationHintIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowFieldSettingsMigrationHintIsFlagged_Result = Shared_BlueprintValidationResult;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowFieldSuffixMigrationHintIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowFieldSuffixMigrationHintIsFlagged_Result = Shared_BlueprintValidationResult;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowFieldTargetsMigrationHintIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowFieldTargetsMigrationHintIsFlagged_Result = Shared_BlueprintValidationResult;

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowRunTriggerWithAValidDependsOnPasses_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowRunTriggerWithAValidDependsOnPasses_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowRunTriggerWithAValidDependsOnPasses_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowRunTriggerWithAValidDependsOnPasses_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowRunTriggerWithAValidDependsOnPasses_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowRunTriggerWithAValidDependsOnPasses_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowRunTriggerWithAValidDependsOnPasses_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowRunTriggerWithAValidDependsOnPasses_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowRunTriggerWithAValidDependsOnPasses_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowRunTriggerWithAValidDependsOnPasses_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowRunTriggerWithAValidDependsOnPasses_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowRunTriggerWithAValidDependsOnPasses_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowRunTriggerWithAValidDependsOnPasses_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowRunTriggerWithoutDependsOnIsFlagged_Workspaces = Shared_NovaConfig_Workspaces;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowRunTriggerWithoutDependsOnIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowRunTriggerWithoutDependsOnIsFlagged_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowRunTriggerWithoutDependsOnIsFlagged_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowRunTriggerWithoutDependsOnIsFlagged_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowRunTriggerWithoutDependsOnIsFlagged_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowRunTriggerWithoutDependsOnIsFlagged_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowRunTriggerWithoutDependsOnIsFlagged_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowRunTriggerWithoutDependsOnIsFlagged_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowRunTriggerWithoutDependsOnIsFlagged_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowRunTriggerWithoutDependsOnIsFlagged_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowRunTriggerWithoutDependsOnIsFlagged_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkflowRunTriggerWithoutDependsOnIsFlagged_ResultDiagnostics;
};

/**
 * Tests - CLI - Generate - GitHub - Workflows Blueprint Validate - Validator Validate.
 *
 * @since 0.21.0
 */
export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkspaceDotenvMigrationHintIsFlagged_WorkspacesEntry = Shared_NovaConfigWorkspace & Record<string, unknown>;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkspaceDotenvMigrationHintIsFlagged_Workspaces = {
  [key: string]: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkspaceDotenvMigrationHintIsFlagged_WorkspacesEntry;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkspaceDotenvMigrationHintIsFlagged_RawWorkflows = unknown[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkspaceDotenvMigrationHintIsFlagged_ResultWorkflows = Shared_BlueprintConfigWorkflow[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkspaceDotenvMigrationHintIsFlagged_ResultDiagnosticSeverity = 'error';

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkspaceDotenvMigrationHintIsFlagged_ResultDiagnosticMessage = string;

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkspaceDotenvMigrationHintIsFlagged_ResultDiagnostic = {
  severity: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkspaceDotenvMigrationHintIsFlagged_ResultDiagnosticSeverity;
  message: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkspaceDotenvMigrationHintIsFlagged_ResultDiagnosticMessage;
};

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkspaceDotenvMigrationHintIsFlagged_ResultDiagnostics = Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkspaceDotenvMigrationHintIsFlagged_ResultDiagnostic[];

export type Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkspaceDotenvMigrationHintIsFlagged_Result = {
  workflows: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkspaceDotenvMigrationHintIsFlagged_ResultWorkflows;
  diagnostics: Tests_Cli_Generate_Github_WorkflowsBlueprintValidate_ValidatorValidate_WorkspaceDotenvMigrationHintIsFlagged_ResultDiagnostics;
};
