/**
 * Tests - Link - Link Validation.
 *
 * @since 0.14.0
 */
export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_Cwd = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_ContentDirs = string[];

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_MdFiles = string[];

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_ContentPath = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_Entries = string[];

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_Ext = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_ExistingPaths = Set<string>;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_BlogPaths = Set<string>;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_IdPaths = Set<string>;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_DocRelativePath = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_WithoutExt = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_IndexSuffix = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_FilePath = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_Content = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_IdMatch = RegExpExecArray | null;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_Id = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_Dir = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_IdPath = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_FileHeadings = Map<string, Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_Headings>;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_HeadingFilePath = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_HeadingContent = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_Headings = Set<string>;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_MatchCapture = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_Anchor = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_SelfWithoutExt = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_DocMapRelativePath = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_DocWithoutExt = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_DocIndexSuffix = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_DocIdMatch = RegExpExecArray | null;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_DocId = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_DocDir = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_DocIdPath = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_SlugMatch = RegExpExecArray | null;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_BlogSlug = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_BlogFileName = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_Failures = string[];

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_LinkFilePath = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_LinkContent = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_Lines = string[];

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_InCodeBlock = boolean;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_ProseLines = string[];

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_Prose = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_Href = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_SelfAnchor = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_CurrentPath = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_HeadingsLookup = Set<string> | undefined;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_PathPartValue = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_DocAnchor = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_DocPath = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_DocHeadingsLookup = Set<string> | undefined;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_BlogPathPartValue = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_BlogAnchor = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_BlogPath = string;

export type Tests_Link_LinkValidation_AllInternalLinksPointToExistingFilesAndAnchors_BlogHeadingsLookup = Set<string> | undefined;
