/**
 * Tests - Terminology - Terminology Validation.
 *
 * @since 0.14.0
 */
export type Tests_Terminology_TerminologyValidation_AllTerminologyComponentsHaveValidAttributesAndAnchors_Cwd = string;

export type Tests_Terminology_TerminologyValidation_AllTerminologyComponentsHaveValidAttributesAndAnchors_ContentDirs = string[];

export type Tests_Terminology_TerminologyValidation_AllTerminologyComponentsHaveValidAttributesAndAnchors_TerminologyPath = string;

export type Tests_Terminology_TerminologyValidation_AllTerminologyComponentsHaveValidAttributesAndAnchors_TerminologyContent = string;

export type Tests_Terminology_TerminologyValidation_AllTerminologyComponentsHaveValidAttributesAndAnchors_ValidAnchors = Set<string>;

export type Tests_Terminology_TerminologyValidation_AllTerminologyComponentsHaveValidAttributesAndAnchors_HeadingCapture = string;

export type Tests_Terminology_TerminologyValidation_AllTerminologyComponentsHaveValidAttributesAndAnchors_HeadingText = string;

export type Tests_Terminology_TerminologyValidation_AllTerminologyComponentsHaveValidAttributesAndAnchors_MdFiles = string[];

export type Tests_Terminology_TerminologyValidation_AllTerminologyComponentsHaveValidAttributesAndAnchors_ContentPath = string;

export type Tests_Terminology_TerminologyValidation_AllTerminologyComponentsHaveValidAttributesAndAnchors_Entries = string[];

export type Tests_Terminology_TerminologyValidation_AllTerminologyComponentsHaveValidAttributesAndAnchors_Ext = string;

export type Tests_Terminology_TerminologyValidation_AllTerminologyComponentsHaveValidAttributesAndAnchors_Failures = string[];

export type Tests_Terminology_TerminologyValidation_AllTerminologyComponentsHaveValidAttributesAndAnchors_FilePath = string;

export type Tests_Terminology_TerminologyValidation_AllTerminologyComponentsHaveValidAttributesAndAnchors_Content = string;

export type Tests_Terminology_TerminologyValidation_AllTerminologyComponentsHaveValidAttributesAndAnchors_StrippedContent = string;

export type Tests_Terminology_TerminologyValidation_AllTerminologyComponentsHaveValidAttributesAndAnchors_Attrs = string;

export type Tests_Terminology_TerminologyValidation_AllTerminologyComponentsHaveValidAttributesAndAnchors_Children = string;

export type Tests_Terminology_TerminologyValidation_AllTerminologyComponentsHaveValidAttributesAndAnchors_TitleMatch = RegExpExecArray | null;

export type Tests_Terminology_TerminologyValidation_AllTerminologyComponentsHaveValidAttributesAndAnchors_ToMatch = RegExpExecArray | null;

export type Tests_Terminology_TerminologyValidation_AllTerminologyComponentsHaveValidAttributesAndAnchors_ToValue = string;

export type Tests_Terminology_TerminologyValidation_AllTerminologyComponentsHaveValidAttributesAndAnchors_ExpectedBase = string;

export type Tests_Terminology_TerminologyValidation_AllTerminologyComponentsHaveValidAttributesAndAnchors_Anchor = string;
