run-name: "${{ github.event_name == 'issues' && format('Analyzing issue #{0}', github.event.issue.number) || format('Analyzing comment on issue #{0}', github.event.issue.number) }}"
publish-condition: ""
trigger:
  issues:
    types: [ "opened", "closed" ]
