/**
 * Tests - CLI - Scaffold - Docs - Docusaurus - Run.
 *
 * @since 0.15.0
 */
export type Tests_Cli_Scaffold_Docs_Docusaurus_CliScaffoldDocsDocusaurusRun_OriginalCwd = string;

export type Tests_Cli_Scaffold_Docs_Docusaurus_CliScaffoldDocsDocusaurusRun_TemporaryDirectory = string;

export type Tests_Cli_Scaffold_Docs_Docusaurus_CliScaffoldDocsDocusaurusRun_TemporaryBase = string;

export type Tests_Cli_Scaffold_Docs_Docusaurus_CliScaffoldDocsDocusaurusRun_SandboxRoot = string;

export type Tests_Cli_Scaffold_Docs_Docusaurus_CliScaffoldDocsDocusaurusRun_RootDirectory = string;

export type Tests_Cli_Scaffold_Docs_Docusaurus_CliScaffoldDocsDocusaurusRun_ChildDirectory = string;

export type Tests_Cli_Scaffold_Docs_Docusaurus_CliScaffoldDocsDocusaurusRun_RootPackageJson = string;

export type Tests_Cli_Scaffold_Docs_Docusaurus_CliScaffoldDocsDocusaurusRun_RootPackageJsonPath = string;

export type Tests_Cli_Scaffold_Docs_Docusaurus_CliScaffoldDocsDocusaurusRun_ChildPackageJson = string;

export type Tests_Cli_Scaffold_Docs_Docusaurus_CliScaffoldDocsDocusaurusRun_ChildPackageJsonPath = string;

export type Tests_Cli_Scaffold_Docs_Docusaurus_CliScaffoldDocsDocusaurusRun_ProjectDirectory = string;

export type Tests_Cli_Scaffold_Docs_Docusaurus_CliScaffoldDocsDocusaurusRun_Exists = boolean;

export type Tests_Cli_Scaffold_Docs_Docusaurus_CliScaffoldDocsDocusaurusRun_DryRunOutputPath = string;

export type Tests_Cli_Scaffold_Docs_Docusaurus_CliScaffoldDocsDocusaurusRun_WorkspacePackageJsonPath = string;

export type Tests_Cli_Scaffold_Docs_Docusaurus_CliScaffoldDocsDocusaurusRun_DocusaurusConfigPath = string;

export type Tests_Cli_Scaffold_Docs_Docusaurus_CliScaffoldDocsDocusaurusRun_IntroMdPath = string;

export type Tests_Cli_Scaffold_Docs_Docusaurus_CliScaffoldDocsDocusaurusRun_PackageJson = string;

export type Tests_Cli_Scaffold_Docs_Docusaurus_CliScaffoldDocsDocusaurusRun_PackageJsonPath = string;
