import { ok, strictEqual } from 'node:assert/strict';
import {
  mkdir,
  mkdtemp,
  readFile,
  rm,
  writeFile,
} from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import {
  afterAll,
  describe,
  it,
  vi,
} from 'vitest';

vi.mock('prompts', () => (
  {
    default: vi.fn().mockResolvedValue(
      {
        key: '',
      },
    ),
  }
));

import { CliGenerateMustHavesDotenv } from '../../../../cli/generate/must-haves/dotenv.js';

import type {
  TestsCliGenerateMustHavesDotenvRunEnvPath,
  TestsCliGenerateMustHavesDotenvRunEnvSamplePath,
  TestsCliGenerateMustHavesDotenvRunEnvSampleWritten,
  TestsCliGenerateMustHavesDotenvRunEnvWritten,
  TestsCliGenerateMustHavesDotenvRunExpectedEnvBanner,
  TestsCliGenerateMustHavesDotenvRunExpectedSampleBanner,
  TestsCliGenerateMustHavesDotenvRunOriginalCwd,
  TestsCliGenerateMustHavesDotenvRunProjectDirectory,
  TestsCliGenerateMustHavesDotenvRunSandboxRoot,
  TestsCliGenerateMustHavesDotenvRunTemporaryDirectory,
  TestsCliGenerateMustHavesDotenvRunTemporaryPrefix,
} from '../../../../types/tests/cli/generate/must-haves/dotenv.test.d.ts';

/**
 * Tests - CLI - Generate - Must Haves - Dotenv - Run.
 *
 * @since 0.15.0
 */
describe('CliGenerateMustHavesDotenv.run', async () => {
  const originalCwd: TestsCliGenerateMustHavesDotenvRunOriginalCwd = process.cwd();
  const temporaryDirectory: TestsCliGenerateMustHavesDotenvRunTemporaryDirectory = tmpdir();
  const temporaryPrefix: TestsCliGenerateMustHavesDotenvRunTemporaryPrefix = join(temporaryDirectory, `nova-${'test'}-`);
  const sandboxRoot: TestsCliGenerateMustHavesDotenvRunSandboxRoot = await mkdtemp(temporaryPrefix);

  afterAll(async () => {
    process.chdir(originalCwd);

    await rm(sandboxRoot, {
      recursive: true,
      force: true,
    });

    return;
  });

  it('sets exit code when not at project root', async () => {
    const projectDirectory: TestsCliGenerateMustHavesDotenvRunProjectDirectory = join(sandboxRoot, 'not-project-root');

    await mkdir(projectDirectory, { recursive: true });

    process.chdir(projectDirectory);

    await CliGenerateMustHavesDotenv.run({});

    strictEqual(process.exitCode, 1);

    return;
  });

  it('generates .env with fillable header banner and .env.sample with strict header banner', async () => {
    const projectDirectory: TestsCliGenerateMustHavesDotenvRunProjectDirectory = join(sandboxRoot, 'with-banner-headers');

    await mkdir(projectDirectory, { recursive: true });
    await mkdir(join(projectDirectory, '.git'), { recursive: true });
    await writeFile(join(projectDirectory, 'package.json'), JSON.stringify({ name: 'test-project' }));

    process.chdir(projectDirectory);

    await CliGenerateMustHavesDotenv.run(
      {
        replaceFile: true,
      },
    );

    const envPath: TestsCliGenerateMustHavesDotenvRunEnvPath = join(projectDirectory, '.env');
    const envSamplePath: TestsCliGenerateMustHavesDotenvRunEnvSamplePath = join(projectDirectory, '.env.sample');
    const envWritten: TestsCliGenerateMustHavesDotenvRunEnvWritten = await readFile(envPath, 'utf-8');
    const envSampleWritten: TestsCliGenerateMustHavesDotenvRunEnvSampleWritten = await readFile(envSamplePath, 'utf-8');

    const expectedEnvBanner: TestsCliGenerateMustHavesDotenvRunExpectedEnvBanner = [
      '# This file is generated by @cbnventures/nova.',
      '# You may fill in values for existing keys only — do not add, rename, or remove keys.',
      '#',
      '# Run `nova generate must-haves dotenv` to regenerate.',
      '# See: https://nova.cbnventures.io/docs/cli/generators/must-haves/dotenv',
      '',
      '',
    ].join('\n');

    const expectedSampleBanner: TestsCliGenerateMustHavesDotenvRunExpectedSampleBanner = [
      '# This file is generated by @cbnventures/nova.',
      '# Do not edit manually.',
      '#',
      '# Run `nova generate must-haves dotenv` to regenerate.',
      '# See: https://nova.cbnventures.io/docs/cli/generators/must-haves/dotenv',
      '',
      '',
    ].join('\n');

    ok(envWritten.startsWith(expectedEnvBanner));
    ok(envSampleWritten.startsWith(expectedSampleBanner));

    return;
  });

  return;
});
