import { ok, strictEqual } from 'node:assert/strict';
import {
  mkdir,
  mkdtemp,
  readFile,
  rm,
  writeFile,
} from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import {
  afterAll,
  describe,
  it,
  vi,
} from 'vitest';

import { CliGenerateMustHavesGitignore } from '../../../../cli/generate/must-haves/gitignore.js';

vi.mock('prompts', () => (
  {
    default: vi.fn().mockResolvedValue(
      {
        entry: '',
      },
    ),
  }
));

import type {
  TestsCliGenerateMustHavesGitignoreRunExpectedBanner,
  TestsCliGenerateMustHavesGitignoreRunGitignorePath,
  TestsCliGenerateMustHavesGitignoreRunOriginalCwd,
  TestsCliGenerateMustHavesGitignoreRunProjectDirectory,
  TestsCliGenerateMustHavesGitignoreRunSandboxRoot,
  TestsCliGenerateMustHavesGitignoreRunTemporaryDirectory,
  TestsCliGenerateMustHavesGitignoreRunTemporaryPrefix,
  TestsCliGenerateMustHavesGitignoreRunWritten,
} from '../../../../types/tests/cli/generate/must-haves/gitignore.test.d.ts';

/**
 * Tests - CLI - Generate - Must Haves - Gitignore - Run.
 *
 * @since 0.15.0
 */
describe('CliGenerateMustHavesGitignore.run', async () => {
  const originalCwd: TestsCliGenerateMustHavesGitignoreRunOriginalCwd = process.cwd();
  const temporaryDirectory: TestsCliGenerateMustHavesGitignoreRunTemporaryDirectory = tmpdir();
  const temporaryPrefix: TestsCliGenerateMustHavesGitignoreRunTemporaryPrefix = join(temporaryDirectory, `nova-${'test'}-`);
  const sandboxRoot: TestsCliGenerateMustHavesGitignoreRunSandboxRoot = await mkdtemp(temporaryPrefix);

  afterAll(async () => {
    process.chdir(originalCwd);

    await rm(sandboxRoot, {
      recursive: true,
      force: true,
    });

    return;
  });

  it('sets exit code when not at project root', async () => {
    const projectDirectory: TestsCliGenerateMustHavesGitignoreRunProjectDirectory = join(sandboxRoot, 'not-project-root');

    await mkdir(projectDirectory, { recursive: true });

    process.chdir(projectDirectory);

    await CliGenerateMustHavesGitignore.run({});

    strictEqual(process.exitCode, 1);

    return;
  });

  it('generates .gitignore with strict header banner', async () => {
    const projectDirectory: TestsCliGenerateMustHavesGitignoreRunProjectDirectory = join(sandboxRoot, 'with-banner-header');

    await mkdir(projectDirectory, { recursive: true });
    await mkdir(join(projectDirectory, '.git'), { recursive: true });
    await writeFile(join(projectDirectory, 'package.json'), JSON.stringify({ name: 'test-project' }));

    process.chdir(projectDirectory);

    await CliGenerateMustHavesGitignore.run(
      {
        replaceFile: true,
      },
    );

    const gitignorePath: TestsCliGenerateMustHavesGitignoreRunGitignorePath = join(projectDirectory, '.gitignore');
    const written: TestsCliGenerateMustHavesGitignoreRunWritten = await readFile(gitignorePath, 'utf-8');

    const expectedBanner: TestsCliGenerateMustHavesGitignoreRunExpectedBanner = [
      '# This file is generated by @cbnventures/nova.',
      '# Do not edit manually.',
      '#',
      '# Run `nova generate must-haves gitignore` to regenerate.',
      '# See: https://nova.cbnventures.io/docs/cli/generators/must-haves/gitignore',
      '',
      '',
    ].join('\n');

    ok(written.startsWith(expectedBanner));

    return;
  });

  return;
});
