import type { readFile as fsPromisesReadFile } from 'node:fs/promises';

import type { vi } from 'vitest';

import type { Shared_NovaConfig_Project_License } from '../../../../shared.d.ts';
import type { Toolkit_Logger_Runner_Customize_Returns } from '../../../../toolkit/logger.d.ts';

/**
 * Tests - CLI - Recipe - License - Update Copyright - Run.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_OriginalCwd = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_TemporaryDirectory = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_SandboxPath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_SandboxRoot = string;

/**
 * Tests - CLI - Recipe - License - Update Copyright - CLI Recipe License Update Copyright Run - A Consumer LICENSE Read Rejection Is Skipped While Other Copies Refresh.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_ProjectDirectory = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_Template = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_RootPath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_UnreadablePath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_GoodPath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_StaleContent = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_IsProjectRootSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_LoadSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_OriginalReadFile = typeof fsPromisesReadFile;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_BrokenSuffix = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_ReadFileSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_PermissionError = NodeJS.ErrnoException;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_CustomizedLoggerMock_Debug = ReturnType<typeof vi['fn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_CustomizedLoggerMock_Dev = ReturnType<typeof vi['fn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_CustomizedLoggerMock_Info = ReturnType<typeof vi['fn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_CustomizedLoggerMock_Warn = ReturnType<typeof vi['fn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_CustomizedLoggerMock_Error = ReturnType<typeof vi['fn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_CustomizedLoggerMock = {
  debug: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_CustomizedLoggerMock_Debug;
  dev: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_CustomizedLoggerMock_Dev;
  info: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_CustomizedLoggerMock_Info;
  warn: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_CustomizedLoggerMock_Warn;
  error: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_CustomizedLoggerMock_Error;
};

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_LoggerCustomizeSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_LoggerCustomizeReturn = Toolkit_Logger_Runner_Customize_Returns;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_Threw = boolean;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_ExpectedContent = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_RootOutput = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_GoodOutput = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_WarnCalls = unknown[][];

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEReadRejectionIsSkippedWhileOtherCopiesRefresh_InfoCalls = unknown[][];

/**
 * Tests - CLI - Recipe - License - Update Copyright - CLI Recipe License Update Copyright Run - A Consumer LICENSE That Is A Directory Is Skipped While Other Copies Refresh.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_ProjectDirectory = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_Template = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_RootPath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_DirLicensePath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_GoodPath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_StaleContent = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_IsProjectRootSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_LoadSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_CustomizedLoggerMock_Debug = ReturnType<typeof vi['fn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_CustomizedLoggerMock_Dev = ReturnType<typeof vi['fn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_CustomizedLoggerMock_Info = ReturnType<typeof vi['fn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_CustomizedLoggerMock_Warn = ReturnType<typeof vi['fn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_CustomizedLoggerMock_Error = ReturnType<typeof vi['fn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_CustomizedLoggerMock = {
  debug: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_CustomizedLoggerMock_Debug;
  dev: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_CustomizedLoggerMock_Dev;
  info: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_CustomizedLoggerMock_Info;
  warn: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_CustomizedLoggerMock_Warn;
  error: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_CustomizedLoggerMock_Error;
};

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_LoggerCustomizeSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_LoggerCustomizeReturn = Toolkit_Logger_Runner_Customize_Returns;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_Threw = boolean;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_ExpectedContent = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_RootOutput = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_GoodOutput = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_WarnCalls = unknown[][];

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_AConsumerLICENSEThatIsADirectoryIsSkippedWhileOtherCopiesRefresh_InfoCalls = unknown[][];

/**
 * Tests - CLI - Recipe - License - Update Copyright - CLI Recipe License Update Copyright Run - Apache Indented Regenerates Holder And Year And Keeps Body Byte Identical.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ApacheIndentedRegeneratesHolderAndYearAndKeepsBodyByteIdentical_ProjectDirectory = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ApacheIndentedRegeneratesHolderAndYearAndKeepsBodyByteIdentical_Template = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ApacheIndentedRegeneratesHolderAndYearAndKeepsBodyByteIdentical_LicensePath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ApacheIndentedRegeneratesHolderAndYearAndKeepsBodyByteIdentical_IsProjectRootSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ApacheIndentedRegeneratesHolderAndYearAndKeepsBodyByteIdentical_LoadSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ApacheIndentedRegeneratesHolderAndYearAndKeepsBodyByteIdentical_Output = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ApacheIndentedRegeneratesHolderAndYearAndKeepsBodyByteIdentical_ExpectedContent = string;

/**
 * Tests - CLI - Recipe - License - Update Copyright - CLI Recipe License Update Copyright Run - Bsd Comma Regenerates Holder And Year And Keeps Body Byte Identical.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_BSDCommaRegeneratesHolderAndYearAndKeepsBodyByteIdentical_ProjectDirectory = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_BSDCommaRegeneratesHolderAndYearAndKeepsBodyByteIdentical_Template = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_BSDCommaRegeneratesHolderAndYearAndKeepsBodyByteIdentical_LicensePath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_BSDCommaRegeneratesHolderAndYearAndKeepsBodyByteIdentical_IsProjectRootSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_BSDCommaRegeneratesHolderAndYearAndKeepsBodyByteIdentical_LoadSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_BSDCommaRegeneratesHolderAndYearAndKeepsBodyByteIdentical_Output = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_BSDCommaRegeneratesHolderAndYearAndKeepsBodyByteIdentical_ExpectedContent = string;

/**
 * Tests - CLI - Recipe - License - Update Copyright - CLI Recipe License Update Copyright Run - Disabled Flag Skips And Does Not Write.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DisabledFlagSkipsAndDoesNotWrite_ProjectDirectory = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DisabledFlagSkipsAndDoesNotWrite_Template = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DisabledFlagSkipsAndDoesNotWrite_LicensePath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DisabledFlagSkipsAndDoesNotWrite_OnDiskContent = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DisabledFlagSkipsAndDoesNotWrite_IsProjectRootSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DisabledFlagSkipsAndDoesNotWrite_LoadSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DisabledFlagSkipsAndDoesNotWrite_Output = string;

/**
 * Tests - CLI - Recipe - License - Update Copyright - CLI Recipe License Update Copyright Run - Dollar Metacharacter Holder Is Written Verbatim.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_ProjectDirectory = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_Template = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_LicensePath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_OldContent = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_LegalName = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_IsProjectRootSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_LoadSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_Output = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_YearRange = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_ExpectedContent = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DollarMetacharacterHolderIsWrittenVerbatim_ExpectedHolderLine = string;

/**
 * Tests - CLI - Recipe - License - Update Copyright - CLI Recipe License Update Copyright Run - Dry Run Does Not Write.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunDoesNotWrite_ProjectDirectory = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunDoesNotWrite_Template = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunDoesNotWrite_LicensePath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunDoesNotWrite_OnDiskContent = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunDoesNotWrite_IsProjectRootSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunDoesNotWrite_LoadSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunDoesNotWrite_Output = string;

/**
 * Tests - CLI - Recipe - License - Update Copyright - CLI Recipe License Update Copyright Run - Dry Run Writes Nothing Anywhere In A Fan Out Tree.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_ProjectDirectory = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_Template = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_RootPath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_AppPath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_StaleContent = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_IsProjectRootSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_LoadSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_SaveGeneratedFileSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_RootOutput = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DryRunWritesNothingAnywhereInAFanOutTree_AppOutput = string;

/**
 * Tests - CLI - Recipe - License - Update Copyright - CLI Recipe License Update Copyright Run - Dual Copyright Holder Is Skipped And Never Rewritten.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_ProjectDirectory = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_Template = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_LicensePath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_InjectedHolder = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_OnDiskContent = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_IsProjectRootSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_LoadSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_CustomizedLoggerMock_Debug = ReturnType<typeof vi['fn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_CustomizedLoggerMock_Dev = ReturnType<typeof vi['fn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_CustomizedLoggerMock_Info = ReturnType<typeof vi['fn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_CustomizedLoggerMock_Warn = ReturnType<typeof vi['fn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_CustomizedLoggerMock_Error = ReturnType<typeof vi['fn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_CustomizedLoggerMock = {
  debug: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_CustomizedLoggerMock_Debug;
  dev: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_CustomizedLoggerMock_Dev;
  info: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_CustomizedLoggerMock_Info;
  warn: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_CustomizedLoggerMock_Warn;
  error: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_CustomizedLoggerMock_Error;
};

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_LoggerCustomizeSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_LoggerCustomizeReturn = Toolkit_Logger_Runner_Customize_Returns;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_Output = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_DualCopyrightHolderIsSkippedAndNeverRewritten_WarnCalls = unknown[][];

/**
 * Tests - CLI - Recipe - License - Update Copyright - CLI Recipe License Update Copyright Run - Fans Out To Every Consumer Workspace License.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_ProjectDirectory = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_Template = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_RootPath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_AppPath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_PackagePath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_StaleContent = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_IsProjectRootSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_LoadSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_ExpectedContent = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_RootOutput = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_AppOutput = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_FansOutToEveryConsumerWorkspaceLICENSE_PackageOutput = string;

/**
 * Tests - CLI - Recipe - License - Update Copyright - CLI Recipe License Update Copyright Run - Gates Each License Independently In A Mixed Tree.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_ProjectDirectory = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_Template = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_RootPath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_EditedPath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_MissingPath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_RootStaleContent = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_EditedContent = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_IsProjectRootSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_LoadSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_ExpectedRootContent = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_RootOutput = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_EditedOutput = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_GatesEachLICENSEIndependentlyInAMixedTree_MissingExists = boolean;

/**
 * Tests - CLI - Recipe - License - Update Copyright - CLI Recipe License Update Copyright Run - Hand Edited License Is Skipped And Never Rewritten.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_ProjectDirectory = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_Template = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_LicensePath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_OnDiskContent = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_IsProjectRootSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_LoadSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_CustomizedLoggerMock_Debug = ReturnType<typeof vi['fn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_CustomizedLoggerMock_Dev = ReturnType<typeof vi['fn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_CustomizedLoggerMock_Info = ReturnType<typeof vi['fn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_CustomizedLoggerMock_Warn = ReturnType<typeof vi['fn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_CustomizedLoggerMock_Error = ReturnType<typeof vi['fn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_CustomizedLoggerMock = {
  debug: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_CustomizedLoggerMock_Debug;
  dev: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_CustomizedLoggerMock_Dev;
  info: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_CustomizedLoggerMock_Info;
  warn: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_CustomizedLoggerMock_Warn;
  error: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_CustomizedLoggerMock_Error;
};

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_LoggerCustomizeSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_LoggerCustomizeReturn = Toolkit_Logger_Runner_Customize_Returns;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_Output = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_HandEditedLICENSEIsSkippedAndNeverRewritten_WarnCalls = unknown[][];

/**
 * Tests - CLI - Recipe - License - Update Copyright - CLI Recipe License Update Copyright Run - Idempotent Second Run Is A No Op.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_IdempotentSecondRunIsANoOp_ProjectDirectory = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_IdempotentSecondRunIsANoOp_Template = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_IdempotentSecondRunIsANoOp_LicensePath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_IdempotentSecondRunIsANoOp_OnDiskContent = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_IdempotentSecondRunIsANoOp_IsProjectRootSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_IdempotentSecondRunIsANoOp_LoadSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_IdempotentSecondRunIsANoOp_SaveGeneratedFileSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_IdempotentSecondRunIsANoOp_Output = string;

/**
 * Tests - CLI - Recipe - License - Update Copyright - CLI Recipe License Update Copyright Run - Missing Enable Flag Skips And Does Not Write.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MissingEnableFlagSkipsAndDoesNotWrite_ProjectDirectory = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MissingEnableFlagSkipsAndDoesNotWrite_Template = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MissingEnableFlagSkipsAndDoesNotWrite_LicensePath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MissingEnableFlagSkipsAndDoesNotWrite_OnDiskContent = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MissingEnableFlagSkipsAndDoesNotWrite_IsProjectRootSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MissingEnableFlagSkipsAndDoesNotWrite_LoadSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MissingEnableFlagSkipsAndDoesNotWrite_Output = string;

/**
 * Tests - CLI - Recipe - License - Update Copyright - CLI Recipe License Update Copyright Run - MIT Regenerates Holder And Year And Keeps Body Byte Identical.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MITRegeneratesHolderAndYearAndKeepsBodyByteIdentical_ProjectDirectory = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MITRegeneratesHolderAndYearAndKeepsBodyByteIdentical_Template = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MITRegeneratesHolderAndYearAndKeepsBodyByteIdentical_LicensePath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MITRegeneratesHolderAndYearAndKeepsBodyByteIdentical_IsProjectRootSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MITRegeneratesHolderAndYearAndKeepsBodyByteIdentical_LoadSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MITRegeneratesHolderAndYearAndKeepsBodyByteIdentical_Output = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_MITRegeneratesHolderAndYearAndKeepsBodyByteIdentical_ExpectedContent = string;

/**
 * Tests - CLI - Recipe - License - Update Copyright - CLI Recipe License Update Copyright Run - Non Nova License Is Skipped And Never Rewritten.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_NonNovaLICENSEIsSkippedAndNeverRewritten_ProjectDirectory = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_NonNovaLICENSEIsSkippedAndNeverRewritten_LicensePath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_NonNovaLICENSEIsSkippedAndNeverRewritten_OnDiskContent = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_NonNovaLICENSEIsSkippedAndNeverRewritten_IsProjectRootSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_NonNovaLICENSEIsSkippedAndNeverRewritten_LoadSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_NonNovaLICENSEIsSkippedAndNeverRewritten_Output = string;

/**
 * Tests - CLI - Recipe - License - Update Copyright - CLI Recipe License Update Copyright Run - Placeholderless Template Skips Informationally.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_ProjectDirectory = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_Template = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_LicensePath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_OnDiskContent = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_IsProjectRootSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_LoadSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_CustomizedLoggerMock_Debug = ReturnType<typeof vi['fn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_CustomizedLoggerMock_Dev = ReturnType<typeof vi['fn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_CustomizedLoggerMock_Info = ReturnType<typeof vi['fn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_CustomizedLoggerMock_Warn = ReturnType<typeof vi['fn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_CustomizedLoggerMock_Error = ReturnType<typeof vi['fn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_CustomizedLoggerMock = {
  debug: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_CustomizedLoggerMock_Debug;
  dev: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_CustomizedLoggerMock_Dev;
  info: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_CustomizedLoggerMock_Info;
  warn: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_CustomizedLoggerMock_Warn;
  error: Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_CustomizedLoggerMock_Error;
};

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_LoggerCustomizeSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_LoggerCustomizeReturn = Toolkit_Logger_Runner_Customize_Returns;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_Output = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_PlaceholderLessTemplateSkipsInformationally_InfoCalls = unknown[][];

/**
 * Tests - CLI - Recipe - License - Update Copyright - CLI Recipe License Update Copyright Run - Proprietary Regenerates Holder And Year And Keeps Body Byte Identical.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ProprietaryRegeneratesHolderAndYearAndKeepsBodyByteIdentical_ProjectDirectory = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ProprietaryRegeneratesHolderAndYearAndKeepsBodyByteIdentical_Template = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ProprietaryRegeneratesHolderAndYearAndKeepsBodyByteIdentical_LicensePath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ProprietaryRegeneratesHolderAndYearAndKeepsBodyByteIdentical_IsProjectRootSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ProprietaryRegeneratesHolderAndYearAndKeepsBodyByteIdentical_LoadSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ProprietaryRegeneratesHolderAndYearAndKeepsBodyByteIdentical_Output = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_ProprietaryRegeneratesHolderAndYearAndKeepsBodyByteIdentical_ExpectedContent = string;

/**
 * Tests - CLI - Recipe - License - Update Copyright - CLI Recipe License Update Copyright Run - Regex Special Holder Round Trips Through Fingerprint.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_RegexSpecialHolderRoundTripsThroughTheFingerprint_ProjectDirectory = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_RegexSpecialHolderRoundTripsThroughTheFingerprint_Template = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_RegexSpecialHolderRoundTripsThroughTheFingerprint_LicensePath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_RegexSpecialHolderRoundTripsThroughTheFingerprint_OldContent = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_RegexSpecialHolderRoundTripsThroughTheFingerprint_IsProjectRootSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_RegexSpecialHolderRoundTripsThroughTheFingerprint_LoadSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_RegexSpecialHolderRoundTripsThroughTheFingerprint_Output = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_RegexSpecialHolderRoundTripsThroughTheFingerprint_ExpectedContent = string;

/**
 * Tests - CLI - Recipe - License - Update Copyright - CLI Recipe License Update Copyright Run - With No Consumer Workspaces Behaves As Before.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_WithNoConsumerWorkspacesBehavesAsBefore_ProjectDirectory = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_WithNoConsumerWorkspacesBehavesAsBefore_Template = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_WithNoConsumerWorkspacesBehavesAsBefore_LicensePath = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_WithNoConsumerWorkspacesBehavesAsBefore_IsProjectRootSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_WithNoConsumerWorkspacesBehavesAsBefore_LoadSpy = ReturnType<typeof vi['spyOn']>;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_WithNoConsumerWorkspacesBehavesAsBefore_Output = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_CliRecipeLicenseUpdateCopyrightRun_WithNoConsumerWorkspacesBehavesAsBefore_ExpectedContent = string;

/**
 * Tests - CLI - Recipe - License - Update Copyright - Read Template.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Recipe_License_UpdateCopyright_ReadTemplate_LicenseId = Shared_NovaConfig_Project_License;

export type Tests_Cli_Recipe_License_UpdateCopyright_ReadTemplate_Returns = Promise<string>;

export type Tests_Cli_Recipe_License_UpdateCopyright_ReadTemplate_TemplatesDirectory = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_ReadTemplate_TemplatePath = string;

/**
 * Tests - CLI - Recipe - License - Update Copyright - Substitute.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Recipe_License_UpdateCopyright_Substitute_Template = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_Substitute_YearRange = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_Substitute_EntityName = string;

export type Tests_Cli_Recipe_License_UpdateCopyright_Substitute_Returns = string;
