/**
 * Tests - CLI - Generate - Must Haves - Agent Conventions - Run.
 *
 * @since 0.15.0
 */
export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_OriginalCwd = string;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_TemporaryDirectory = string;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_TemporaryPrefix = string;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_SandboxRoot = string;

/**
 * Tests - CLI - Generate - Must Haves - Agent Conventions - Run - Generates Claude Code Only.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_GeneratesClaudeCodeOnly_ProjectDirectory = string;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_GeneratesClaudeCodeOnly_PackageJson = string;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_GeneratesClaudeCodeOnly_PackageJsonPath = string;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_GeneratesClaudeCodeOnly_ConfigPath = string;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_GeneratesClaudeCodeOnly_ClaudeMdPath = string;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_GeneratesClaudeCodeOnly_AgentsMdPath = string;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_GeneratesClaudeCodeOnly_VisionMdPath = string;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_GeneratesClaudeCodeOnly_ProjectRulesMdPath = string;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_GeneratesClaudeCodeOnly_UniversalMdPath = string;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_GeneratesClaudeCodeOnly_AgentsMdExists = boolean;

/**
 * Tests - CLI - Generate - Must Haves - Agent Conventions - Run - Generates Codex Only.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_GeneratesCodexOnly_ProjectDirectory = string;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_GeneratesCodexOnly_PackageJson = string;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_GeneratesCodexOnly_PackageJsonPath = string;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_GeneratesCodexOnly_ConfigPath = string;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_GeneratesCodexOnly_AgentsMdPath = string;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_GeneratesCodexOnly_ClaudeMdPath = string;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_GeneratesCodexOnly_VisionMdPath = string;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_GeneratesCodexOnly_ProjectRulesMdPath = string;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_GeneratesCodexOnly_ClaudeMdExists = boolean;

/**
 * Tests - CLI - Generate - Must Haves - Agent Conventions - Run - Respects Dry Run.
 *
 * @since 0.15.0
 */
export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_RespectsDryRun_ProjectDirectory = string;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_RespectsDryRun_PackageJson = string;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_RespectsDryRun_PackageJsonPath = string;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_RespectsDryRun_ConfigPath = string;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_RespectsDryRun_Exists = boolean;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_RespectsDryRun_ClaudeMdPath = string;

/**
 * Tests - CLI - Generate - Must Haves - Agent Conventions - Run - Sets Exit Code When Not At Project Root.
 *
 * @since 0.15.0
 */
export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_SetsExitCodeWhenNotAtProjectRoot_ProjectDirectory = string;

/**
 * Tests - CLI - Generate - Must Haves - Agent Conventions - Run - Warns When No Agents Selected.
 *
 * @since 0.20.0
 */
export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_WarnsWhenNoAgentsSelected_ProjectDirectory = string;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_WarnsWhenNoAgentsSelected_PackageJson = string;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_WarnsWhenNoAgentsSelected_PackageJsonPath = string;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_WarnsWhenNoAgentsSelected_CustomizedLoggerMock_Debug = ReturnType<typeof import('vitest')['vi']['fn']>;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_WarnsWhenNoAgentsSelected_CustomizedLoggerMock_Dev = ReturnType<typeof import('vitest')['vi']['fn']>;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_WarnsWhenNoAgentsSelected_CustomizedLoggerMock_Info = ReturnType<typeof import('vitest')['vi']['fn']>;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_WarnsWhenNoAgentsSelected_CustomizedLoggerMock_Warn = ReturnType<typeof import('vitest')['vi']['fn']>;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_WarnsWhenNoAgentsSelected_CustomizedLoggerMock_Error = ReturnType<typeof import('vitest')['vi']['fn']>;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_WarnsWhenNoAgentsSelected_CustomizedLoggerMock = {
  debug: Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_WarnsWhenNoAgentsSelected_CustomizedLoggerMock_Debug;
  dev: Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_WarnsWhenNoAgentsSelected_CustomizedLoggerMock_Dev;
  info: Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_WarnsWhenNoAgentsSelected_CustomizedLoggerMock_Info;
  warn: Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_WarnsWhenNoAgentsSelected_CustomizedLoggerMock_Warn;
  error: Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_WarnsWhenNoAgentsSelected_CustomizedLoggerMock_Error;
};

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_WarnsWhenNoAgentsSelected_LoggerCustomizeSpy = ReturnType<typeof import('vitest')['vi']['spyOn']>;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_WarnsWhenNoAgentsSelected_LoggerCustomizeReturn = import('../../../../toolkit/logger.d.ts').Toolkit_Logger_Runner_Customize_Returns;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_WarnsWhenNoAgentsSelected_WarnCalls = unknown[][];

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_WarnsWhenNoAgentsSelected_HasNoAgentsWarning = boolean;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_WarnsWhenNoAgentsSelected_ClaudeMdExists = boolean;

export type Tests_Cli_Generate_MustHaves_AgentConventions_CliGenerateMustHavesAgentConventionsRun_WarnsWhenNoAgentsSelected_ClaudeMdPath = string;
